sLay = 'ATUS104'
Sch_Table['gam'][sLay] = 'Independence War'
Sch_Table['aut'][sLay] = ''
Sch_Table['key'][sLay] =
[
,
['blu','Cycle\nCamera',,,,,,],
['cyn','Wingman\nStatus',,,,,,],
['cyn','Join\nFormation',,,,,,],
['cyn','Attack\nTarget',,,,,,],
['cyn','Defend\nTarget',,,,,,],
['cyn','Form on\nTarget',,,,,,],
['cyn','Halt',,,,,,],
['cyn','Retreat',,,,,,],
['cyn','Dock on\nTarget',,,,,,],
,
['cyn','Wingman\nRequest',,,,,,],
['grn','Decrease\nSpeed',,,,,,],
['grn','Increase\nSpeed',,,,,,],
['red','Select Missile',,,,,,],
['mag','Fullscreen',,,,,,],
['yel','Last\nAttacker','Debrief',,,,,],
['yel','Nearest\nWeapon',,,,,,],
['yel','Cycle\nEnemies',,,,,,],
['yel','Nearest\nEnemy','Remote\nLog',,,,,],
['yel','Target in\nReticule',,,,,,],
['grn','Switch Roll\n/ Yaw Axes',,,,,,],
['grn','Undock',,,,,,],
['red','Fire LDSI\nMissile',,,,,,],
['yel','Next\nObjective',,'Options',,,,],
['mag','Pause',,,,,,],
,
,
,
,
['grn','Forward\nThrust',,,,,,],
['grn','Lateral\nThrust',,,,,,],
,
['red','Weapon\nMode',,,,,,],
,
['mag','Toggle\nHUD',,,,,,],
,
,
['grn','Toggle\nLDS',,,,,,],
,
,
,
['red','Weapon PBC',,,,,,],
['grn','Lateral Thrust',,,,,,],
,
['grn','Reverse\nThrust',,,,,,],
['red','Sniper\nMode',,,,,,],
['mag','Command\nSection',,,,,,],
['yel','Orb\nDisplay',,,,,,],
,
['grn','Thruster\nMode',,,,,,],
['yel','Contact\nType',,,,,,],
['yel','Contacts\nDown',,,,,,],
['yel','Contacts\nUp',,,,,,],
['yel','Target\nContact',,,,,,],
['blu','Toggle View',,,,,,],
,
,
['red','Fire Selected',,,,,,],
,
['red','Toggle TRI',,,,,,],
['red','Insta-\nShield',,,,,,],
['red','Launch\nFlare',,,,,,],
['grn','Left /\nThrust',,,,,,],
,
,
['grn','Down /\nShield',,,,,,],
['grn','Up /\nCenter',,,,,,],
['cyn','Messages',,,,,,],
,
['grn','Right /\nWeapon',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
['mag','Command\nConsole','Chase\nView',,,,,],
['mag','NAV\nConsole','Conact\nView',,,,,],
['mag','Wepaons\nConsole','Missile\nView',,,,,],
['mag','Engineer\nConsole','External\nView',,,,,],
['grn','Stop',,,,,,],
['grn','Auto\nApproach',,,,,,],
['grn','Auto\nFormate',,,,,,],
['grn','Auto\nDock',,,,,,],
['grn','Match\nVelocity',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,

]
Sch_Table['leg'][sLay] =
[
['red','Combat'],
['yel','Targeting'],
['grn','Navigation'],
['cyn','Communication'],
['blu','Camera'],
['mag','Game Controls']
]
Sch_Table['com'][sLay] = []
Sch_Table['mou'][sLay] = []
Sch_Table['joy'][sLay] = []
Sch_Table['add'][sLay] = []
sLay = 'ATUS104DVO'
Sch_Table['gam'][sLay] = Sch_Table['gam']['ATUS104']
Sch_Table['aut'][sLay] = Sch_Table['aut']['ATUS104']
Sch_Table['key'][sLay] = Sch_Table['key']['ATUS104']
Sch_Table['leg'][sLay] = Sch_Table['leg']['ATUS104']
Sch_Table['com'][sLay] = Sch_Table['com']['ATUS104']
Sch_Table['mou'][sLay] = Sch_Table['mou']['ATUS104']
Sch_Table['joy'][sLay] = Sch_Table['joy']['ATUS104']
Sch_Table['add'][sLay] = Sch_Table['add']['ATUS104']
