sLay = 'ATUS104'
Sch_Table['gam'][sLay] = 'Jane\'s USAF'
Sch_Table['aut'][sLay] = ''
Sch_Table['key'][sLay] =
[
,
,
['grn','60%\nThrust',,,'Form\nEchelon',,,],
['grn','65%\nThrust',,,'Form\nWedge',,,],
['grn','70%\nThrust',,,'Form\nTrail',,,],
['grn','80%\nThrust',,,'Form\nLine',,,],
['grn','90%\nThrust',,,,,,],
['grn','Full\nThrust',,,,,,],
['grn','After-\nburner 1',,,,,,],
['grn','After-\nburner 2',,,,,,],
['grn','Increase\nThrust',,,,,,],
['grn','Decrease\nThrust',,,,,,],
,
,
['yel','Clear Target /\nAcquire New',,,,,,],
['red','Fire Guns',,,,,,],
['yel','Radar\nSubmodes',,,,,,],
['yel','Cycle\nWaypoints +','-',,'Engage\nSimilar',,,],
,
['mag','Radar\nMFD','Toggle\nRadar','Refuel','Status',,,],
['mag','Tactical /\nJTIDS MFD',,,,,,],
,
['mag','RWR\nMFD',,,,,,],
['mag','FLIR\nMFD',,,'Show\nSquares',,,],
,
[,,,,'Protect\nMe',,,],
['red','Cycle\nWeapons +',,,,,,],
['red','Cycle\nWeapons -',,,,,,],
['red','Boresight Mode',,,,,,],
,
['yel','Cycle\nAutopilot',,,,,,],
['grn','Speed\nBrakes',,,'Sort\nTargets',,,],
['mag','Damage\nMFD',,,,,,],
['grn','Flaps',,,'Go to\nRefuel',,,],
,
[,,,,'Anchor',,,],
,
,
[,,,,'Lase My\nTarget',,,],
,
,
,
['yel','Select Target /\nNext Target','Previous',,,,,],
,
,
,
,
['mag','Cycle\nTC',,'1x TC','Close\nFormation',,,],
[,,,,'Spread\nFormation',,,],
['grn','Wheel\nBrakes','Chute',,'Bug\nOut',,,],
['mag','NAV\nMFD',,'Night\nVision',,,,],
['yel','Avionics\nMode',,,,,,],
['yel','Radar\nRange -',,,,,,],
['yel','Radar\nRange +',,,,,,],
,
,
,
,
['red','Fire Weapon',,,,,,],
,
,
,
,
['grn','Roll Left',,'Pan Left',,,,],
,
,
['grn','Nose Down',,'Pan Up',,,,],
['grn','Nose Up',,'Pan Down',,,,],
,
,
['grn','Roll Right',,'Pan Right',,,,],
,
,
['grn','Roll Left',,'Pan Left',,,,],
,
,
['grn','Nose Down',,'Pan Down',,,,],
,
['grn','Nose Up',,'Pan Up',,,,],
['grn','Rudder Left',,,,,,],
,
,
['grn','Roll Right',,'Pan Right',,,,],
,
['grn','Rudder\nRight',,,,,,],
,
,
,
,
['blu','Cockpit\nView',,,,,,],
['blu','3D Cockpit\nView',,,,,,],
['blu','Padlock\nView',,,,,,],
['blu','Target\nView',,,,,,],
['blu','Threat\nView',,,,,,],
['blu','Wingman\nView',,,,,,],
['blu','Target\nView',,,,,,],
['blu','Arcade\nView',,,,,,],
['blu','Fly-By\nView',,,,,,],
['blu','Chase\nView',,,,,,],
['blu','Weapon\nView',,,,,,],
['blu','Action\nView',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,

]
Sch_Table['leg'][sLay] =
[
['red','Combat'],
['yel','Targeting'],
['grn','Movment'],
['blu','Camera'],
['mag','Game Controls']
]
Sch_Table['com'][sLay] = []
Sch_Table['mou'][sLay] = []
Sch_Table['joy'][sLay] = []
Sch_Table['add'][sLay] = []
