sLay = 'ATUS104'
Sch_Table['gam'][sLay] = 'NetHack'
Sch_Table['aut'][sLay] = ''
Sch_Table['key'][sLay] =
[
,
,
['grn','Move SW','Escape\nto Shell',,,,,],
['grn','Move S','Auto-\npickup',,'Dual\nWeild',,,],
['grn','Move SE','Extended\nCommands',,,,,],
['grn','Move W','Current\nGold',,,,,],
,
['grn','Move E','Describe\nLast Trap',,,,,],
['grn','Move NW','Describe\nCommand',,,,,],
['grn','Move N','Current\nEquipment',,,,,],
['grn','Move NE','Current\nTool',,,,,],
['yel','Inventory','Current\nWeapon',,,,,],
,
['yel','Current\nRings','List Known\nSpells',,,,,],
,
,
['red','Quaff\nPotion','Arm Bow',,'Quit\nGame',,,],
['yel','Equip\nWeapon','Equip\nArmor',,'Wipe\nFace',,,],
['red','Eat\nFood','Engrave',,'Enhance\nSkills',,,],
['red','Read\nScroll','Unequip\nAccessory',,'Rub\nLamp',,,],
[,,'Unequip\nArmor','Teleport','Turn\nUndead',,,],
,
['red','Untrap',,,'Untrap',,,],
['yel','Inventory','Inventory\nSubset',,'Item\nAbility',,,],
['red','Open\nDoor','Options',,'Offer\nSacrifice',,,],
['red','Pay\nBill','Equip\nAccessory',,'Pray',,,],
['yel','Armor',,,,,,],
,
['blu','List Known\nObjects',,,,,,],
,
['red','Use\nTool','Unequip\nEquipment',,'Adjust\nInventory',,,],
['red','Search\nNearby','Save\nGame',,'Sit\nDown',,,],
['red','Drop\nItem','Drop\nMany','Kick','Dip\nItem',,,],
['red','Fire\nItem','Move &\nFight',,'Force\nLock',,,],
['grn','Move Until\nPiqued','Move w/o\nForks',,,,,],
,
['red','Jump',,,'Jump',,,],
['red','Kick\nObject',,,'Kick',,,],
['red','Loot\nContainer',,,'Loot',,,],
['blu','Describe\nObject','Look',,,,,],
['red','Pick Up\nItem',,,,,,],
,
,
,
,
['red','Use\nWand','Cast Spell','Suspend\nGame',,,,],
['yel','Swap\nWeapons','Discovery\nMode','Char\nInfo',,,,],
['red','Close\nDoor','Call\nMonster','Panic\nQuit','Chat',,,],
['blu','Game\nVersion','Game\nHistory',,'Compile\nOptions',,,],
,
[,,'Name\nObject',,'Name\nObject',,,],
['grn','Move w/o\nPickup','Continue',,'Use\nMonster\nAbility',,,],
[,,'Climb\nStairs',,,,,],
['red','Rest','Descend\nStairs',,,,,],
['blu','Item','Help',,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
['grn','Move NW',,,,,,],
['grn','Move W',,,,,,],
['grn','Move SW',,,,,,],
['blu','Item',,,,,,],
['grn','Move N','Game\nVersion',,,,,],
,
['grn','Move S','Untrap\nTrap',,,,,],
['yel','Inventory',,,,,,],
['yel','Equipment',,,,,,],
['grn','Move NE','Rub\nLamp',,,,,],
['grn','Move E',,,,,,],
['grn','Move SE','Quit\nGame',,,,,],
['red','Rest',,,,,,],
,
['blu','Spells',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,

]
Sch_Table['leg'][sLay] =
[
['red','Action'],
['yel','Inventory'],
['grn','Movement'],
['blu','Information']
]
Sch_Table['com'][sLay] = []
Sch_Table['mou'][sLay] = []
Sch_Table['joy'][sLay] = []
Sch_Table['add'][sLay] = []
sLay = 'ATUS104DVO'
Sch_Table['gam'][sLay] = Sch_Table['gam']['ATUS104']
Sch_Table['aut'][sLay] = Sch_Table['aut']['ATUS104']
Sch_Table['key'][sLay] = Sch_Table['key']['ATUS104']
Sch_Table['leg'][sLay] = Sch_Table['leg']['ATUS104']
Sch_Table['com'][sLay] = Sch_Table['com']['ATUS104']
Sch_Table['mou'][sLay] = Sch_Table['mou']['ATUS104']
Sch_Table['joy'][sLay] = Sch_Table['joy']['ATUS104']
Sch_Table['add'][sLay] = Sch_Table['add']['ATUS104']
