sLay = 'ATUS104'
Sch_Table['gam'][sLay] = 'Tachyon'
Sch_Table['aut'][sLay] = ''
Sch_Table['key'][sLay] =
[
,
['red','Double\nFire',,,,,,],
['red','Cycle\nPrimary',,,,,,],
['red','Cycle\nSecondary',,,,,,],
['red','Link\nPrimary',,,,,,],
['red','Link\nSecondary',,,,,,],
,
,
,
,
['grn','Match\nSpeed',,,,,,],
['grn','Zero\nThrottle',,,,,,],
['grn','Decrease\nThrottle',,,,,,],
['grn','Increase\nThrottle',,,,,,],
['grn','Full\nThrottle',,,,,,],
['grn','Afterburner',,,,,,],
['grn','Slide',,,,,,],
['grn','Roll\nLeft',,,,,,],
['grn','Roll\nRight',,,,,,],
,
['mag','Burner\nto Shield',,,,,,],
['mag','Laser\nto Shield',,,,,,],
['mag','Shield\nRear to\nFront',,,,,,],
,
['yel','Nearest\nFriendly',,,,,,],
['yel','Nearest\nNeutral',,,,,,],
['yel','Target\nPrevious',,,,,,],
['yel','Target\nNext',,,,,,],
,
,
['grn','Autopilot',,,,,,],
['grn','Left\nThrust',,,,,,],
['grn','Right\nThrust',,,,,,],
,
['mag','Shield\nto Burner',,,,,,],
['mag','Shield\nto Laser',,,,,,],
['mag','Shield\nFront to\nRear',,,,,,],
,
['yel','Nearest\nMissile',,,,,,],
['yel','Previous\nSubsys',,,,,,],
['yel','Next\nSubsys',,,,,,],
,
['yel','Target Boresight',,,,,,],
,
,
['grn','Reverse\nThrust',,,,,,],
['red','Fire\nSecondary',,,,,,],
['red','Fire ECM',,,,,,],
,
['mag','Cycle\nBurner',,,,,,],
['mag','Cycle\nLaser',,,,,,],
['mag','Cycle\nShield',,,,,,],
,
['yel','Next\nEnemy',,,,,,],
['yel','Nearest\nEnemy',,,,,,],
,
,
,
['red','Fire Primary',,,,,,],
,
,
['blu','Zoom\nCamera\nOut',,,,,,],
['blu','Move\nCamera\nLeft',,,,,,],
['grn','Turn Left',,,,,,],
['blu','Move\nCamera\nUp',,,,,,],
['blu','Move\nCamera\nDown',,,,,,],
['grn','Turn Down',,,,,,],
['grn','Turn Up',,,,,,],
['blu','Zoom\nCamera\nIn',,,,,,],
['blu','Move\nCamera\nRight',,,,,,],
['grn','Turn Right',,,,,,],
,
['cyn','Chat\nBegin',,,,,,],
['cyn','Break\nTalker',,,,,,],
['cyn','Previous\nPlayer',,,,,,],
,
['cyn','Special\nChat',,,,,,],
,
['cyn','Option\nMenu',,,,,,],
['cyn','Last\nTalker',,,,,,],
['cyn','Player\nList',,,,,,],
['cyn','Messages',,,,,,],
['cyn','Mute\nTalker',,,,,,],
['cyn','Next\nPlayer',,,,,,],
['cyn','Select\nTarget',,,,,,],
['cyn','Cycle\nDisplay',,,,,,],
['cyn','Mute',,,,,,],
['cyn','Talk',,,,,,],
,
['blu','Cockpit\nView',,,,,,],
['blu','External\nView',,,,,,],
['blu','Target\nView',,,,,,],
,
['blu','Look\nUp',,,,,,],
['blu','Look\nLeft',,,,,,],
['blu','Look\nRight',,,,,,],
['blu','Look\nDown',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,

]
Sch_Table['leg'][sLay] =
[
['red','Combat'],
['yel','Targeting'],
['grn','Navigation'],
['cyn','Communication'],
['blu','Camera'],
['mag','Power Systems']
]
Sch_Table['com'][sLay] = []
Sch_Table['mou'][sLay] = []
Sch_Table['joy'][sLay] = []
Sch_Table['add'][sLay] = []
sLay = 'ATUS104DVO'
Sch_Table['gam'][sLay] = Sch_Table['gam']['ATUS104']
Sch_Table['aut'][sLay] = Sch_Table['aut']['ATUS104']
Sch_Table['key'][sLay] = Sch_Table['key']['ATUS104']
Sch_Table['leg'][sLay] = Sch_Table['leg']['ATUS104']
Sch_Table['com'][sLay] = Sch_Table['com']['ATUS104']
Sch_Table['mou'][sLay] = Sch_Table['mou']['ATUS104']
Sch_Table['joy'][sLay] = Sch_Table['joy']['ATUS104']
Sch_Table['add'][sLay] = Sch_Table['add']['ATUS104']
