sLay = 'ATUS104'
Sch_Table['gam'][sLay] = 'SimCity 4'
Sch_Table['aut'][sLay] = ''
Sch_Table['key'][sLay] =
[
,
[,,,'Pause\nGame',,,,],
['blu','Zoom\nLevel 1',,'Turtle\nSpeed',,,,],
['blu','Zoom\nLevel 2',,'Rhino\nSpeed',,,,],
['blu','Zoom\nLevel 3',,'Cheetah\nSpeed',,,,],
['blu','Zoom\nLevel 4',,,,,,],
['blu','Zoom\nLevel 5',,,,,,],
,
,
,
,
,
['blu','Zoom Out',,,,,,],
['blu','Zoom In',,,,,,],
,
,
['red','Light\nResidential',,,,,,],
['red','Medium\nResidential',,,,,,],
['red','Heavy\nResidential',,,,,,],
['red','Roads','Highway',,'Street',,,],
['red','Rails','Subway',,,,,],
['red','Landfill',,,,,,],
,
['red','Pipes',,,,,,],
,
['red','Small\nPolice Stn','Jail','Dispatch','Large',,,],
,
,
,
,
['red','Light\nCommercial',,,,,,],
['red','Medium\nResidential',,,,,,],
['red','Heavy\nResidential',,,,,,],
['red','Small\nFire Stn',,'Dispatch','Large',,,],
['mag','Toggle\nGrid',,,,,,],
['red','Small\nClinic',,,'Large',,,],
,
['red','Small\nSchool','College',,'High',,,],
['red','Power\nLines',,,,,,],
,
,
,
,
,
,
['red','Agricultural',,,,,,],
['red','Medium\nIndustrial',,'Cheat',,,,],
['red','Heavy\nIndustrial',,,,,,],
['red','Remove\nZones',,,,,,],
['red','Demolish',,,,,,],
,
,
,
,
['red','Query Tool',,,,,,],
,
,
,
['blu','Center on Cursor',,,,,,],
,
,
,
,
['blu','Scroll Left',,'Scroll\nOnce',,,,],
['red','Building\nClockwise',,,,,,],
['red','Building\nCounter-\nclockwise',,,,,,],
['blu','Scroll Up',,'Scroll\nOnce',,,,],
['blu','Scroll Down',,'Scroll\nOnce',,,,],
['blu','Rotate\nCounter-\nclockwise',,,,,,],
['blu','Rotate\nClockwise',,,,,,],
['blu','Scroll Roght',,'Scroll\nOnce',,,,],
['mag','Toggle\nInteface',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
['mag','Cancel /\nDefault\nTool',,,,,,],
['mag','God\nMode',,,,,,],
['mag','Mayor\nMode',,,,,,],
['mag','My Sim\nMode',,,,,,],
['mag','City\nOptions',,,,,,],
['mag','Day Only',,,,,,],
['mag','Night Only',,,,,,],
['mag','Day &\nNight',,,,,,],
['mag','Exit to\nRegion',,,,,,],
['mag','Graphic\nOptions',,,,,,],
['mag','Audio\nOptions',,,,,,],
['mag','Gameplay\nOptions',,,,,,],
['mag','Quit Game',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,

]
Sch_Table['leg'][sLay] =
[
['red','Actions/Tools'],
['blu','Camera'],
['mag','Game Controls']
]
Sch_Table['com'][sLay] =
[
'CTRL + SHIFT + R = Build Bus Stop',
'CTRL + SHIFT + T = Build Passenger Depot',
'CTRL + ALT + T = Build Freight Depot',
'SHIFT + ALT + T = Build Subway Station',
'CTRL + SHIFT + A = Open Phot Album',
'CTRL + SHIFT + S = Take Snapshot',
'CTRL + SHIFT + ALT + F = Refresh Screen',
'CTRL + SHIFT + C = Toggle Terrain Contours',
'CTRL + SHIFT + O = Obliterate City'
]
Sch_Table['mou'][sLay] = []
Sch_Table['joy'][sLay] = []
Sch_Table['add'][sLay] = []
sLay = 'ATUS104DVO'
Sch_Table['gam'][sLay] = Sch_Table['gam']['ATUS104']
Sch_Table['aut'][sLay] = Sch_Table['aut']['ATUS104']
Sch_Table['key'][sLay] = Sch_Table['key']['ATUS104']
Sch_Table['leg'][sLay] = Sch_Table['leg']['ATUS104']
Sch_Table['com'][sLay] = Sch_Table['com']['ATUS104']
Sch_Table['mou'][sLay] = Sch_Table['mou']['ATUS104']
Sch_Table['joy'][sLay] = Sch_Table['joy']['ATUS104']
Sch_Table['add'][sLay] = Sch_Table['add']['ATUS104']
