sLay = 'ATUS104'
Sch_Table['gam'][sLay] = 'Flight Sim Toolkit'
Sch_Table['aut'][sLay] = ''
Sch_Table['key'][sLay] =
[
,
,
['grn','10%\nSpeed',,,,,,],
['grn','20%\nSpeed',,,,,,],
['grn','30%\nSpeed',,,,,,],
['grn','40%\nSpeed',,,,,,],
['grn','50%\nSpeed',,,,,,],
['grn','60%\nSpeed',,,,,,],
['grn','70%\nSpeed',,,,,,],
['grn','80%\nSpeed',,,,,,],
['grn','90%\nSpeed',,,,,,],
['grn','100%\nSpeed',,,,,,],
['grn','Speed +','Zero\nSpeed',,,,,],
['grn','Speed -','Max\nSpeed',,,,,],
['red','Select Weapon',,,,,,],
['blu','View\nNext Object',,,,,,],
['mag','Engine\nSound',,'All\nSounds',,,,],
['grn','Wheel\nBrakes',,,,,,],
['grn','Engine',,'Eject',,,,],
,
[,,,,'Show\nResources',,,],
,
,
['yel','ILS',,,,,,],
['blu','Track\nView',,,'Options',,,],
['blu','Padlock\nView',,,'Pause',,,],
['yel','Next Radial\n(VOR1)','Prev',,,,,],
,
['yel','Next Radial\n(VOR2)','Prev',,,,,],
,
,
['grn','Raise\nFlaps',,'Haze +','Haze -',,,],
['blu','Target\nTracking',,,,,,],
['red','Flare',,,'Show\nVector',,,],
['grn','Gear',,'Toggle Grid','Screenshot',,,],
[,,,,'Toggle\nHUD',,,],
[,,,'Jettison','Show\nJoystick',,,],
,
,
['yel','Next VOR','Prev\nVOR',,,,,],
,
,
['red','Select Weapon',,,,,,],
,
,
,
['grn','Lower\nFlaps',,,'Exit',,,],
['red','Chaff',,,,,,],
['blu','Chase\nView',,,'Pilot\nView',,,],
['grn','Air\nBrakes',,'Baro Alti','Toggle\nLag',,,],
[,,,'Radar\nAlti',,,,],
[,,,'Map','Missile\nView',,,],
['grn','Rudder\nLeft',,,,,,],
['grn','Rudder\nRight',,,,,,],
['yel','Next NDB','Prev\nNDB',,,,,],
,
,
,
['red','Fire Weapon',,,,,,],
,
,
,
,
['grn','Bank\nLeft',,,,,,],
,
,
['grn','Nose\nDown',,,,,,],
['grn','Nose\nUp',,,,,,],
['blu','Zoom\nIn',,,,,,],
['blu','Zoom\nOut',,,,,,],
['grn','Bank\nRight',,,,,,],
,
,
['grn','Bank\nLeft',,,,,,],
,
,
['grn','Nose\nDown',,,,,,],
,
['grn','Nose\nUp',,,,,,],
['grn','Rudder Left',,,,,,],
['grn','Zero Trim',,,,,,],
['blu','Zoom\nIn',,,,,,],
['grn','Bank\nRight',,,,,,],
['blu','Zoom\nOut',,,,,,],
['grn','Rudder\nRight',,,,,,],
['grn','More Trim',,,,,,],
['grn','Less Trim',,,,,,],
,
['mag','Options',,,,,,],
['blu','Look\nForward','Back',,'Center',,,],
['blu','Look\nLeft 60\u00b0',,,,,,],
['blu','Look\nRight 60\u00b0',,,,,,],
['blu','Move\nCockpit',,,,,,],
['blu','Look\nLeft 120\u00b0',,,,,,],
['blu','Look\nRight 120\u00b0',,,,,,],
['blu','Pan Left',,,,,,],
['blu','Pan Right',,,,,,],
['blu','Pan Up',,,,,,],
['blu','Pan Down',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,

]
Sch_Table['leg'][sLay] =
[
['red','Combat'],
['yel','Guidance/Radar'],
['grn','Navigation'],
['blu','Camera'],
['mag','Game Controls']
]
Sch_Table['com'][sLay] = []
Sch_Table['mou'][sLay] = []
Sch_Table['joy'][sLay] = []
Sch_Table['add'][sLay] = []
sLay = 'ATUS104DVO'
Sch_Table['gam'][sLay] = Sch_Table['gam']['ATUS104']
Sch_Table['aut'][sLay] = Sch_Table['aut']['ATUS104']
Sch_Table['key'][sLay] = Sch_Table['key']['ATUS104']
Sch_Table['leg'][sLay] = Sch_Table['leg']['ATUS104']
Sch_Table['com'][sLay] = Sch_Table['com']['ATUS104']
Sch_Table['mou'][sLay] = Sch_Table['mou']['ATUS104']
Sch_Table['joy'][sLay] = Sch_Table['joy']['ATUS104']
Sch_Table['add'][sLay] = Sch_Table['add']['ATUS104']
