sLay = 'ATUS104'
Sch_Table['gam'][sLay] = 'Nexus: TJI'
Sch_Table['aut'][sLay] = ''
Sch_Table['key'][sLay] =
[
,
,
['yel','Select\nGroup','Select\nShip','Assign\nGroup',,,,],
['yel','Select\nGroup','Select\nShip','Assign\nGroup',,,,],
['yel','Select\nGroup','Select\nShip','Assign\nGroup',,,,],
['yel','Select\nGroup','Select\nShip','Assign\nGroup',,,,],
[,,'Select\nShip',,,,,],
[,,'Select\nShip',,,,,],
[,,'Select\nShip',,,,,],
[,,'Select\nShip',,,,,],
[,,'Select\nShip',,,,,],
,
,
,
['yel','Select All Ships\nin Group',,,,,,],
,
,
,
,
['mag','Repair',,,,,,],
,
,
,
,
['mag','Info',,,,,,],
,
,
,
,
,
['yel','Select All\nCapital\nShips',,,,,,],
['yel','Select All\nSmall\nShips',,'Select\nShips\nDocked\nw/ This',,,,],
,
,
,
,
,
,
,
,
,
,
,
['blu','Free\nMove',,,,,,],
,
,
,
,
,
,
['blu','Create\nNAV Point',,,,,,],
['mag','Manual',,,,,,],
,
,
,
['blu','Free\nMove',,,,,,],
,
,
['mag','Pause',,,,,,],
,
,
['blu','Lock\nCamera\non Target',,,,,,],
['blu','Delete\nNAV Point',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
['mag','In-Game\nMenu',,,,,,],
['red','Auto',,,,,,],
['red','Approach',,,,,,],
['red','Hold\nPosition',,,,,,],
['red','Run Away',,,,,,],
['red','Drain\nShield',,,,,,],
['red','Attack\nDevices',,,,,,],
['red','Destroy\nHull',,,,,,],
['red','Artillery',,,,,,],
['red','Special\nWeapon',,,,,,],
['red','Recon',,,,,,],
['red','Guard',,,,,,],
['red','IP Drive',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,

]
Sch_Table['leg'][sLay] =
[
['red','Action'],
['yel','Selection'],
['blu','Miscellaneous'],
['mag','Game Menus']
]
Sch_Table['com'][sLay] =
[
'Ctrl + Shift + 1 - 9	Add/Remove Capital Ship from Selection'
]
Sch_Table['mou'][sLay] = []
Sch_Table['joy'][sLay] = []
Sch_Table['add'][sLay] = []
sLay = 'ATUS104DVO'
Sch_Table['gam'][sLay] = Sch_Table['gam']['ATUS104']
Sch_Table['aut'][sLay] = Sch_Table['aut']['ATUS104']
Sch_Table['key'][sLay] = Sch_Table['key']['ATUS104']
Sch_Table['leg'][sLay] = Sch_Table['leg']['ATUS104']
Sch_Table['com'][sLay] = Sch_Table['com']['ATUS104']
Sch_Table['mou'][sLay] = Sch_Table['mou']['ATUS104']
Sch_Table['joy'][sLay] = Sch_Table['joy']['ATUS104']
Sch_Table['add'][sLay] = Sch_Table['add']['ATUS104']
