sLay = 'ATUS104'
Sch_Table['gam'][sLay] = 'Temple of Elemental Evil'
Sch_Table['aut'][sLay] = ''
Sch_Table['key'][sLay] =
[
,
['yel','Select\nAll Units',,,,,,],
['yel','Select\nUnit','Add to\nSelection',,,,,],
['yel','Select\nUnit','Add to\nSelection',,,,,],
['yel','Select\nUnit','Add to\nSelection',,,,,],
['yel','Select\nUnit','Add to\nSelection',,,,,],
['yel','Select\nUnit','Add to\nSelection',,,,,],
['yel','Select\nUnit','Add to\nSelection',,,,,],
['yel','Select\nUnit','Add to\nSelection',,,,,],
['yel','Select\nUnit','Add to\nSelection',,,,,],
,
,
,
,
,
['blu','Highlight\nItems',,,,,,],
[,,,,'Quit\nGame',,,],
,
,
['red','Rest',,,,,,],
,
,
,
['mag','Inventory',,,,,,],
['mag','Options',,,,,,],
,
,
,
,
,
,
,
,
['red','Formation',,,,,,],
,
['mag','Help',,,,,,],
,
,
['mag','Logbook',,,,,,],
,
,
,
['red','Accept\nCommand',,,,,,],
,
,
,
,
['red','Combat\nMode',,,,,,],
,
,
,
['mag','Map',,,,,,],
,
,
,
['red','Spontaneous\nCasting',,,,,,],
['mag','Assign\nHotkey',,,,,,],
['red','Movement /\nWaypoints',,,,,,],
['red','End Turn',,,,,,],
,
,
,
,
['blu','Pan\nLeft',,,,,,],
['blu','Center\non Unit',,,,,,],
,
['blu','Pan\nUp',,,,,,],
['blu','Pan\nDown',,,,,,],
,
,
['blu','Pan\nRight',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
['mag','Main Menu\n/ Cancel\nCommand',,,,,,],
['yel','Select\nGroup',,'Assign',,,,],
['yel','Select\nGroup',,'Assign',,,,],
['yel','Select\nGroup',,'Assign',,,,],
['yel','Select\nGroup',,'Assign',,,,],
['yel','Select\nGroup',,'Assign',,,,],
['yel','Select\nGroup',,'Assign',,,,],
['yel','Select\nGroup',,'Assign',,,,],
['yel','Select\nGroup',,'Assign',,,,],
['mag','Quick\nLoad',,,,,,],
,
,
['mag','Quick\nSave',,,,,,],
['mag','Screenshot',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,

]
Sch_Table['leg'][sLay] =
[
['red','Action'],
['yel','Selection'],
['blu','Camera'],
['mag','Game Controls']
]
Sch_Table['com'][sLay] = []
Sch_Table['mou'][sLay] = []
Sch_Table['joy'][sLay] = []
Sch_Table['add'][sLay] = []
