sLay = 'ATUS104'
Sch_Table['gam'][sLay] = 'StarLancer'
Sch_Table['aut'][sLay] = ''
Sch_Table['key'][sLay] =
[
,
['grn','After-\nburner',,,,,,],
['blu','Cockpit\nView',,,,,,],
['blu','Left\nView',,,,,,],
['blu','Right\nView',,,,,,],
['blu','Rear\nView',,,,,,],
['blu','Fly-by\nView',,,,,,],
['blu','Target\nView',,,,,,],
['blu','External\nView',,,,,,],
['blu','Missile\nView',,,,,,],
,
,
['grn','Decrease\nThrust',,,,,,],
['grn','Increase\nThrust',,,,,,],
['grn','Zero Thrust',,,,,,],
['grn','Afterburner','Reverse\nThrust',,,,,],
['yel','Next\nFriendly','Prev',,,,,],
['yel','Nearest\nFriendly',,,,,,],
['yel','Next\nEnemy','Prev','Auto\nTarget',,,,],
['yel','Nearest\nEnemy',,,,,,],
['yel','Target\nTorpedo',,,,,,],
['yel','Target in\nReticule',,,,,,],
['mag','Full Power\nto Guns',,,,,,],
['mag','Full Power\nto Engines',,,,,,],
['mag','Full Power\nto Shields',,,,,,],
['mag','Powerball','Lock',,,,,],
['mag','Equalize\nPower',,,,,,],
['grn','Full Thrust',,,,,,],
,
,
['yel','Primary\nTarget',,,,,,],
['yel','Next\nSubtarget','Prev',,,,,],
['red','Damage','Lock',,,,,],
['red','Full Guns',,,,,,],
['red','Guns','Lock','Sync Guns',,,,],
['red','Counter-\nmeasure',,,,,,],
['grn','Jump Drive',,,,,,],
['red','Cloak',,,,,,],
['red','ECM',,,,,,],
['mag','Spectral\nShields',,,,,,],
['cyn','Send\nMessage',,,,,,],
,
['red','Launch Missile',,,,,,],
,
,
['grn','Match\nSpeed',,,,,,],
['cyn','Wing\nStatus','Lock',,,,,],
['cyn','Comms',,,,,,],
['yel','Radar',,,,,,],
['yel','Objectives',,,,,,],
['mag','Shield\nBalancing',,,,,,],
['red','Missiles',,,,,,],
['red','Cycle\nMissiles\nLeft',,,,,,],
['red','Cycle\nMissiles\nRight',,,,,,],
['grn','Joystick\nRoll',,,,,,],
,
,
,
['red','Fire Lasers',,,,,,],
,
,
,
,
['grn','Yaw Left',,,,,,],
['grn','Roll Left',,,,,,],
['grn','Strafe Left',,,,,,],
['grn','Pitch Down',,,,,,],
['grn','Pitch Up',,,,,,],
['grn','Roll\nRight',,,,,,],
['grn','Strafe\nRight',,,,,,],
['grn','Yaw Right',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
['gry','Key\nConfig',,,,,,],
,
,
,
['cyn','Attack My\nTarget',,,,,,],
['cyn','Back\nOff',,,,,,],
['cyn','Help\nMe',,,,,,],
['cyn','Permission\nto Land',,,,,,],
,
['red','Display\nKills',,,,,,],
,
['grn','Eject',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,

]
Sch_Table['leg'][sLay] =
[
['red','Combat'],
['yel','Targeting'],
['grn','Navigation'],
['cyn','Communication'],
['blu','Camera'],
['mag','Power Systems'],
['gry','Game Controls']
]
Sch_Table['com'][sLay] = []
Sch_Table['mou'][sLay] = []
Sch_Table['joy'][sLay] = []
Sch_Table['add'][sLay] = []
sLay = 'ATUS104DVO'
Sch_Table['gam'][sLay] = Sch_Table['gam']['ATUS104']
Sch_Table['aut'][sLay] = Sch_Table['aut']['ATUS104']
Sch_Table['key'][sLay] = Sch_Table['key']['ATUS104']
Sch_Table['leg'][sLay] = Sch_Table['leg']['ATUS104']
Sch_Table['com'][sLay] = Sch_Table['com']['ATUS104']
Sch_Table['mou'][sLay] = Sch_Table['mou']['ATUS104']
Sch_Table['joy'][sLay] = Sch_Table['joy']['ATUS104']
Sch_Table['add'][sLay] = Sch_Table['add']['ATUS104']
