sLay = 'ATUS104'
Sch_Table['gam'][sLay] = 'Project Earth'
Sch_Table['aut'][sLay] = ''
Sch_Table['key'][sLay] =
[
,
,
['yel','Select\nGroup','Add','Assign','Focus',,,],
['yel','Select\nGroup','Add','Assign','Focus',,,],
['yel','Select\nGroup','Add','Assign','Focus',,,],
['yel','Select\nGroup','Add','Assign','Focus',,,],
['yel','Select\nGroup','Add','Assign','Focus',,,],
['yel','Select\nGroup','Add','Assign','Focus',,,],
['yel','Select\nGroup','Add','Assign','Focus',,,],
['yel','Select\nGroup','Add','Assign','Focus',,,],
['yel','Select\nGroup','Add','Assign','Focus',,,],
,
['blu','Zoom\nOut',,,,,,],
['blu','Zoom\nIn',,,,,,],
,
['yel','Next Group',,,,,,],
,
['blu','View\nBattle',,,,,,],
['red','Sell',,,,,,],
['red','Repair',,,'Stop\nRepair',,,],
['yel','Select All\nof Type',,,,,,],
,
,
['mag','Messages',,,,,,],
['red','Offense',,,,,,],
['yel','Select\nMilitary',,,,,,],
['yel','Select\nPrevious',,,,,,],
['yel','Select\nNext',,,,,,],
['mag','Mission\nInfo',,,,,,],
,
['yel','Select\nAll',,,,,,],
['red','Stop',,,,,,],
['red','Defense',,,,,,],
['red','Follow\nMode',,,,,,],
,
['yel','Select\nCritical',,,,,,],
,
['red','Repair',,,'Stop\nRepair',,,],
['red','Sell',,,,,,],
,
,
,
,
,
,
,
['red','Scatter',,,,,,],
['blu','Center\nView',,,,,,],
['red','Recall\nHarvesters',,,,,,],
,
,
['red','Retreat',,,,,,],
['yel','Select\nPrevious',,,,,,],
['yel','Select\nNext',,,,,,],
,
,
,
,
['blu','Next Battle',,,,,,],
,
,
['yel','Highlight\nShips',,,,,,],
['red','Self\nDestruct',,,,,,],
['blu','Pan Left',,,,,,],
['yel','Select\nCritical',,,,,,],
['blu','View\nBattle',,,,,,],
['blu','Pan Ahead',,,,,,],
['blu','Pan Back',,,,,,],
['blu','Pan Up',,,,,,],
['blu','Pan Down',,,,,,],
['blu','Pan Right',,,,,,],
,
['yel','Select\nCritical',,,,,,],
['blu','Pan Left',,,,,,],
['blu','View Battle',,,,,,],
,
['blu','Pan Ahead',,,,,,],
['blu','Center\nView',,,,,,],
['blu','Pan Back',,,,,,],
['yel','Highlight\nShips',,,,,,],
,
['blu','Pan Up',,,,,,],
['blu','Pan Right',,,,,,],
['blu','Pan Down',,,,,,],
['red','Self-\nDestruct',,,,,,],
['blu','Zoom Out',,,,,,],
['blu','Zoom In',,,,,,],
,
['mag','Main\nMenu',,,,,,],
['blu','Battle 1',,,,,,],
['blu','Battle 2',,,,,,],
['blu','Battle 3',,,,,,],
,
,
,
,
,
['blu','Load\nCamera',,'Camera\nSet',,,,],
['blu','Load\nCamera',,'Camera\nSet',,,,],
['blu','Load\nCamera',,'Camera\nSet',,,,],
['blu','Load\nCamera',,'Camera\nSet',,,,],
,                     
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,

]
Sch_Table['leg'][sLay] =
[
['red','Action'],
['yel','Selection'],
['blu','Camera'],
['mag','Menus']
]
Sch_Table['com'][sLay] = []
Sch_Table['mou'][sLay] = []
Sch_Table['joy'][sLay] = []
Sch_Table['add'][sLay] = []
sLay = 'ATUS104DVO'
Sch_Table['gam'][sLay] = Sch_Table['gam']['ATUS104']
Sch_Table['aut'][sLay] = Sch_Table['aut']['ATUS104']
Sch_Table['key'][sLay] = Sch_Table['key']['ATUS104']
Sch_Table['leg'][sLay] = Sch_Table['leg']['ATUS104']
Sch_Table['com'][sLay] = Sch_Table['com']['ATUS104']
Sch_Table['mou'][sLay] = Sch_Table['mou']['ATUS104']
Sch_Table['joy'][sLay] = Sch_Table['joy']['ATUS104']
Sch_Table['add'][sLay] = Sch_Table['add']['ATUS104']
