sLay = 'ATUS104'
Sch_Table['gam'][sLay] = 'Homeworld 2'
Sch_Table['aut'][sLay] = ''
Sch_Table['key'][sLay] =
[
,
,
['yel','Select\nGroup',,'Assign','Build\nItem',,,],
['yel','Select\nGroup',,'Assign','Build\nItem',,,],
['yel','Select\nGroup',,'Assign','Build\nItem',,,],
['yel','Select\nGroup',,'Assign','Build\nItem',,,],
['yel','Select\nGroup',,'Assign','Build\nItem',,,],
['yel','Select\nGroup',,'Assign','Build\nItem',,,],
['yel','Select\nGroup',,'Assign','Build\nItem',,,],
['yel','Select\nGroup',,'Assign','Build\nItem',,,],
['yel','Select\nGroup',,'Assign','Build\nItem',,,],
['yel','Select\nGroup',,'Assign','Build\nItem',,,],
[,,,'Unassign\nFrom All',,,,],
,
['mag','Cycle HUDs',,,,,,],
['mag','Tactical Overlay',,,,,,],
['mag','Queue',,,'Sensors',,,],
['red','Waypoint',,,'Platform',,,'icon_hw2_waypoint.png'],
['red','EMP',,,'Pause\nShip',,,'icon_hw2_emp.png'],
['mag','Research\nManager',,,'Frigate',,,],
['red','Def Field',,,'Utility',,,'icon_hw2_field.png'],
['red','Repair',,,,,,'icon_hw2_repair.png'],
['red','Capture',,,,,,],
['mag','Fleet Info',,,,,,],
['mag','Objective',,,,,,],
['red','Rally Pt','Parade','Rally Obj',,,,'icon_hw2_rally.png'],
['red','Previous\nTactic',,,,,,],
['red','Next\nTactic',,,,,,],
,
['yel','Select All',,,,,,],
['yel','Military\nSelection',,,'Capital',,,],
['red','Stop',,,,,,'icon_hw2_stop.png'],
['red','Dock',,,'Module',,,'icon_hw2_dock.png'],
['yel','Focus on\nSelected',,,'Fighter',,,],
['red','Guard',,,'Pause\nSubsys',,,'icon_hw2_guard.png'],
['red','Harvest',,,,,,'icon_hw2_harvest.png'],
['red','Jump',,,,,,'icon_hw2_jump.png'],
['mag','Diplomacy',,'Speech\nRecall',,,,],
['mag','Launch\nManager',,'Close','Show All',,,],
,
['red','Special\nCommand',,,,,,],
,
['mag','Chat',,,,,,],
,
,
['red','Special\nAttack',,,,,,],
['red','Ping',,,'Cancel\nShip',,,'icon_hw2_ping.png'],
['red','Cloak',,,'Corvette',,,'icon_hw2_cloak.png'],
['mag','Events',,,'Cancel\nBuild\nSubsys',,,],
['mag','Build\nManager',,'Close',,,,],
['red','Lay Mine',,,,,,'icon_hw2_mine.png'],
['red','Move','Vertical\nMove',,,,,'icon_hw2_move.png'],
['yel','Next Idle\nMilitary',,,,,,],
['yel','Next Idle\nCollector',,,,,,],
,
,
['red','Attack',,,,,,'icon_hw2_attack.png'],
,
['yel','Sensors Manager',,,,,,],
,
,
['blu','Pan\nUp',,,,,,],
['blu','Pan\nDown',,,,,,],
['blu','Pan\nLeft',,,,,,],
['yel','Focus on\nBuild-\nCapable',,,,,,],
['yel','Focus on\nEvent',,,,,,],
['blu','Pan\nForward',,,'Pan\nUp',,,],
['blu','Pan\nBack',,,'Pan\nDown',,,],
['yel','Next\nFocus',,,,,,],
['yel','Previous\nFocus',,,,,,],
['blu','Pan\nRight',,,,,,],
,
['yel','Focus on\nBuild-\nCapable',,,,,,],
['blu','Pan\nLeft',,,,,,],
['yel','Focus on\nEvent',,,,,,],
,
['blu','Pan\nForward',,,'Pan\nUp',,,],
,
['blu','Pan\nBack',,,'Pan\nDown',,,],
['blu','Pan\nUp',,,,,,],
,
['yel','Next\nFocus',,,,,,],
['blu','Pan\nRight',,,,,,],
['yel','Previous\nFocus',,,,,,],
['blu','Pan\nDown',,,,,,],
,
,
['mag','Chat',,,,,,],
['yel','Cancel\nSelect',,,'Min',,,],
['mag','Help',,,,,,],
['red','Passive\nBehavior',,,,,,],
['red','Defense\nBehavior',,,,,,],
['red','Aggressive\nBehavior',,,'Quit',,,],
['red','Capital\nPhalanx\nFormation',,'Save',,,,],
['red','Frigate\nLine\nFormation',,,,,,],
['red','Fighter\nScreen\nFormation',,,,,,],
['red','Disband\nFormation','Restart','Load',,,,],
,
['mag','Game\nMenu',,,,,,],
,
,
,
['mag','Screenshot',,,,,,],
['mag','Pause',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,

]
Sch_Table['leg'][sLay] =
[
['red','Action'],
['yel','Selection'],
['blu','Camera'],
['mag','Menus']
]
Sch_Table['com'][sLay] =
[
'Retire = Shift + Ctrl + X',
'Scuttle = Shift + Ctrl + S',
'Clear All Groups = Shift + Ctrl + -'
]
Sch_Table['mou'][sLay] = []
Sch_Table['joy'][sLay] = []
Sch_Table['add'][sLay] = []
sLay = 'ATUS104DVO'
Sch_Table['gam'][sLay] = Sch_Table['gam']['ATUS104']
Sch_Table['aut'][sLay] = Sch_Table['aut']['ATUS104']
Sch_Table['key'][sLay] = Sch_Table['key']['ATUS104']
Sch_Table['leg'][sLay] = Sch_Table['leg']['ATUS104']
Sch_Table['com'][sLay] = Sch_Table['com']['ATUS104']
Sch_Table['mou'][sLay] = Sch_Table['mou']['ATUS104']
Sch_Table['joy'][sLay] = Sch_Table['joy']['ATUS104']
Sch_Table['add'][sLay] = Sch_Table['add']['ATUS104']
