sLay = 'ATUS104'
Sch_Table['gam'][sLay] = 'Titans of Steel: Warring Suns'
Sch_Table['aut'][sLay] = ''
Sch_Table['key'][sLay] =
[       
,
,
['yel','Teammate\nStatus',,,,,,],
['yel','Teammate\nStatus',,,,,,],
['yel','Teammate\nStatus',,,,,,],
['yel','Teammate\nStatus',,,,,,],
['yel','Teammate\nStatus',,,,,,],
['yel','Teammate\nStatus',,,,,,],
['yel','Teammate\nStatus',,,,,,],
['yel','Teammate\nStatus',,,,,,],
,
,
,
,
,
,
,
,
['blu','Show\nExit\nArea',,,,,,],
['cyn','Recover\nSync',,,,,,],
['blu','Show\nTarget\nArea',,,,,,],
['red','Wait on\nNew Foe',,,,,,],
,
,
,
['mag','Screenshot',,,,,,],
,
,
,
,
['red','Toggle\nAI Control',,,,,,],
,
,
,
,
,
,
,
,
['blu','Toggle\nGrid',,,,,,],
,
,
['red','Confirm\nAction',,,,,,],
,
,
['red','Wait on\nLocked\nFoe',,,,,,],
['red','Wait on\nRecycle\nWeapon',,,'Exit\nBattle',,,],
['cyn','Chat',,,,,,],
,
,
,
['red','Respawn\nMap',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
['blu','Scroll\nLeft',,,,,,],
['blu','Center\non Unit',,,,,,],
['blu','Center\non Target',,,,,,],
['blu','Scroll\nUp',,,,,,],
['blu','Scroll\nDown',,,,,,],
,
,
['blu','Scroll\nRight',,,,,,],
,
,
,
,
['blu','Toggle\nWeapon\nRanges',,,,,,],
,
,
,
,
['blu','Toggle\nScanner\nRanges',,,,,,],
,
,
,
,
['blu','Toggle\nOverlay',,,,,,],
['blu','Toggle\nArc of\nFire',,,,,,],
['red','Confirm\nAction',,,,,,],
['mag','Close\nWindow',,,,,,],
['mag','Help\nScreen',,,,,,],
['mag','Team\nStats',,,,,,],
['mag','Gameplay\nOptions',,,,,,],
['mag','Engine\nOptions',,,,,,],
['mag','Recall\nMessages',,,,,,],
['mag','Scanner\nDatabase',,,,,,],
['mag','Save\nGame',,,,,,],
['mag','Load\nGame',,,,,,],
['mag','Mission\nBriefing',,,,,,],
['mag','Mission\nStatus',,,,,,],
['mag','Next\nPage','Prev',,,,,],
['mag','Toggle\nMusic',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,

]
Sch_Table['leg'][sLay] =
[
['red','Actions/Orders'],
['yel','Selection'],
['blu','Camera/Display'],
['cyn','Multiplayer'],
['mag','Game Copntrols']
]
Sch_Table['com'][sLay] = []
Sch_Table['mou'][sLay] = []
Sch_Table['joy'][sLay] = []
Sch_Table['add'][sLay] = []
sLay = 'ATUS104DVO'
Sch_Table['gam'][sLay] = Sch_Table['gam']['ATUS104']
Sch_Table['aut'][sLay] = Sch_Table['aut']['ATUS104']
Sch_Table['key'][sLay] = Sch_Table['key']['ATUS104']
Sch_Table['leg'][sLay] = Sch_Table['leg']['ATUS104']
Sch_Table['com'][sLay] = Sch_Table['com']['ATUS104']
Sch_Table['mou'][sLay] = Sch_Table['mou']['ATUS104']
Sch_Table['joy'][sLay] = Sch_Table['joy']['ATUS104']
Sch_Table['add'][sLay] = Sch_Table['add']['ATUS104']
