sLay = 'ATUS104'
Sch_Table['gam'][sLay] = 'Winamp'
Sch_Table['aut'][sLay] = ''
Sch_Table['key'][sLay] =
[
,
['blu','Preamp +',,,,,,],
['blu','EQ Band +',,,,,,],
['blu','EQ Band +',,,,,,],
['blu','EQ Band +',,,'Track Info',,,],
['blu','EQ Band +',,,,,,],
['blu','EQ Band +',,,,,,],
['blu','EQ Band +',,,,,,],
['blu','EQ Band +',,,,,,],
['blu','EQ Band +',,,,,,],
['blu','EQ Band +',,,,,,],
['blu','EQ Band +',,,,,,],
,
,
,
['blu','Preamp -',,'Cycle\nWindows',,,,],
['blu','EQ -',,,,,,],
['blu','EQ -',,'Window-\nshade','Main\nWindow',,,],
['blu','EQ -',,'Easy\nMove','Edit\nPlaylist',,,],
['grn','Toggle\nRepeat /\nEQ -',,'Reverse\nPlaylist',,,,],
['blu','EQ -',,'Time\nDisplay','Mini-\nbrowser',,,],
['blu','EQ -',,,,,,],
['blu','EQ -',,,,,,],
['blu','EQ -',,,,,,],
['blu','EQ -',,'Open\nPlaylist','Viz\nOptions',,,],
['blu','EQ -',,'Prefer-\nences',,,,],
,
,
,
,
['blu','Auto EQ',,'Always\non Top',,,,],
['grn','Toggle\nShuffle /\nEQ Presets',,'Save\nPlaylist','Select\nSkin',,,],
,
[,,,'Double\nSize','Menu',,,],
[,,,,'Equalizer',,,],
,
['grn','Jump\nto File',,'Jump\nTime',,,,],
[,,,'Viz\nPrefs','Viz\nConfig',,,],
['grn','Add/Load\nFile','Add/Load\nFolder','Add/Load\nURL',,,,],
,
,
,
['red','Play Selected Track',,,,,,],
,
,
['grn','Previous\nTrack',,,,,,],
['grn','Start\nPlaying',,,,,,],
['grn','Pause\nPlaying',,,,,,],
['grn','Stop\nPlaying','Fade\nStop','Stop at\nEnd',,,,],
['grn','Next\nTrack',,,,,,],
[,,,'New\nPlaylist',,,,],
['blu','Toggle EQ',,,'Minimize',,,],
,
,
,
,
,
,
,
,
,
['grn','Add/Load\nFolder',,,,,,],
['red','Delete\nTrack',,'Crop\nList','Clear\nDead',,,],
['grn','Back 5\nSeconds',,,,,,],
['red','Go to Top\nof List',,,,,,],
['red','Go to End\nof List',,,,,,],
['grn','Volume +',,,'Move +',,,],
['grn','Volume -',,,'Move -',,,],
['red','Page\nDown',,,,,,],
['red','Page\nDown',,,,,,],
['grn','Ahead 5\nSeconds',,,,,,],
,
['grn','Back 5\nSeconds',,,,,,],
['grn','Previous\nTrack',,,,,,],
['grn','Back 10\nTracks',,,,,,],
,
['grn','Volume +',,,,,,],
['grn','Start\nPlaying',,,,,,],
['grn','Volume -',,,,,,],
['grn','Add/Load File',,'Add/Load URL',,,,],
,
['grn','Ahead 5\nSeconds',,,,,,],
['grn','Next\nTrack',,,,,,],
['grn','Ahead 10\nTracks',,,,,,],
['grn','Jump\nto File',,,,,,],
,
,
,
,
['mag','About /\nHelp',,,,,,],
,
,
[,,,'Close\nWindow','Exit\nWinamp',,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,

]
Sch_Table['leg'][sLay] =
[
['grn','Playback'],
['red','Playlist'],
['blu','Equalizer'],
['mag','Winamp']
]
Sch_Table['com'][sLay] =
[
'Ctrl + Alt + A = Toggle Always-On-Top for playlist editor.',
'Ctrl + Shift + K = Start/Stop current visualization plug-in.',
'Ctrl + Alt + N = Spawn new Winamp instance.',
'Ctrl + Shift + Delete = Clear playlist.',
'Ctrl + Shift + 1 = Sort playlist by title.',
'Ctrl + Shift + 2 = Sort playlist by file name.',
'Ctrl + Shift + 3 = Sort playlist by file path and name.',
'Ctrl + Shift + R = Randomize playlist.'
]
Sch_Table['mou'][sLay] = []
Sch_Table['joy'][sLay] = []
Sch_Table['add'][sLay] = []
