sLay = 'ATUS104'
Sch_Table['gam'][sLay] = 'Freedom Force'
Sch_Table['aut'][sLay] = ''
Sch_Table['key'][sLay] =
[
,
,
['yel','Select\nCharacter','Add to\nSelection',,,,,],
['yel','Select\nCharacter','Add to\nSelection',,,,,],
['yel','Select\nCharacter','Add to\nSelection',,,,,],
['yel','Select\nCharacter','Add to\nSelection',,,,,],
['yel','Select\nSquad',,,,,,],
,
,
,
,
,
['mag','Game\nSpeed -',,,,,,],
['mag','Game\nSpeed +',,,,,,],
,
['mag','Toggle\nBuilding Fade',,,,,,],
,
['blu','Camera\nUp',,,,,,],
,
,
['mag','Multiplayer\nChat',,,,,,],
,
,
,
['mag','Mission\nObjectives',,,,,,],
,
['red','Previous\nPower',,,,,,],
['red','Next\nPower',,,,,,],
,
,
['blu','Camera\nLeft',,,,,,],
['blu','Camera\nDown',,,,,,],
['blu','Camera\nRight',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
['blu','Cinematic\nCamera',,,,,,],
['red','Force\nOverpower',,,,,,],
['red','Force\nRepeat',,,,,,],
,
,
,
,
,
,
,
,
['red','Force Attack',,,,,,],
['blu','Zoom/Rotate\nCamera',,,,,,],
['mag','Pause\nGame',,,,,,],
,
,
,
,
['blu','Camera\nLeft',,,,,,],
,
,
['blu','Camera\nUp',,,,,,],
['blu','Camera\nDown',,,,,,],
,
,
['blu','Camera\nRight',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
['mag','Main\nMenu',,,,,,],
['red','Default\nPower',,,,,,],
['red','Default\nPower',,,,,,],
['red','Default\nPower',,,,,,],
['red','Default\nPower',,,,,,],
['red','Default\nPower',,,,,,],
['red','Default\nPower',,,,,,],
['red','Default\nPower',,,,,,],
['red','Default\nPower',,,,,,],
['red','Default\nPower',,,,,,],
['red','Default\nPower',,,,,,],
['mag','Quick\nSave',,,,,,],
['mag','Quick\nLoad',,,,,,],
,
,
['mag','Pause\nGame',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,

]
Sch_Table['leg'][sLay] = []
Sch_Table['com'][sLay] = []
Sch_Table['mou'][sLay] = []
Sch_Table['joy'][sLay] = []
Sch_Table['add'][sLay] = []
sLay = 'ATUS104DVO'
Sch_Table['gam'][sLay] = Sch_Table['gam']['ATUS104']
Sch_Table['aut'][sLay] = Sch_Table['aut']['ATUS104']
Sch_Table['key'][sLay] = Sch_Table['key']['ATUS104']
Sch_Table['leg'][sLay] = Sch_Table['leg']['ATUS104']
Sch_Table['com'][sLay] = Sch_Table['com']['ATUS104']
Sch_Table['mou'][sLay] = Sch_Table['mou']['ATUS104']
Sch_Table['joy'][sLay] = Sch_Table['joy']['ATUS104']
Sch_Table['add'][sLay] = Sch_Table['add']['ATUS104']
