sLay = 'ATUS104'
Sch_Table['gam'][sLay] = 'Vega Strike'
Sch_Table['aut'][sLay] = 'Agnes Beste'
Sch_Table['key'][sLay] =
[
,
['grn','Shelton\nSlide',,,,,,],
['blu','Toggle\nCockpit','Self\nDestruct',,,,,],
['blu','Look\nLeft',,,,,,],
['blu','Look\nRight',,,,,,],
['blu','Look\nBack',,,,,,],
['blu','Chase\nView',,,,,,],
['blu','Panning\nView',,,,,,],
['blu','Target\nView',,,,,,],
['blu','Target\nPanning\nView','Roll\nRight',,,,,],
['mag','TC -',,,,,,],
['mag','TC +',,,'Clear\nDock',,,],
['grn','Decrease\nVelocity',,,,,,],
['grn','Increase\nVelocity',,,,,,],
['grn','Relative Stop',,,,,,],
['grn','Afterburner',,,,,,],
['blu','Pan Down',,,,,,],
['red','Next\nSecondary\nWeapon','Prev',,,,,],
['red','ECM',,,'Eject',,,],
['yel','Next\nNear Target\n(Hostile)','Toughest',,,,,],
['yel','Next\nAll Target','Prev',,,,,],
['grn','Switch\nCombat\nMode',,,,,,],
['yel','Next\nManmade\nTarget','Prev',,,,,],
['mag','Screenshot',,,,,,],
['red','Turret AI\nOn','Auto',,'Off',,,],
['yel','Target in\nBoresight','Turret\nTarget',,,,,],
['yel','Change\nShip',,,,,,],
['yel','Text\nMessage',,,,,,],
['grn','Max Velocity','Pause\nGame',,,,,],
,
['grn','Autopilot','SPEC',,,,,],
['blu','Pan Left','Skip Song',,,,,],
['grn','Docking\nManeuver','Attack\nTarget',,,,,],
['blu','Pan Right','Form Up',,,,,],
['red','Next\nPrimary\nWeapon','Prev',,,,,],
['yel','Next\nHostile\nTarget','Prev',,'Help\nMe',,,],
['grn','Jump Drive',,,,,,],
['yel','Next Near\nTarget\n(Friend)','Base','Plant','Jump',,,],
['yel','Lock on\nTarget',,,,,,],
['mag','Respawn',,,,,,],
,
,
['red','Fire Secondary',,,,,,],
,
,
['blu','Pan Up','Jettison\nCargo',,,,,],
,
['red','Cloak',,,,,,],
['mag','Cycle\nRight VDU',,'Shader\nNew',,,,],
['yel','Next\nSubunit','Break\nForm',,,,,],
['yel','Next\nNeutral\nTarget','Prev',,'Mission\nN/P',,,],
['mag','Cycle\nLeft VDU','Toggle\nMap',,,,,],
['grn','Thrust\nUp','Left',,,,,],
['grn','Thrust\nDown','Right',,,,,],
,
,
,
,
['red','Fire Primary',,,,,,],
,
,
['grn','Roll\nLeft',,,,,,],
['grn','Roll\nRight',,,,,,],
['grn','Nose\nLeft',,,,,,],
['grn','Match\nVelocity',,,,,,],
['grn','Zero\nVelocity',,,,,,],
['grn','Nose\nDown',,,,,,],
['grn','Nose\nUp',,,,,,],
['mag','Scroll\nText Up',,,,,,],
['mag','Scroll\nText Down',,,,,,],
['grn','Nose\nRight',,,,,,],
,
['grn','Match\nVelocity',,,,,,],
['grn','Nose\nLeft',,,,,,],
['grn','Zero\nVelocity',,,,,,],
['grn','Roll\nLeft',,,,,,],
['grn','Nose\nDown',,,,,,],
,
['grn','Nose\nUp',,,,,,],
,
['grn','Roll\nRight',,,,,,],
['mag','Scroll\nText Up',,,,,,],
['grn','Nose\nRight',,,,,,],
['mag','Scroll\nText Down',,,,,,],
,
['grn','Decrease\nVelocity',,,,,,],
['grn','Increase\nVelocity',,,,,,],
['red','Fire\nSecondary',,,,,,],
['mag','Quit',,,,,,],
['cyn','Comm\nKey 1',,,,,,],
['cyn','Comm\nKey 2',,,,,,],
['cyn','Comm\nKey 3',,,,,,],
['cyn','Comm\nKey 4',,,,,,],
['cyn','Comm\nKey 5',,,,,,],
['cyn','Comm\nKey 6',,,,,,],
['cyn','Comm\nKey 7',,,,,,],
['cyn','Comm\nKey 8',,,,,,],
['mag','Volume -',,,,,,],
['mag','Volume +',,,,,,],
['blu','Music\nVolume -',,,,,,],
['blu','Music\nVolume +',,,,,,],
,
,
['mag','Pause\nGame',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,

]
Sch_Table['leg'][sLay] =
[
['red','Combat'],
['yel','Targeting'],
['grn','Navigation'],
['cyn','Communication'],
['blu','Camera'],
['mag','Game Controls']
]
Sch_Table['com'][sLay] = []
Sch_Table['mou'][sLay] = []
Sch_Table['joy'][sLay] = []
Sch_Table['add'][sLay] = []


sLay = 'ATDE105'
Sch_Table['gam'][sLay] = 'Vega Strike'
Sch_Table['aut'][sLay] = 'Agnes Beste'
Sch_Table['key'][sLay] =
[       
['grn','"Shelton\nSlide"\n-Man\u00f6ver',,,,,,],
['cyn','Ziel 1:\nSprechen','Selbst-\nmord','Fort-\nsetzen','Speichern',,,],
['cyn','Ziel 2:\nSprechen',,'Fort-\nsetzen','Spei-\nchern',,,],
['cyn','Ziel 3:\nSprechen',,'Fort-\nsetzen','Spei-\nchern',,,],
['cyn','Ziel 4:\nSprechen',,'Fort-\nsetzen','Spei-\nchern',,,],
['cyn','Ziel 5:\nSprechen',,'Fort-\nsetzen','Spei-\nchern',,,],
['cyn','Ziel 6:\nSprechen',,'Fort-\nsetzen','Spei-\nchern',,,],
['cyn','Ziel 7:\nSprechen',,'Fort-\nsetzen','Spei-\nchern',,,],
['cyn','Ziel 8:\nSprechen',,'Fort-\nsetzen','Spei-\nchern',,,],
['cyn','Ziel 9:\nSprechen',,'Fort-\nsetzen','Spei-\nchern',,,],
['cyn','Erbitte\nLande-\nerlaubnis',,,,,,],
['grn','Bremsen',,,,,,],
['grn','Beschleu-\nnigen',,,,,,],
['grn','Stoppen',,,,,,],
['grn','Nachbrenner',,,,,,],
,
['red','W\u00e4hle\nSekund\u00e4r-\nwaffe',,,,,,],
['red','ECM\nan/ab','Erlasse\nSchiff',,,,,],
,
['yel','Alle Ziele','R\u00fcckw.',,,,,],
['red','Kampf-\nmodus',,,,,,],
['yel','Alles auﬂer\nPlaneten','R\u00fcckw.',,,,,],
['mag','Screenshot',,,,,,],
['yel','Turm-KI\nan/ab',,,,,,],
['yel','Ziel unter\nFaden-\nkreuz',,,,,,],
,
['yel','Turm-\nkontrolle','W\u00e4hle\nZiel f\u00fcr\nT\u00fcrme',,,,,],
,
,
['grn','"SPEC Dr."\nan','Ab',,,,,],
[,,'N\u00e4chster\nSong\nTitel',,,,,],
['grn','Andocken','Alle mein\nZiel an-\ngreifen',,,,,],
[,,'Forma-\ntionsflug ',,,,,],
['red','W\u00e4hle\nPrim\u00e4r-\nwaffe',,,,,,],
['yel','Feind-\nliche\nZiele','R\u00fcckw.',,'Hilfe',,,],
['grn','"Jump Dr."\nan/ab',,,,,,],
,
['yel','Visiere\nan Ziel',,,,,,],
['mag','Schiff\naufer-\nstehen',,,,,,],
,
['grn','Volle\nGeschw.','Spiel\npausen',,,,,],
['red','Feuer\nSekund\u00e4r-\nwaffe',,,,,,],
,
['mag','Musik -','Musik +',,,,,],
['red','Tarn-\nschild','Kargo\naus-\nwerfen',,,,,],
,
,
['mag','Rechte\nVDU',,,,,,],
['yel','Teil des\nSchiffs','Formation\naufl\u00f6sen',,,,,],
['yel','Wichtige /\nNeutrale\nZiele','R\u00fcckw.',,,,,],
['mag','Linke\nVDU','Miss/Nav\nComputer',,,,,],
['mag','Ger\u00e4u-\nsche -','Musik -',,,,,],
['mag','Ger\u00e4u-\nsche +','Musik +',,,,,],
,
,
,
,
['red','Feuer Prim\u00e4rwaffe',,,,,,],
,
,
['grn','Links\nRollen',,,,,,],
['grn','Rechts\nRollen',,,,,,],
['grn','Links',,,,,,],
['grn','Geschw.\ndem Ziel\nanpassen',,,,,,],
['grn','Null\nGeschw.',,,,,,],
['grn','Hoch',,,,,,],
['grn','Runter',,,,,,],
['mag','Text nach\noben',,,,,,],
['mag','Text nach\nunten',,,,,,],
['grn','Rechts',,,,,,],
,
['grn','Geschw.\ndem Ziel\nanpassen',,,,,,],
['grn','Links',,,,,,],
['grn','Null\nGeschw.',,,,,,],
['grn','Links\nRollen',,,,,,],
['grn','Hoch',,,,,,],
,
['grn','Runter',,,,,,],
,
['grn','Rechts\nRollen',,,,,,],
['mag','Text nach\noben',,,,,,],
['grn','Rechts',,,,,,],
['mag','Text nach\nunten',,,,,,],
,
['grn','Bremsen',,,,,,],
['grn','Beschleu-\nnigen',,,,,,],
['red','Feuer\nSekund\u00e4r-\nwaffe',,,,,,],
['mag','Spiel\nbeenden',,,,,,],
['blu','Normales\nCockpit',,,,,,],
['blu','Nach links\nschauen',,,,,,],
['blu','Nach rechts\nschauen',,,,,,],
['blu','Nach hinten\nschauen',,,,,,],
['blu','Verfolg-\nungs-\nkamera',,,,,,],
['blu','Freie\nKamera',,,,,,],
['blu','Ziel-\nkamera',,,,,,],
['blu','Ziel-Ego-\nKamera',,,,,,],
['mag','Zeitver-\nzerrung +',,,,,,],
['mag','Zeitver-\nzerrung -',,,,,,],
['blu','Kamera\nein-\nzoomen',,,,,,],
['blu','Kamera\naus-\nzoomen',,,,,,],
,
,
['mag','Spiel\npausen',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,

]
Sch_Table['leg'][sLay] =
[
['red','Kampf'],
['yel','Zielerfassung'],
['grn','Bewegung'],
['cyn','Kommunikation'],
['blu','Kamera'],
['mag','System Kontrolle']
]
Sch_Table['com'][sLay] = []
Sch_Table['mou'][sLay] = []
Sch_Table['joy'][sLay] = []
Sch_Table['add'][sLay] = []
sLay = 'ATUS104DVO'
Sch_Table['gam'][sLay] = Sch_Table['gam']['ATUS104']
Sch_Table['aut'][sLay] = Sch_Table['aut']['ATUS104']
Sch_Table['key'][sLay] = Sch_Table['key']['ATUS104']
Sch_Table['leg'][sLay] = Sch_Table['leg']['ATUS104']
Sch_Table['com'][sLay] = Sch_Table['com']['ATUS104']
Sch_Table['mou'][sLay] = Sch_Table['mou']['ATUS104']
Sch_Table['joy'][sLay] = Sch_Table['joy']['ATUS104']
Sch_Table['add'][sLay] = Sch_Table['add']['ATUS104']
