sLay = 'ATUS104'
Sch_Table['gam'][sLay] = 'UFO: Alien Invasion (Development)'
Sch_Table['aut'][sLay] = ''
Sch_Table['key'][sLay] =
[
,
['mag','Game\nConsole',,,,,,],
['yel','Select\nSoldier',,,,,,],
['yel','Select\nSoldier',,,,,,],
['yel','Select\nSoldier',,,,,,],
['yel','Select\nSoldier',,,,,,],
['yel','Select\nSoldier',,,,,,],
['yel','Select\nSoldier',,,,,,],
['yel','Select\nSoldier',,,,,,],
['yel','Select\nSoldier',,,,,,],
,
,
['mag','Geoscape\nSpeed -',,,,,,],
['mag','Geoscape\nSpeed +',,,,,,],
['mag','Geoscape\nPause',,,,,,],
['yel','Next Soldier',,,,,,],
['grn','Turn to\nPointer',,,,,,],
['blu','Terrain\nUp',,,,,,],
['red','End Turn',,,,,,],
['blu','Rotate\nUp',,,,,,],
['mag','Draw Line\nof Sight',,,,,,],
,
,
['red','Inventory',,,,,,],
,
,
,
,
,
,
['blu','Rotate\nLeft',,,,,,],
['blu','Terrain\nDown',,,,,,],
['blu','Rotate\nRight',,,,,,],
['blu','Rotate\nDown',,,,,,],
,
['mag','Toggle\nHUD',,,,,,],
,
['cyn','Chat\nAll',,,,,,],
['cyn','Chat\nTeam',,,,,,],
['cyn','Toggle\nChat Bar',,,,,,],
,
,
['red','Confirm Action',,,,,,],
['red','Align Firing Angle',,,,,,],
,
,
['red','Toggle\nReaction\nFire',,,,,,],
['grn','Crouch /\nStand',,,,,,],
['blu','First/Third\nPerson\nView',,,,,,],
,
['mag','Geoscape\nSpeed -',,,,,,],
['mag','Geoscape\nSpeed +',,,,,,],
,
,
,
['red','Align Firing Angle',,,,,,],
['grn','Turn to Pointer',,,,,,],
,
['yel','[Tactical] Next Alien\n[Geoscape] Center on Object',,,,,,],
,
['grn','Turn to Pointer',,,,,,],
['blu','Rotate\nUp',,,,,,],
['blu','Rotate\nDown',,,,,,],
['blu','Rotate\nLeft',,,,,,],
,
,
['blu','Terrain\nUp',,,,,,],
['blu','Terrain\nDown',,,,,,],
['blu','Zoom\nIn',,,,,,],
['blu','Zoom\nOut',,,,,,],
['blu','Rotate\nRight',,,,,,],
,
,
['blu','Pan\nLeft',,,,,,],
,
,
['blu','Pan\nForward',,,,,,],
,
['blu','Pan\nBackward',,,,,,],
,
,
,
['blu','Pan\nRight',,,,,,],
,
,
,
,
,
,
['mag','Quick\nSave',,,,,,],
['mag','Quick\nLoad',,,,,,],
,
,
,
,
,
,
,
['mag','Push Menu\nin Stack',,,,,,],
['mag','Toggle\nHUD',,,,,,],
['mag','Screenshot',,,,,,],
,
,
['mag','Pause\nGame',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,

]
Sch_Table['leg'][sLay] =
[
['red','Actions'],
['grn','Movement'],
['yel','Selection'],
['blu','Camera'],
['cyn','Chat'],
['mag','Game Controls']
]
Sch_Table['com'][sLay] =
[
'CTRL + Left Click = Turn Toward Pointer'
]
Sch_Table['mou'][sLay] =
[
'Left Click = Select Soldier / Walk Toward Pointer / Attack',
'Right Click = Turn Toward Pointer',
'Middle Click = Walk Toward Pointer / Cancel Attack',
'Mouse Wheel = Zoom In/Out'
]
Sch_Table['joy'][sLay] = []
Sch_Table['add'][sLay] = []
