sLay = 'ATUS104'
Sch_Table['gam'][sLay] = 'Gothic 2'
Sch_Table['aut'][sLay] = ''
Sch_Table['key'][sLay] =
[
,
,
['red','Melee\nWeapon',,,,,,],
['red','Ranged\nWeapon',,,,,,],
['red','Last Spell',,,,,,],
['red','Spell 1',,,,,,],
['red','Spell 2',,,,,,],
['red','Spell 3',,,,,,],
['red','Spell 4',,,,,,],
['red','Spell 5',,,,,,],
['red','Spell 6',,,,,,],
['red','Spell 7',,,,,,],
,
,
,
['mag','Inventory',,,,,,],
['grn','Turn Left',,,,,,],
['grn','Move\nForward',,,,,,],
['grn','Turn Right',,,,,,],
,
,
,
,
,
,
,
,
,
,
['grn','Toggle Run/Walk',,,,,,],
['grn','Strafe Left',,,,,,],
['grn','Move\nBackward',,,,,,],
['grn','Strafe Right',,,,,,],
,
,
,
,
,
['mag','Log Book',,,,,,],
,
,
,
,
['grn','Switch Run/Walk',,,,,,],
,
,
,
['mag','Character\nScreen',,,,,,],
,
,
['mag','Log Book',,,,,,],
['mag','Map',,,,,,],
,
,
,
['grn','Switch Run/Walk',,,,,,],
['red','Interact / Focus',,,,,,],
['grn','Jump / Dive',,,,,,],
['red','Draw Last Weapon',,,,,,],
['grn','Jump / Dive',,,,,,],
['red','Interact / Focus',,,,,,],
,
['grn','Strafe\nLeft',,,,,,],
['grn','Turn Left',,'Attack\nLeft',,,,],
,
,
['grn','Move\nForward',,'Attack\nForward',,,,],
['grn','Move\nBackward',,,,,,],
,
['grn','Strafe\nRight',,,,,,],
['grn','Turn Right',,'Attack\nRight',,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
['mag','Main Menu\n/ Cancel',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,

]
Sch_Table['leg'][sLay] =
[
['red','Weapons/Actions'],
['grn','Movement'],
['mag','Game Controls']
]
Sch_Table['com'][sLay] = []
Sch_Table['mou'][sLay] = []
Sch_Table['joy'][sLay] = []
Sch_Table['add'][sLay] = []
sLay = 'ATUS104DVO'
Sch_Table['gam'][sLay] = Sch_Table['gam']['ATUS104']
Sch_Table['aut'][sLay] = Sch_Table['aut']['ATUS104']
Sch_Table['key'][sLay] = Sch_Table['key']['ATUS104']
Sch_Table['leg'][sLay] = Sch_Table['leg']['ATUS104']
Sch_Table['com'][sLay] = Sch_Table['com']['ATUS104']
Sch_Table['mou'][sLay] = Sch_Table['mou']['ATUS104']
Sch_Table['joy'][sLay] = Sch_Table['joy']['ATUS104']
Sch_Table['add'][sLay] = Sch_Table['add']['ATUS104']
