sLay = 'ATUS104'
Sch_Table['gam'][sLay] = 'Allegience'
Sch_Table['aut'][sLay] = ''
Sch_Table['key'][sLay] =
[
,
['mag','Chat\nMenu',,,,,,],
['red','Weapon 1',,'Swap',,,,],
['red','Weapon 2',,'Swap',,,,],
['red','Weapon 3',,'Swap',,,,],
['red','Weapon 4',,'Swap',,,,],
['red','Fire Missile',,'Swap',,,,],
['red','Chaff',,'Swap',,,,],
['red','Shield',,'Swap',,,,],
['red','Cloak',,'Swap',,,,],
['grn','Booster',,'Swap',,,,],
['red','Mine',,'Swap',,,,],
['grn','Throttle -',,,,,,],
['grn','Throttle +',,,,,,],
['grn','Zero Throttle',,,,,,],
['grn','Booster',,,,,,],
['yel','Next\nEnemy\nBase','Prev','Near',,,,],
['red','Next\nWeapon','Prev','Group Fire',,,,],
['yel','Next\nEnemy','Prev','Near',,,,],
['grn','Ripcord',,'Reload',,,,],
['yel','Next\nTarget','Prev','Near',,,,],
['cyn','Vote\nYes',,,,,,],
[,,'Promote\nTurret 2','Swap',,,,],
['yel','Cycle\nRadar\nModes','Promote\nTurret 3','Swap',,,,],
[,,'Promote\nTurret 4','Swap',,,,],
['grn','Autopilot',,,,,,],
['grn','1/3\nThrottle',,,,,,],
['grn','2/3\nThrottle',,,,,,],
['grn','Max Throttle',,,,,,],
,
['red','Drop\nChaff',,,,,,],
[,,,'Drop\nCargo',,,,],
['red','Drop\nMine',,,,,,],
['yel','Next\nFriendly','Prev','Near',,,,],
['mag','Switch to\nGamestate',,'Toggle\nGrid',,,,],
['yel','Next\nHostile',,,,,,],
['yel','Next\nLifepod','Prev','Near',,,,],
['red','Cloak',,,,,,],
['grn','Lock\nVector',,,,,,],
,
,
,
['cyn','Chat',,,,,,],
,
,
['yel','Target\nSelf',,,,,,],
['yel','Target\nNothing',,,,,,],
['yel','Target\nCenter','Target\nCommand','View',,,,],
[,,'Promote\nTurret 1','Swap',,,,],
,
['cyn','Vote No /\nNext Cargo',,,,,,],
['grn','Match\nSpeed',,,,,,],
,
,
,
,
,
,
['red','Fire Weapon',,'Fire Missile',,,,],
,
,
['cyn','Execute\nCommand','Accept\nCommand',,,,,],
['cyn','Reject\nCommand','Clear\nCommand',,,,,],
['grn','Yaw\nLeft','Roll\nLeft',,,,,],
['yel','Target\nCommand',,,,,,],
['mag','Finish\nGoal',,,,,,],
['grn','Pitch\nUp',,,,,,],
['grn','Pitch\nLeft',,,,,,],
['mag','Scroll\nUp',,,,,,],
['mag','Scroll\nDown',,,,,,],
['grn','Yaw\nRight','Roll\nRight',,,,,],
,
['grn','Thrust\nDown',,,,,,],
['grn','Thrust\nLeft',,,,,,],
['yel','Target\nCenter',,,,,,],
,
['grn','Thrust\nForward',,,,,,],
['grn','Thrust\nBack',,,,,,],
,
['mag','Mouse Control',,,,,,],
,
['grn','Thrust\nUp',,,,,,],
['grn','Thrust\nRight',,,,,,],
['grn','Lock\nVector',,,,,,],
,
['blu','Zoom Out',,,,,,],
['blu','Zoom In',,,,,,],
,
,
,
['mag','Switch to\nCombat',,,,,,],
['mag','Switch to\nCommand',,,,,,],
['mag','Switch to\nInventory',,,,,,],
['mag','Switch to\nInvest',,,,,,],
['mag','Switch to\nTeam','Mini\nTeam',,,,,],
['mag','Switch to\nNav',,,,,,],
['mag','Switch to\nTeleport',,,,,,],
['blu','View\nMissile',,,,,,],
['blu','View\nTarget',,,,,,],
['blu','View\nChase',,,,,,],
['blu','View\nExternal\nTarget','View\nOrbit',,,,,],
,
,
[,,,'Pause',,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,

]
Sch_Table['leg'][sLay] =
[
['red','Combat'],
['yel','Targeting'],
['grn','Navigation'],
['cyn','Communication'],
['blu','Camera'],
['mag','Game Controls']
]
Sch_Table['com'][sLay] =
[
'Eject From Turret = Shift + Ctrl + D (three times)'
]
Sch_Table['mou'][sLay] = []
Sch_Table['joy'][sLay] = []
Sch_Table['add'][sLay] = []
