sLay = 'ATUS104'
Sch_Table['gam'][sLay] = 'Silent Storm'
Sch_Table['aut'][sLay] = ''
Sch_Table['key'][sLay] =
[
,
,
['yel','Select\nUnit',,'Add',,,,],
['yel','Select\nUnit',,'Add',,,,],
['yel','Select\nUnit',,'Add',,,,],
['yel','Select\nUnit',,'Add',,,,],
['yel','Select\nUnit',,'Add',,,,],
['yel','Select\nUnit',,'Add',,,,],
['yel','Select\nUnit',,'Add',,,,],
,
,
,
,
['yel','Select\nAll Units',,,,,,],
,
['yel','Select\nNext Unit',,,,,,],
['red','Snap\nShot',,'Quit\nGame',,,,],
['red','Aimed\nShot',,,,,,],
['red','Careful\nShot',,,,,,],
['red','Reload',,,,,,],
['red','Sniper\nShot',,,,,,],
,
['mag','Character\nWindow',,,,,,],
['mag','Item\nWindow',,,,,,],
['mag','Objective\nWindow',,,,,,],
,
['red','Previous\nFiring Mode',,,,,,],
['red','Next\nFiring Mode',,,,,,],
,
,
['red','Attack',,,,,,],
['red','Stop',,,,,,],
['red','Keep\nStance',,,,,,],
['red','Short\nBurst',,,,,,],
['red','Long\nBurst',,,,,,],
['red','Hide',,,,,,],
['mag','Journal',,,,,,],
,
['red','Look',,,,,,],
,
,
,
['red','End Turn',,,,,,],
,
,
['red','Run',,,,,,],
['red','Walk',,,,,,],
['red','Crouch',,,,,,],
['red','Prone',,,,,,],
,
,
['red','Move',,,,,,],
,
,
,
,
,
['mag','Item Names',,,,,,],
['mag','Skip Dialogue',,,,,,],
,
,
,
,
['blu','Pan Left',,'Turn\nLeft',,,,],
,
,
['blu','Pan\nForward',,'Turn\nUp',,,,],
['blu','Pan\nBackward',,'Turn\nDown',,,,],
['blu','Zoom In',,,,,,],
['blu','Zoom Out',,,,,,],
['blu','Pan Right',,'Turn\nRight',,,,],
,
,
['red','Aim at\nLeft Arm',,,,,,],
['red','Aim at\nLeft Leg',,,,,,],
,
['red','Aim at\nHead',,,,,,],
['red','Aim at\nBody',,,,,,],
,
,
,
,
['red','Aim at\nRight Arm',,,,,,],
['red','Aim at\nRight Leg',,,,,,],
,
['blu','Lower\nLevel',,,,,,],
['blu','Upper\nLevel',,,,,,],
,
['mag','End\nDialogue',,,,,,],
,
,
,
[,,,,'Exit to\nWindows',,,],
['mag','Quick\nSave',,,,,,],
['mag','Save\nMenu',,,,,,],
['mag','Load\nMenu',,,,,,],
['mag','Quick\nLoad',,,,,,],
,
['mag','Main\nMenu',,,,,,],
,
,
['mag','Screenshot',,,,,,],
,
['mag','Pause\nGame',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,

]
Sch_Table['leg'][sLay] =
[
['red','Action'],
['yel','Selection'],
['blu','Camera'],
['mag','Game Controls']
]
Sch_Table['com'][sLay] = []
Sch_Table['mou'][sLay] = []
Sch_Table['joy'][sLay] = []
Sch_Table['add'][sLay] = []
sLay = 'ATUS104DVO'
Sch_Table['gam'][sLay] = Sch_Table['gam']['ATUS104']
Sch_Table['aut'][sLay] = Sch_Table['aut']['ATUS104']
Sch_Table['key'][sLay] = Sch_Table['key']['ATUS104']
Sch_Table['leg'][sLay] = Sch_Table['leg']['ATUS104']
Sch_Table['com'][sLay] = Sch_Table['com']['ATUS104']
Sch_Table['mou'][sLay] = Sch_Table['mou']['ATUS104']
Sch_Table['joy'][sLay] = Sch_Table['joy']['ATUS104']
Sch_Table['add'][sLay] = Sch_Table['add']['ATUS104']
