sLay = 'ATUS104'
Sch_Table['gam'][sLay] = 'SimCity 3000 Unlimited'
Sch_Table['aut'][sLay] = ''
Sch_Table['key'][sLay] =
[
,
,
['blu','Zoom\nLevel 1',,,,,,],
['blu','Zoom\nLevel 2',,,,,,],
['blu','Zoom\nLevel 3',,,,,,],
['blu','Zoom\nLevel 4',,,,,,],
['blu','Zoom\nLevel 5',,,,,,],
,
,
,
,
,
['blu','Zoom Out',,,,,,],
['blu','Zoom In',,,,,,],
,
,
['red','Light\nResidential',,'Quit',,,,],
['red','Medium\nResidential',,'Neighbors',,,,],
['red','Dense\nResidential',,'Power Plants',,,,],
['red','Lay\nRoads','Highway','Rewards','Bus\nStop',,,],
['red','Lay Rail','Subway','Real Terrain','Train Station',,,],
['red','Landfill',,'Waste Mgmt',,,,],
['red','Plant\nTrees','Lay Water',,,,,],
['red','Lay\nPipes',,'Water Mgmt',,,,],
[,,,'Ordinances',,,,],
['red','Build\nPolice\nStation','Build\nJail','Prefs',,,,],
,
,
,
,
['red','Light\nCommercial',,'Advisors',,,,],
['red','Medium\nCommercial',,'Save City',,,,],
['red','Dense\nCommercial',,'Landmarks',,,,],
['red','Build Fire\nStation',,'Starter Town',,,,],
['mag','Toggle\nGrid',,'City Layers',,,,],
['red','Build\nHospital',,,,,,],
['red','Build\nSmall Park','Large Park',,,,,],
['red','Build\nSchool','College',,,,,],
['red','Lay\nPower Lines',,'Load City',,,,],
,
,
,
,
,
,
['red','Light\nIndustrial',,,,,,],
['red','Medium\nResidential',,,,,,],
['red','Dense\nResidential','Get XYZ',,,,,],
['red','Clear\nZones',,,,,,],
['red','Demolish\nTool',,'Budget',,,,],
[,,,'New City',,,,],
[,,,'City Data',,,,],
['mag','Game\nSpeed -',,,,,,],
['mag','Game\nSpeed +',,,,,,],
['mag','Pause\nGame',,,,,,],
,
['red','(Hold)\nCancel Action',,,,,,],
['red','(Hold)\nDemolish',,,,,,],
['blu','Focus on Cursor',,,,,,],
['red','(Hold)\nDemolish',,,,,,],
['red','(Hold)\nCancel Action',,,,,,],
,
,
['blu','Scroll Left',,,,,,],
,
,
['blu','Scroll Up',,,,,,],
['blu','Scroll Down',,,,,,],
['blu','Rotate\nCounter-\nclockwise',,,,,,],
['blu','Rotate\nClockwise',,,,,,],
['blu','Scroll Right',,,,,,],
['mag','Toggle\nToolbar',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
['mag','Cancel /\nDefault\nTool',,,,,,],
['mag','Save As...',,,,,,],
['mag','Save City',,,,,,],
['mag','Load City',,,,,,],
['mag','Prefer-\nences',,,,,,],
['mag','New City',,,,,,],
['mag','Starter\nTown',,,,,,],
['mag','Real\nTerrain',,,,,,],
,
,
['mag','Quit Game',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,

]
Sch_Table['leg'][sLay] =
[
['red','Actions/Tools'],
['blu','Camera'],
['mag','Game Controls']
]
Sch_Table['com'][sLay] =
[
'CTRL + LMB = Query Tile',
'ALT + LMB = Demolish Tile',
'SHIFT + ALT + T = Build Subway Station',
'CTRL + SHIFT + A = View Snapshots',
'CTRL + SHIFT + S = Take Snapshot',
'CTRL + ALT + S = Save City As...',
'SHIFT on Mouse Up = Cancel Action'
]
Sch_Table['mou'][sLay] = []
Sch_Table['joy'][sLay] = []
Sch_Table['add'][sLay] = []
sLay = 'ATUS104DVO'
Sch_Table['gam'][sLay] = Sch_Table['gam']['ATUS104']
Sch_Table['aut'][sLay] = Sch_Table['aut']['ATUS104']
Sch_Table['key'][sLay] = Sch_Table['key']['ATUS104']
Sch_Table['leg'][sLay] = Sch_Table['leg']['ATUS104']
Sch_Table['com'][sLay] = Sch_Table['com']['ATUS104']
Sch_Table['mou'][sLay] = Sch_Table['mou']['ATUS104']
Sch_Table['joy'][sLay] = Sch_Table['joy']['ATUS104']
Sch_Table['add'][sLay] = Sch_Table['add']['ATUS104']
