sLay = 'ATUS104'
Sch_Table['gam'][sLay] = 'Battle for Wesnoth'
Sch_Table['aut'][sLay] = ''
Sch_Table['key'][sLay] =
[
,
,
['blu','Radius\nin 1 Turn',,,,,,],
['blu','Radius\nin 2 Turns',,,,,,],
['blu','Radius\nin 3 Turns',,,,,,],
['blu','Radius\nin 4 Turns',,,,,,],
['blu','Radius\nin 5 Turns',,,,,,],
['blu','Radius\nin 6 Turns',,,,,,],
['blu','Radius\nin 7 Turns',,,,,,],
,                      
,
['blu','Default\nZoom',,,,,,],
['blu','Zoom Out',,,,,,],
['blu','Zoom In',,,,,,],
,
,
[,,,'Quit\nGame',,,,],
,
,
['red','Redo\nMove',,'Recruit\nUnit','Recall\nUnit',,,],
['red','Finish\nMove',,,,,,],
,
['red','Undo\nMove',,,'Unit\nList',,,],
,
[,,,'Load\nGame',,,,],
[,,,'Prefer-\nences',,,,],
,
,
,
,
[,,,'Game\nSpeed',,,,],
['mag','Statistics','Upd Shroud','Save Game','Game Status',,,],
['mag','Describe\nUnit','Delay\nShroud',,,,,],
[,,,'Toggle\nFullscreen\n/ Window',,,,],
[,,,'Toggle\nGrid',,,,],
,
[,,,'Mission\nObjectives',,,,],
,
['blu','Focus on\nLeader',,,'Mark\nTerrain',,,],
[,,'Command\nConsole',,,,,],
,
,
,
,
,
,
,
[,,,'Clear All\nLabels','Chat Log',,,],
[,,,'Show\nActual\nEnemy\nMoves',,,,],
[,,,'Show\nEnemy\nMoves\nMinus Self',,,,],
['yel','Cycle\nUnits +','Cycle -','Rename\nUnit',,,,],
['cyn','Chat\nPlayer',,,'Chat\nTeam','Chat All',,],
,
,
['mag','Search\nby Name',,,,,,],
,
,
,
['red','Done With Current Unit','Hold Position','End Turn',,,,],
,
,
,
,
['blu','Scroll Left',,,,,,],
,
,
['blu','Scroll Up',,,,,,],
['blu','Scroll Down',,,,,,],
,
,
['blu','Scroll Right',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
['mag','Menu /\nCancel',,,,,,],
['mag','Help',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,

]
Sch_Table['leg'][sLay] =
[
['red','Commands/Actions'],
['yel','Selection'],
['blu','Camera'],
['cyn','Chat'],
['mag','Game Controls']
]
Sch_Table['com'][sLay] =
[
'CTRL + ALT + R = Repeat Last Recruit',
'CTRL + ALT + M = Mute Game Sounds'
]
Sch_Table['mou'][sLay] =
[
'LMB = Select/Move Unit',
'RMB = Main Menu / Cancel',
'MMB = Center on Pointer'
]
Sch_Table['joy'][sLay] = []
Sch_Table['add'][sLay] = []
sLay = 'ATUS104DVO'
Sch_Table['gam'][sLay] = Sch_Table['gam']['ATUS104']
Sch_Table['aut'][sLay] = Sch_Table['aut']['ATUS104']
Sch_Table['key'][sLay] = Sch_Table['key']['ATUS104']
Sch_Table['leg'][sLay] = Sch_Table['leg']['ATUS104']
Sch_Table['com'][sLay] = Sch_Table['com']['ATUS104']
Sch_Table['mou'][sLay] = Sch_Table['mou']['ATUS104']
Sch_Table['joy'][sLay] = Sch_Table['joy']['ATUS104']
Sch_Table['add'][sLay] = Sch_Table['add']['ATUS104']
