sLay = 'ATUS104'
Sch_Table['gam'][sLay] = 'Battlecruiser Millenium'
Sch_Table['aut'][sLay] = ''
Sch_Table['key'][sLay] =
[
,
['grn','After-\nburner',,,,,,],
['grn','Thrust\nLevel 1',,,,,,],
['grn','Thrust\nLevel 2',,,,,,],
['grn','Thrust\nLevel 3',,,,,,],
['grn','Thrust\nLevel 4',,,,,,],
['grn','Thrust\nLevel 5',,,,,,],
['grn','Thrust\nLevel 6',,,,,,],
['grn','Thrust\nLevel 7',,,,,,],
['grn','Thrust\nLevel 8',,,,,,],
['grn','Thrust\nLevel 9','Hyper-\ndrive',,,,,],
['grn','Zero\nThrust',,,,,,],
['grn','Decrease\nThrust',,,,,,],
['grn','Increase\nThrust',,,,,,],
['red','Cycle Missiles',,,,,,],
['grn','Retro-rockets',,,,,,],
[,,,,'Quit\nGame',,,],
['red','Weapon\nSystem','Select\nWeapon',,,,,],
['red','Jammer','Engine','Eject','Exit Craft',,,],
['yel','Radar\nMode','Reactor',,'ROSTER',,,],
['red','Tractor\nBeam',,'SOS Tow','TAC-\nTICAL',,,],
['yel','Owned\nMissile',,,,,,],
['yel','Enemy\nMissile',,,,,,],
,
['grn','Planetary\nEgress',,,'CONFIG',,,],
['yel','PTA',,'Pause\nGame','PER-\nSCAN',,,],
['red','Decrease\nShield','Shield\nOff',,,,,],
['red','Increase\nShield','Shield\nMax',,,,,],
,
['grn','VTOL/HTOL',,,,,,],
['grn','Autopilot','Autopilot\nMode',,,,,],
['yel','STT',,'Quick\nSave','TAC-\nOPS',,,],
['grn','Match\nSpeed',,,'Dock',,,],
['yel','Add to\nPath',,,,,,],
[,,,'Screen-\nshot',,,,],
['yel','TTD Mode','HUD\nColor',,,,,],
['yel','NID Mode','NID Off',,,,,],
['yel','TACSCAN\nMode','TACSCAN\nOff',,,,,],
['yel','CVD Mode','CVD Off',,'LOGISTIX',,,],
['red','Decrease\nGun','Decrease\nPTA',,,,,],
['red','Increase\nGun','Increase\nPTA',,,,,],
,
['red','Fire Gun',,,,,,],
,
,
['yel','Radar\nZoom In','Radar\nZoom\nOut',,,,,],
['yel','Clear\nTarget','Clear All\nTargets',,,,,],
['yel','Send\nMessage','Cloak',,'COMM-\nLINK',,,],
['yel','Video Link',,'Game\nInfo',,,,],
['yel','Attacker of\nTarget',,,,,,],
['yel','Closest\nAttacker',,,'MIS-\nCON',,,],
['yel','Closest\nEnemy','Radar\nMask',,'NAVI-\nTRON',,,],
['yel','Previous\nTarget','Previous\nType',,,,,],
['yel','Next\nTarget','Next\nType',,,,,],
['yel','Target in\nFront',,,,,,],
,
,
,
['red','Fire Missile',,,,,,],
,
,
['grn','Yaw Left',,,,,,],
['grn','Yaw Right',,,,,,],
['grn','Roll Left',,,,,,],
['blu','Zoom In\n(Fine)',,,,,,],
['blu','Zoom Out\n(Fine)',,,,,,],
['grn','Pitch Up',,,,,,],
['grn','Pitch Down',,,,,,],
['blu','Zoom In\n(Coarse)',,,,,,],
['blu','Zoom Out\n(Coarse)',,,,,,],
['grn','Roll Right',,,,,,],
,
['blu','Zoom In\n(Fine)',,,,,,],
['grn','Roll Left',,,,,,],
['blu','Zoom Out\n(Fine)',,,,,,],
,
['grn','Pitch Up',,,,,,],
['grn','Level\nWings',,,,,,],
['grn','Pitch Down',,,,,,],
['grn','Yaw Left',,,,,,],
,
['blu','Zoom In\n(Coarse)',,,,,,],
['grn','Roll Right',,,,,,],
['blu','Zoom Out\n(Coarse)',,,,,,],
['grn','Yaw Right',,,,,,],
,
,
['red','Fire Gun',,,,,,],
,
['blu','Forward\nView',,,,,,],
['blu','Left View',,,,,,],
['blu','Right View',,,,,,],
['blu','Rear View',,,,,,],
['blu','Top View',,,,,,],
['blu','Bottom\nView',,,,,,],
['blu','Owned\nMissile',,,,,,],
['blu','Enemy\nMissile',,,,,,],
['blu','View Self',,,,,,],
['blu','View\nTarget',,,,,,],
,
,
,
['red','Decouple\nGun',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,

]
Sch_Table['leg'][sLay] =
[
['red','Combat'],
['yel','Targeting'],
['grn','Navigation'],
['blu','Camera']
]
Sch_Table['com'][sLay] = []
Sch_Table['mou'][sLay] = []
Sch_Table['joy'][sLay] = []
Sch_Table['add'][sLay] = []
