sLay = 'ATUS104'
Sch_Table['gam'][sLay] = 'Thief: The Dark Project'
Sch_Table['aut'][sLay] = ''
Sch_Table['key'][sLay] =
[
,
['red','Clear\nWeapon',,,,,,],
['red','Sword',,,,,,],
['red','Blackjack',,,,,,],
['red','Broadhead\nArrow',,,,,,],
['red','Water\nArrow',,,,,,],
['red','Fire\nArrow',,,,,,],
['red','Moss\nArrow',,,,,,],
['red','Gas\nArrow',,,,,,],
['red','Rope\nArrow',,,,,,],
['red','Noise\nArrow',,,,,,],
,
['mag','Gamma -',,,,,,],
['mag','Gamma +',,,,,,],
['yel','Clear Item',,,,,,],
['yel','Next Item','Previous',,,,,],
['grn','Lean Left',,,,,,],
['grn','Run',,,,,,],
['grn','Lean Right',,,,,,],
['yel','Drop Item',,,,,,],
['blu','Look Up',,,,,,],
,
,
,
['mag','Objectives',,,,,,],
,
['yel','Previous\nItem',,,,,,],
['yel','Next\nItem',,,,,,],
,
,
['grn','Turn Left',,,,,,],
['grn','Walk',,,,,,],
['grn','Turn Right',,,,,,],
['grn','Crouch',,,,,,],
['blu','Look Down',,,,,,],
,
,
,
,
,
,
,
,
,
,
['grn','Strafe\nLeft',,,,,,],
['grn','Backpedal',,,,,,],
['grn','Strafe\nRight',,,,,,],
['blu','Center\nView',,,,,,],
,
,
['mag','Map',,,,,,],
,
,
,
,
,
,
['grn','Jump / Block',,,,,,],
,
,
,
,
['grn','Turn Left',,,'Strafe Left',,,],
,
,
['grn','Run',,,,,,],
['grn','Backpedal',,,,,,],
['blu','Look Up',,,,,,],
['blu','Look Down',,,,,,],
['grn','Turn Right',,,'Strafe Right',,,],
,
['grn','Lean Left',,,,,,],
['grn','Turn Left',,,,,,],
['grn','Strafe\nLeft',,,,,,],
['yel','Previous\nItem',,,,,,],
['grn','Run',,,,,,],
['grn','Walk',,,,,,],
['grn','Backpedal',,,,,,],
['grn','Jump / Block',,,,,,],
['yel','Next\nItem',,,,,,],
['grn','Lean Right',,,,,,],
['grn','Turn Right',,,,,,],
['grn','Strafe\nRight',,,,,,],
['blu','Center\nView',,,,,,],
,
,
,
['mag','Main Menu',,,,,,],
['yel','Healing\nPotion',,,,,,],
['yel','Breath\nPotion',,,,,,],
['yel','Holy\nWater',,,,,,],
['yel','Lockpick\n1',,,,,,],
['yel','Lockpick\n2',,,,,,],
['yel','Flash\nBomb',,,,,,],
['yel','Gas\nMine',,,,,,],
['yel','Mine',,,,,,],
['yel','Compass',,,,,,],
['mag','Screen-\nshot',,,,,,],
['mag','Quick\nSave',,,,,,],
['mag','Quick\nLoad',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,

]
Sch_Table['leg'][sLay] =
[
['red','Weapons'],
['yel','Items'],
['grn','Movement'],
['blu','Camera'],
['mag','Game Controls']
]
Sch_Table['com'][sLay] = []
Sch_Table['mou'][sLay] =
[       
'Left Click = Attack',
'Right Click = Use Item',
'Middle Click = Block'
]
Sch_Table['joy'][sLay] = []
Sch_Table['add'][sLay] = []
sLay = 'ATUS104DVO'
Sch_Table['gam'][sLay] = Sch_Table['gam']['ATUS104']
Sch_Table['aut'][sLay] = Sch_Table['aut']['ATUS104']
Sch_Table['key'][sLay] = Sch_Table['key']['ATUS104']
Sch_Table['leg'][sLay] = Sch_Table['leg']['ATUS104']
Sch_Table['com'][sLay] = Sch_Table['com']['ATUS104']
Sch_Table['mou'][sLay] = Sch_Table['mou']['ATUS104']
Sch_Table['joy'][sLay] = Sch_Table['joy']['ATUS104']
Sch_Table['add'][sLay] = Sch_Table['add']['ATUS104']
