sLay = 'ATUS104'
Sch_Table['gam'][sLay] = 'Tropico 2: Pirate Cove'
Sch_Table['aut'][sLay] = ''
Sch_Table['key'][sLay] =
[
,
,
['red','Hotkey',,,'Assign',,,],
['red','Hotkey',,,'Assign',,,],
['red','Hotkey',,,'Assign',,,],
['red','Hotkey',,,'Assign',,,],
['red','Hotkey',,,'Assign',,,],
['red','Hotkey',,,'Assign',,,],
['red','Hotkey',,,'Assign',,,],
['red','Hotkey',,,'Assign',,,],
['red','Hotkey',,,'Assign',,,],
['red','Hotkey',,,'Assign',,,],
['mag','Game\nSpeed -',,,,,,],
['mag','Game\nSpeed +',,,,,,],
['red','Center on Item\nin Circle Window',,,,,,],
,
['mag','Quick\nSave',,,,,,],
['grn','Captive\nSatisfaction',,,,,,],
['yel','Edict\nPanel',,,,,,],
['mag','Show\nScreen\nResolution',,,,,,],
['mag','Toggle\nTrees',,,,,,],
,
,
,
['yel','Overview\nPanel',,,,,,],
['grn','Pirate\nSatisfaction',,,,,,],
,
,
,
,
['yel','Assistant\nPanel',,,,,,],
,
['grn','Pirate\nDemo-\ngraphics','Captive\nDemo-\ngraphics',,,,,],
,
['mag','Toggle\nGridlines',,,,,,],
,
,
,
['grn','Island Log',,,,,,],
,
,
,
,
['red','(Hold)\nFire Employee',,,,,,],
,
['mag','Show Zoom\nLevel',,,,,,],
,
['yel','Construction\nPanel',,,,,,],
,
,
,
['yel','Strategic\nMap',,,,,,],
,
,
,
['red','(Hold)\nFire Employee',,,,,,],
['red','(Hold)\nMultiple Edict',,,,,,],
['yel','Hotkey\nPanel',,,,,,],
,
['yel','Hotkey\nPanel',,,,,,],
['red','(Hold)\nMultiple Edict',,,,,,],
,
,
['blu','Scroll Left',,,,,,],
['blu','Scroll\nUp-Left',,,,,,],
['blu','Scroll\nDown-Left',,,,,,],
['blu','Scroll Up',,,,,,],
['blu','Scroll Down',,,,,,],
['blu','Scroll\nUp-Right',,,,,,],
['blu','Scroll\nDown-Right',,,,,,],
['blu','Scroll Right',,,,,,],
,
,
['blu','Rotate\nConter-\nclockwise',,,,,,],
,
,
,
,
,
,
,
,
['blu','Rotate\nClockwise',,,,,,],
,
,
['blu','Zoom Out',,,,,,],
['blu','Zoom In',,,,,,],
,
['mag','Game\nOptions',,,,,,],
['yel','Assistant\nPanel',,,,,,],
,
,
['mag','Toggle\nFullscreen /\nWindow',,,,,,],
,
['mag','Decrease\nScreen\nResolution',,,,,,],
['mag','Increase\nScreen\nResolution',,,,,,],
,
,
,
,
,
,
,
['mag','Pause\nGame',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,

]
Sch_Table['leg'][sLay] =
[
['yel','Menus'],
['grn','Island Log Chapters'],
['red','Action'],
['blu','Camera Controls'],
['mag','Game Controls']
]
Sch_Table['com'][sLay] = []
Sch_Table['mou'][sLay] = []
Sch_Table['joy'][sLay] = []
Sch_Table['add'][sLay] = []
sLay = 'ATUS104DVO'
Sch_Table['gam'][sLay] = Sch_Table['gam']['ATUS104']
Sch_Table['aut'][sLay] = Sch_Table['aut']['ATUS104']
Sch_Table['key'][sLay] = Sch_Table['key']['ATUS104']
Sch_Table['leg'][sLay] = Sch_Table['leg']['ATUS104']
Sch_Table['com'][sLay] = Sch_Table['com']['ATUS104']
Sch_Table['mou'][sLay] = Sch_Table['mou']['ATUS104']
Sch_Table['joy'][sLay] = Sch_Table['joy']['ATUS104']
Sch_Table['add'][sLay] = Sch_Table['add']['ATUS104']
