sLay = 'ATUS104'
Sch_Table['gam'][sLay] = 'FreeSpace 2'
Sch_Table['aut'][sLay] = ''
Sch_Table['key'][sLay] =
[
,
['cyn','Voice\nChat',,,,,,],
['cyn','Chat\nAll',,,,,,],
['cyn','Chat\nTeam',,,,,,],
['cyn','Chat\nOpponents',,,,,,],
['cyn','Chat\nTarget',,,,,,],
,
,
,
,
,
,
['grn','Throttle\nDown 5%',,,,,,],
['grn','Throttle\nUp 5%',,,,,,],
['grn','Zero Throttle',,,,,,],
['grn','Afterburner',,,,,,],
,
[,,'Form\non Wing',,,,,],
['yel','Next\nEscort Ship',,,,,,],
['yel','Closest\nAttacker',,,'Next\nRepair\nShip',,,],
['yel','Next\nShip','Prev',,,,,],
['yel','Ship in\nReticle',,,,,,],
['yel','Next\nUnscanned\nObject',,,,,,],
,
,
,
['grn','Throttle\nto 1/3',,,,,,],
['grn','Throttle\nto 2/3',,,,,,],
['grn','Full Throttle',,,,,,],
,
['grn','Accelerate','Attack my\nTarget',,,,,],
['yel','Next\nSubsys','Prev',,'Cease\nTar-\ngeting',,,],
,
['yel','Next\nClosest\nFriendly','Prev',,,,,],
['yel','Newest\nAttacker',,,,,,],
['yel','Next\nClosest\nHostile','Prev',,'Toggle\nAuto\nTarget',,,],
['yel','Target\'s\nTarget',,,'Sub-\nspace\nJump',,,],
,
,
,
['gry','Radar\nRanges',,,,,,],
,
,
,
,
['grn','Decelerate',,,,,,],
['red','Counter-\nmeasures',,,,,,],
['cyn','Comms\nMenu',,,,,,],
['yel','Subsys in\nReticle',,,,,,],
['yel','Next Bomb\n/ Bomber',,,,,,],
['yel','Newest\nin System',,,,,,],
['grn','Match\nTarget\'s\nSpeed',,,'Auto\nMatch',,,],
['red','Cycle\nPrimary -',,,,,,],
['red','Cycle\nPrimary +',,,,,,],
['red','Cycle\nSecondary','Toggle\nDual Fire',,,,,],
,
['red','Fire Primary',,,,,,],
,
['red','Fire Secondary',,,,,,],
,
['red','Fire Primary',,,,,,],
['mag','Primary\nRecharge +',,,,,,],
['mag','Primary\nRecharge -',,,,,,],
['mag','Left\nShield +',,,,,,],
['mag','Shield\nRecharge +',,,,,,],
['mag','Shield\nRecharge -',,,,,,],
['mag','Forward\nShield +',,,,,,],
['mag','Rear\nShield +',,,,,,],
['mag','Engine\nRecharge +',,,,,,],
['mag','Engine\nRecharge -',,,,,,],
['mag','Right\nShield +',,,,,,],
,
['grn','Bank Left',,,,,,],
['grn','Turn Left',,,,,,],
,
['blu','Target\nView',,,,,,],
['grn','Pitch Down',,,,,,],
['blu','Center\nView',,,,,,],
['grn','Pitch Up',,,,,,],
,
['blu','Chase\nView',,,,,,],
['grn','Bank Right',,,,,,],
['grn','Turn Right',,,,,,],
,
['blu','External\nView',,,,,,],
['blu','Decrease\nZoom',,,,,,],
['blu','Increase\nZoom',,,,,,],
,
['gry','Help',,,,,,],
['gry','Options',,,,,,],
['gry','Assign\nHotkeys',,,,,,],
,
,
['yel','(Alpha)\nWing 1',,,,,,],
['yel','(Beta)\nWing 2',,,,,,],
['yel','(Gamma)\nWing 3',,,,,,],
['yel','Wing 4',,,,,,],
['yel','Wing 5',,,,,,],
['yel','Wing 6',,,,,,],
['yel','Wing 7',,,,,,],
['yel','Wing 8',,,,,,],
,
['mag','Shield to\nWeapons','Weapons\nto Shields',,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,

]
Sch_Table['leg'][sLay] =
[
['red','Weapons'],
['yel','Targeting'],
['mag','Energy Management'],
['cyn','Communications'],
['gry','Game Controls']
]
Sch_Table['com'][sLay] = []
Sch_Table['mou'][sLay] = []
Sch_Table['joy'][sLay] = []
Sch_Table['add'][sLay] = []
sLay = 'ATUS104DVO'
Sch_Table['gam'][sLay] = Sch_Table['gam']['ATUS104']
Sch_Table['aut'][sLay] = Sch_Table['aut']['ATUS104']
Sch_Table['key'][sLay] = Sch_Table['key']['ATUS104']
Sch_Table['leg'][sLay] = Sch_Table['leg']['ATUS104']
Sch_Table['com'][sLay] = Sch_Table['com']['ATUS104']
Sch_Table['mou'][sLay] = Sch_Table['mou']['ATUS104']
Sch_Table['joy'][sLay] = Sch_Table['joy']['ATUS104']
Sch_Table['add'][sLay] = Sch_Table['add']['ATUS104']
