sLay = 'ATUS104'
Sch_Table['gam'][sLay] = 'Silent Hunter II'
Sch_Table['aut'][sLay] = ''
Sch_Table['key'][sLay] =
[
,
['grn','All\nStop',,,,,,],
['grn','Ahead\nSlow',,,,,,],
['grn','Ahead\n1/3',,,,,,],
['grn','Ahead\nStandard',,,,,,],
['grn','Ahead\nFull',,,,,,],
['grn','Ahead\nFlank',,,,,,],
['grn','Back\nSlow',,,,,,],
['grn','Back\n1/3',,,,,,],
['grn','Back\nStandard',,,,,,],
['grn','Back\nEmergency',,,,,,],
,
['cyn','Slower\n(- TC)',,,,,,],
['cyn','Faster\n(+ TC)',,,,,,],
['cyn','Pause\n(0x TC)',,,,,,],
,
['yel','Navigation\nControl',,,,,,],
['yel','Torpedo\nFire Control',,,,,,],
['yel','Command\nControl',,,,,,],
['yel','Vessel ID\nControl',,,,,,],
['red','Cycle\nTorpedo\nTube',,,,,,],
,
,
,
,
['grn','Periscope\nDepth',,,,,,],
['grn','Rudder\nLeft 5\u00b0',,'Rudder\nLeft Full',,,,],
['grn','Rudder\nRight 5\u00b0',,'Rudder\nRight Full',,,,],
['cyn','Normal\n(1x TC)',,,,,,],
,
,
['grn','Surface the\nBoat',,,,,,],
['grn','Snorkel\nDepth',,,,,,],
['grn','Raise/Lower\nSnorkel',,,,,,],
,
['blu','Heading\nto View',,,,,,],
['blu','Return to\nSet Heading',,,,,,],
,
['red','Lock\nSelected\nTarget',,,,,,],
,
['grn','Rudder\nAmidships',,,,,,],
,
['red','Fire Currently Selected\nTorpedo Tube',,,,,,],
,
,
['blu','Zoom\nView',,,,,,],
['blu','Toggle\nPadlock\nView',,,,,,],
['grn','Crash\nDive',,,,,,],
['blu','View to\nHeading',,,,,,],
['grn','Blow\nBallast',,,,,,],
,
,
['blu','Previous\nShip/Gun',,,,,,],
['blu','Next\nShip/Gun',,,,,,],
,
,
,
,
['red','Fire gun',,,,,,],
,
,
,
,
['blu','Rotate\nView/Gun\nLeft',,,,,,],
['blu','Center on\nYour Boat',,,,,,],
,
['blu','Lower\nView/Gun',,,,,,],
['blu','Raise\nView/Gun',,,,,,],
,
,
['blu','Rotate\nView/Gun\nRight',,,,,,],
['yel','Captain\'s\nCabin',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
['mag','Exit',,,,,,],
['mag','Help',,,,,,],
['yel','Periscope',,,,,,],
['yel','Navigation',,,,,,],
['yel','Helm and\nGauges',,,,,,],
['yel','Torpedo\nFire Control',,,,,,],
['yel','Deck Gun',,,,,,],
['yel','Machine\nGun',,,,,,],
['yel','UZO',,,,,,],
['yel','Bridge',,,,,,],
['yel','Damage\nControl',,,,,,],
['yel','Torpedo\nStatus',,,,,,],
['yel','External\nView',,,,,,],
['yel','Radio\nRoom',,'Screen\nCapture',,,,],
['yel','Sound\nRoom',,,,,,],
['yel','Radar',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,

]
Sch_Table['leg'][sLay] =
[
['red','Weapons/Targeting Controls'],
['grn','Helm Controls'],
['blu','View Controls'],
['yel','In-Game Stations'],
['cyn','Time Compression Controls'],
['mag','Miscellaneous']
]
Sch_Table['com'][sLay] = []
Sch_Table['mou'][sLay] = []
Sch_Table['joy'][sLay] = []
Sch_Table['add'][sLay] = []
sLay = 'ATUS104DVO'
Sch_Table['gam'][sLay] = Sch_Table['gam']['ATUS104']
Sch_Table['aut'][sLay] = Sch_Table['aut']['ATUS104']
Sch_Table['key'][sLay] = Sch_Table['key']['ATUS104']
Sch_Table['leg'][sLay] = Sch_Table['leg']['ATUS104']
Sch_Table['com'][sLay] = Sch_Table['com']['ATUS104']
Sch_Table['mou'][sLay] = Sch_Table['mou']['ATUS104']
Sch_Table['joy'][sLay] = Sch_Table['joy']['ATUS104']
Sch_Table['add'][sLay] = Sch_Table['add']['ATUS104']
