sLay = 'ATUS104'
Sch_Table['gam'][sLay] = 'Space Rangers 2 (Main)'
Sch_Table['aut'][sLay] = ''
Sch_Table['key'][sLay] =
[
,
['red','All\nWeapons',,,,,,],
['blu','Select\nWeapon',,,,,,],
['blu','Select\nWeapon',,,,,,],
['blu','Select\nWeapon',,,,,,],
['blu','Select\nWeapon',,,,,,],
['blu','Select\nWeapon',,,,,,],
,
,
,
,
,
,
['red','Unselected\nWeapons',,,,,,],
,
,
,
['red','Weapon\nPanel',,,,,,],
['yel','Equpm\'t\nStore',,,,,,],
['mag','Ranger\nRatings',,,,,,],
['red','Talk to\nShip /\nTrade\nCenter',,,,,,],
,
,
['red','Scan Ship /\nInfo Center',,,,,,],
,
['blu','Pause\nGame',,,,,,],
,
,
,
,
['blu','Autopilot /\nRepair Hull',,,,,,],
['mag','Ship\nMenu',,,,,,],
,
['red','Engine Boost /\nTake Off',,,,,,],
['yel','Gov\'t\nBuilding',,,,,,],
['grn','Hangar /\nFlight Log',,,,,,],
,
,
,
,
,
,
,
['blu','Fire Secondary',,,,,,],
,
,
,
['red','Center\non Ship',,,,,,],
,
['grn','Refuel',,,,,,],
,
['mag','Galaxy\nMap',,,,,,],
,
,
,
['blu','Fire Secondary',,,,,,],
['blu','Fire Primary',,,,,,],
['blu','Pick up\nItem',,,,,,],
['mag','End Turn',,,,,,],
['blu','Pick up\nItem',,,,,,],
['blu','Fire Primary',,,,,,],
,
,
['blu','Move\nLeft',,,,,,],
,
,
['blu','Move\nUp',,,,,,],
['blu','Move\nDown',,,,,,],
,
,
['blu','Move\nRight',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
['mag','Game\nMenu',,,,,,],
,
['mag','Save\nGame',,,,,,],
['mag','Load\nGame',,,,,,],
[,,,,'Exit',,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,

]
Sch_Table['leg'][sLay] =
[
['mag','All Modes'],
['yel','Planet Mode'],
['grn','Hangar Mode'],
['red','Space Mode'],
['blu','Arcade Mode']
]
Sch_Table['com'][sLay] = []
Sch_Table['mou'][sLay] = []
Sch_Table['joy'][sLay] = []
Sch_Table['add'][sLay] = []
sLay = 'ATUS104DVO'
Sch_Table['gam'][sLay] = Sch_Table['gam']['ATUS104']
Sch_Table['aut'][sLay] = Sch_Table['aut']['ATUS104']
Sch_Table['key'][sLay] = Sch_Table['key']['ATUS104']
Sch_Table['leg'][sLay] = Sch_Table['leg']['ATUS104']
Sch_Table['com'][sLay] = Sch_Table['com']['ATUS104']
Sch_Table['mou'][sLay] = Sch_Table['mou']['ATUS104']
Sch_Table['joy'][sLay] = Sch_Table['joy']['ATUS104']
Sch_Table['add'][sLay] = Sch_Table['add']['ATUS104']
