sLay = 'ATUS104'
Sch_Table['gam'][sLay] = 'Privateer'
Sch_Table['aut'][sLay] = ''
Sch_Table['key'][sLay] =
[
,
,
['red','Select\nGun',,,,,,],
['red','Select\nGun',,,,,,],
['red','Select\nGun',,,,,,],
['red','Select\nGun',,,,,,],
['red','Select\nGun',,,,,,],
['red','Select\nGun',,,,,,],
['red','Select\nGun',,,,,,],
['red','Select\nGun',,,,,,],
['red','Select\nGun',,,,,,],
['red','Select\nGun',,,,,,],
['grn','Decrease\nSpeed',,,,,,],
['grn','Increase\nSpeed',,,,,,],
['grn','Zero Speed',,,,,,],
['grn','Afterburner',,,,,,],
['yel','Quadrant\nMap',,,,,,],
['red','Weapons\nDisplay',,,,,,],
['yel','Target\nStatus',,,,,,],
['red','Damage\nDisplay',,,,,,],
['yel','Closest\nin Front',,,,,,],
,
,
['yel','ITTS /\nNAV Info',,,,,,],
[,,,,'Options',,,],
['mag','Pause',,,,,,],
['yel','Left MFD',,,,,,],
['yel','Right MFD',,,,,,],
,
,
['grn','Autopilot',,,,,,],
['red','Shield\nLevel',,,,,,],
['yel','Destination',,,'Self-\nDestruct',,,],
,
['red','Guns\nDisplay',,,,,,],
,
['grn','Jump\nDrive',,,,,,],
,
['yel','Lock on\nTarget',,,,,,],
,
,
,
,
,
,
['yel','Zoom\nLevel',,,,,,],
['red','Jettison\nCargo',,,'Exit',,,],
['yel','Comm\nMFD',,,'Pilot\nComp.',,,],
['yel','Target\nDisplay',,,,,,],
,
['yel','NAV\nComp.',,,,,,],
['yel','Info /\nManifest',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
['blu','Front\nView',,,,,,],
['blu','Port\nView',,,,,,],
['blu','Starboard\nView',,,,,,],
['blu','Aft\nView',,,,,,],
['blu','Turret\n1',,,,,,],
['blu','Turret\n2',,,,,,],
['blu','Missile\nView',,,,,,],
['blu','Chase\nView',,,,,,],
['blu','Panorama\nView',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,

]
Sch_Table['leg'][sLay] =
[
['red','Combat'],
['yel','Targeting'],
['grn','Navigation'],
['blu','Camera'],
['mag','Game Controls']
]
Sch_Table['com'][sLay] = []
Sch_Table['mou'][sLay] = []
Sch_Table['joy'][sLay] = []
Sch_Table['add'][sLay] = []
sLay = 'ATUS104DVO'
Sch_Table['gam'][sLay] = Sch_Table['gam']['ATUS104']
Sch_Table['aut'][sLay] = Sch_Table['aut']['ATUS104']
Sch_Table['key'][sLay] = Sch_Table['key']['ATUS104']
Sch_Table['leg'][sLay] = Sch_Table['leg']['ATUS104']
Sch_Table['com'][sLay] = Sch_Table['com']['ATUS104']
Sch_Table['mou'][sLay] = Sch_Table['mou']['ATUS104']
Sch_Table['joy'][sLay] = Sch_Table['joy']['ATUS104']
Sch_Table['add'][sLay] = Sch_Table['add']['ATUS104']
