sLay = 'ATUS104'
Sch_Table['gam'][sLay] = 'Total Annihilation'
Sch_Table['aut'][sLay] = ''
Sch_Table['key'][sLay] =
[
,
['mag','Toggle\nHealthbars',,,,,,],
['yel','Unit\nMenu',,'Assign','Select\nSquad',,,],
['yel','Unit\nMenu',,'Assign','Select\nSquad',,,],
['yel','Unit\nMenu',,'Assign','Select\nSquad',,,],
['yel','Unit\nMenu',,'Assign','Select\nSquad',,,],
['yel','Unit\nMenu',,'Assign','Select\nSquad',,,],
['yel','Unit\nMenu',,'Assign','Select\nSquad',,,],
['yel','Unit\nMenu',,'Assign','Select\nSquad',,,],
['yel','Unit\nMenu',,'Assign','Select\nSquad',,,],
['yel','Unit\nMenu',,'Assign','Select\nSquad',,,],
,                  
['red','Game\nSpeed -',,,,,,],
['red','Game\nSpeed +',,,,,,],
,
,
[,,,'Select\nArmed\nMobile',,,,],
,
['red','Reclaim',,,,,,],
['red','Repair',,'Select\nRadar/\nJammers',,,,],
['blu','Track\nUnit',,,,,,],
,
['red','Unload',,,,,,],
,
['mag','Order\nMenu',,,,,,],
['red','Patrol',,'Select\nArmed\nAircraft',,,,],
,
,
,
,
['red','Attack',,'Select\nAll',,,,],
['red','Stop',,'Select\nVisible',,,,],
['red','D-Gun',,'Self\nDestruct',,,,],
[,,,,,,,],
['red','Guard',,,,,,],
['cyn','Share\nResources',,,,,,],
,
['red','Cloak',,,,,,],
['red','Load',,,,,,],
,
,
,
['mag','Show Messages',,,,,,],
['red','(Hold)\nQueue Orders',,,,,,],
,
[,,,'Select\nAll of\nType',,,,],
,
['red','Capture',,'Focus on\nComm.',,,,],
[,,,'Select\nAircraft',,,,],
['mag','Build\nMenu',,'Select\nBuilder',,,,],
['yel','Next Unit',,,,,],
['red','Move',,,,,,],
['mag','Previous\nMenu',,,,,,],
['mag','Next\nMenu',,,,,,],
,
['red','(Hold)\nQueue Orders',,,,,,],
,
,
['mag','Game Stats / Unit Totals',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
['red','Cancel\nCommand',,,,,,],
['mag','Unit\nInfo',,,,,,],
['mag','Options\nMenu',,,,,,],
['mag','Go to\nLast\nReporter',,,,,,],
['mag','Show\nScores',,,,,,],
['blu','Select\nBookmark',,'Store',,,,],
['blu','Select\nBookmark',,'Store',,,,],
['blu','Select\nBookmark',,'Store',,,,],
['blu','Select\nBookmark',,'Store',,,,],
['mag','Screenshot',,,,,,],
,
,
['mag','Clear\nMessages',,,,,,],
,
,
['mag','Pause\nGame',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,

]
Sch_Table['leg'][sLay] =
[
['red','Orders/Actions'],
['yel','Selection'],
['blu','Camera'],
['cyn','Multiplayer'],
['mag','Game Controls']
]
Sch_Table['com'][sLay] = []
Sch_Table['mou'][sLay] = []
Sch_Table['joy'][sLay] = []
Sch_Table['add'][sLay] = []
sLay = 'ATUS104DVO'
Sch_Table['gam'][sLay] = Sch_Table['gam']['ATUS104']
Sch_Table['aut'][sLay] = Sch_Table['aut']['ATUS104']
Sch_Table['key'][sLay] = Sch_Table['key']['ATUS104']
Sch_Table['leg'][sLay] = Sch_Table['leg']['ATUS104']
Sch_Table['com'][sLay] = Sch_Table['com']['ATUS104']
Sch_Table['mou'][sLay] = Sch_Table['mou']['ATUS104']
Sch_Table['joy'][sLay] = Sch_Table['joy']['ATUS104']
Sch_Table['add'][sLay] = Sch_Table['add']['ATUS104']
