sLay = 'ATUS104'
Sch_Table['gam'][sLay] = 'Jagged Alliance 2'
Sch_Table['aut'][sLay] = ''
Sch_Table['key'][sLay] =
[
,
,
['yel','Select\nSquad 1','Squad 11','Assign...',,,,],
['yel','Select\nSquad 2','Squad 12','Assign...',,,,],
['yel','Select\nSquad 3','Squad 13','Assign...',,,,],
['yel','Select\nSquad 4','Squad 14','Assign...',,,,],
['yel','Select\nSquad 5','Squad 15','Assign...',,,,],
['yel','Select\nSquad 6','Squad 16','Assign...',,,,],
['yel','Select\nSquad 7','Squad 17','Assign...',,,,],
['yel','Select\nSquad 8','Squad 18','Assign...',,,,],
['yel','Select\nSquad 9','Squad 19','Assign...',,,,],
['yel','Select\nSquad 10','Squad 20','Assign...',,,,],
,                     
['yel','Select\nAll Mercs',,,,,,],
,
['mag','Toggle Roof /\nGround Mode',,,,,,],
,
['mag','Toggle\nWireframe',,,,,,],
['yel','Next\nVisible\nEnemy',,,,,,],
['red','Run',,,,,,],
['mag','Toggle\nTreetops',,'Toggle\nText\nShadow',,,,],
,
,
['mag','Toggle\nItem Glow',,,,,,],
['mag','Options\nScreen',,,,,,],
['red','Lie Prone',,,,,,],
,
,
,
,
['red','Auto-\nBandage',,,,,,],
['red','Stand\nUp',,'Save','Quick\nSave',,,],
['red','End Turn',,,,,,],
['mag','Show\nWeapon\nRanges',,,'Lock\nMerc',,,],
['mag','Toggle\nMerc Lights',,,,,,],
['mag','Help\nMessage',,,,,,],
,
['mag','Key Ring',,,,,,],
['red','Look',,'Load','Quick\nLoad',,,],
,
,
,
['yel','Next Enemy',,,,,,],
['yel','Show Movement Path /\nQuick Scroll /\nBand-Box Select /\nScroll Faster',,,,,,],
,
['red','Stealth\nMode',,,'All\nStealth',,,],
['red','Switch\nPlaces',,,'Exit\nGame',,,],
['red','Crouch',,,'Load\nLast\nSave',,,],
['mag','Show\nGame Info',,,,,,],
['red','Burst\nMode',,,,,,],
['yel','Select\nNext Unit\non Screen',,,,,,],
['mag','Map\nScreen',,,,,,],
,
,
['yel','Center\non Merc',,,,,,],
['yel','Show Movement Path /\nQuick Scroll /\nBand-Box Select /\nScroll Faster',,,,,,],
['yel','Hand Cursor /\nAdd to Selection',,,,,,],
['red','Side-Step /\nSelect or\nLocate Merc',,,,,,],
['yel','Select Next Merc','Select Next Squad',,,,,],
['red','Side-Step /\nSelect or\nLocate Merc',,,,,,],
['yel','Hand Cursor /\nAdd to Selection',,,,,,],
['mag','Sector\nMap',,,,,,],
['mag','Show\nCover',,,,,,],
['blu','Scroll\nLeft',,,,,,],
['mag','Show\nLine of\nSight',,,,,,],
['red','Continue\nPrevious\nMovement',,,,,,],
['blu','Scroll\nUp',,,,,,],
['blu','Scroll\nDown',,,,,,],
,
,
['blu','Scroll\nRight',,,,,,],
,
,
,
,
,
,
,
,
,
['mag','Toggle\nRed/White\nDrop Items',,,,,,],
,
,
,
,
,
,
,
['red','Cancel\nAction',,,,,,],
['yel','Select\nMerc',,,,,,],
['yel','Select\nMerc',,,,,,],
['yel','Select\nMerc',,,,,,],
['yel','Select\nMerc',,,,,,],
['yel','Select\nMerc',,,,,,],
['yel','Select\nMerc',,,,,,],
,
,
,
,
,
,
,
,
['mag','Pause\nGame',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,

]
Sch_Table['leg'][sLay] =
[
['yel','Selection'],
['red','Action'],
['mag','Game Controls'],
['blu','Camera']
]
Sch_Table['com'][sLay] =
[
'SHIFT + Drag LMB on Map = Band-box Select',
'CTRL + LMB on Merc = Add Merc to Selection',
'SHIFT + Arrow Keys = Scroll Faster',
'DELETE + \'-\' or \'+\' = Decrease\Increase Cover Distance',
'HOME + \'-\' or \'+\' = Decrease\Increase Line of Sight Information',
]
Sch_Table['mou'][sLay] = []
Sch_Table['joy'][sLay] = []
Sch_Table['add'][sLay] = []
sLay = 'ATUS104DVO'
Sch_Table['gam'][sLay] = Sch_Table['gam']['ATUS104']
Sch_Table['aut'][sLay] = Sch_Table['aut']['ATUS104']
Sch_Table['key'][sLay] = Sch_Table['key']['ATUS104']
Sch_Table['leg'][sLay] = Sch_Table['leg']['ATUS104']
Sch_Table['com'][sLay] = Sch_Table['com']['ATUS104']
Sch_Table['mou'][sLay] = Sch_Table['mou']['ATUS104']
Sch_Table['joy'][sLay] = Sch_Table['joy']['ATUS104']
Sch_Table['add'][sLay] = Sch_Table['add']['ATUS104']
