sLay = 'ATUS104'
Sch_Table['gam'][sLay] = 'Galactic Civilizations II: Dread Lords'
Sch_Table['aut'][sLay] = ''
Sch_Table['key'][sLay] =
[
,
,
['blu','Default\nView',,'Diplomacy\nPlyr 1',,,,],
['blu','Angled\nView',,'Diplomacy\nPlyr 2',,,,],
['blu','Near\nView',,'Diplomacy\nPlyr 3',,,,],
['blu','Above\nView',,'Diplomacy\nPlyr 4',,,,],
['blu','Strategic\nView',,'Diplomacy\nPlyr 5',,,,],
[,,,'Diplomacy\nPlyr 6',,,,],
[,,,'Diplomacy\nPlyr 7',,,,],
[,,,'Diplomacy\nPlyr 8',,,,],
[,,,'Diplomacy\nPlyr 9',,,,],
[,,,'Diplomacy\nPlyr 10',,,,],
['blu','Zoom Out',,,,,,],
['blu','Zoom In',,,,,,],
,
['yel','Select Next Ship',,,,,,],
,
['red','Sector\nSweep',,,,,,],
,
['red','Auto\nRetreat',,'Refresh\nSensors',,,,],
['mag','Rally Pt\nList',,,,,,],
,
['red','Unform\nFleet',,,,,,],
,
,
[,,'Strongest\nPlanet',,,,,],
['blu','Center on\nRally Pt -',,,,,,],
['blu','Center on\nRally Pt +',,,,,,],
,
,
['red','Auto\nSurvey',,,,,,],
['red','Sentry\nMode','Strongest\nShip','Quick\nSave',,,,],
['mag','Ship\nDetails',,,,,,],
['red','Form\nFleet','Strongest\nFleet',,,,,],
['red','Guard\nMode',,'Toggle\nGrid',,,,],
,
,
['red','Auto\nAttack',,,,,,],
[,,,'Load/\nSave\nGame',,,,],
,
,
,
['red','End Turn',,,,,,],
,
,
,
['mag','Rally Pt\nWindow',,,,,,],
['blu','Center\non Ship',,,,,,],
,
['red','Build\nStarbase',,,,,,],
[,,,'New\nGame',,,,],
[,,,'Toggle\nMusic',,,,],
['mag','Track -',,,,,,],
['mag','Track +',,,,,,],
,
,
,
,
['red','Confirm Ship Orders',,,,,,],
,
,
,
['red','Decomis-\nsion Ship',,,,,,],
['grn','Move\nShip\nLeft',,,,,,],
,
,
['grn','Move\nShip\nForward',,,,,,],
['grn','Move\nShip\nBackward',,,,,,],
,
,
['grn','Move\nShip\nRight',,,,,,],
,
,
['grn','Move\nShip\nLeft',,,,,,],
,
,
['grn','Move\nShip\nForward',,,,,,],
,
['grn','Move\nShip\nBackward',,,,,,],
,
,
,
['grn','Move\nShip\nRight',,,,,,],
,
,
,
,
,
['mag','Close\nWindow',,,,,,],
['mag','Planet\nList',,,,,,],
['mag','Ship\nList',,,,,,],
['mag','Research\nPolicy',,,,,,],
['mag','Domestic\nPolicy',,,,,,],
['mag','Foreign\nPolicy',,,,,,],
['mag','Civilization\nManager',,,,,,],
['mag','Shipyard',,,,,,],
['mag','Options\nScreen',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,

]
Sch_Table['leg'][sLay] =
[
['red','Commands/Orders'],
['grn','Movement'],
['yel','Selection'],
['blu','Camera'],
['mag','Game Controls']
]
Sch_Table['com'][sLay] =
[
'CTRL + Click LMB = Add Ships to Selection',
'SHIFT + Drag LMB = Band-box Select'
]
Sch_Table['mou'][sLay] =
[        
'Click LMB = Select Ship',
'Double-Click LMB = Object Data',
'Click RMB = Move Ship to Destination',
'Drag LMB = Pan Map'
]
Sch_Table['joy'][sLay] = []
Sch_Table['add'][sLay] = []
sLay = 'ATUS104DVO'
Sch_Table['gam'][sLay] = Sch_Table['gam']['ATUS104']
Sch_Table['aut'][sLay] = Sch_Table['aut']['ATUS104']
Sch_Table['key'][sLay] = Sch_Table['key']['ATUS104']
Sch_Table['leg'][sLay] = Sch_Table['leg']['ATUS104']
Sch_Table['com'][sLay] = Sch_Table['com']['ATUS104']
Sch_Table['mou'][sLay] = Sch_Table['mou']['ATUS104']
Sch_Table['joy'][sLay] = Sch_Table['joy']['ATUS104']
Sch_Table['add'][sLay] = Sch_Table['add']['ATUS104']
