sLay = 'ATUS104'
Sch_Table['gam'][sLay] = 'System Shock'
Sch_Table['aut'][sLay] = ''
Sch_Table['key'][sLay] =
[
,
,
['yel','Bioscan',,,,,,],
['mag','Fullscreen\nView',,,,,,],
['yel','Sense\n-Around',,,,,,],
['yel','Lantern',,,,,,],
['yel','Energy\nShield',,,,,,],
['yel','Night\nSight',,,,,,],
['yel','NAV\nModule',,,'Enhanced\nFeatures',,,],
['yel','Reader',,,'Coord-\ninates &\nVideo Mode',,,],
['grn','Motion\nBoost',,,,,,],
['grn','Jump Jet',,,,,,],
['mag','Zoom\nMap Out',,,,,,],
['mag','Zoom\nMap In',,,,,,],
['mag','Clear Display',,,,,,],
['yel','Cycle\nWeapons\nForward','Cycle\nWeapons\nBackward',,,,,],
['grn','Lean\nLeft',,,,,,],
['grn','Negate\nLean',,,,,,],
['grn','Lean\nRight',,,,,,],
['grn','Look\nUp',,,,,,],
['grn','Stand',,,,,,],
,
,
,
[,,,,'Display\nDescription',,,],
['mag','Pause\nGame',,,,,,],
,
,
,
,
['grn','Turn\nLeft',,'Fullscreen\nMap',,,,],
['grn','Walk\nForward',,'Save\nGame',,,,],
['grn','Turn\nRight',,,,,,],
['grn','Center\nView',,,,,,],
['grn','Crouch',,,,,,],
[,,,'HUD\nColors','Help',,,],
['grn','Jump',,,,,,],
,
[,,,'Load\nGame',,,,],
,
,
,
['red','Fire Weapon',,,,,,],
['grn','Run',,,,,,],
,
['grn','Strafe\nLeft',,,,,,],
['grn','Walk\nBackward',,,'Exit\nGame',,,],
['grn','Strafe\nRight',,,,,,],
['grn','Look\nDown',,,'Fullscreen\nView',,,],
['grn','Lie\nProne',,,,,,],
,
,
,
,
[,,'Reference',,,,,],
,
,
,
['grn','Jump',,,,,,],
,
,
,
['mag','Cut\nSpeech',,,,,,],
['grn','Turn\nLeft',,'Lean','Strafe',,,],
,
,
['grn','Walk\nForward',,'Look',,,,],
['grn','Walk\nBackward',,'Look',,,,],
['yel','Cycle\nInventory\nUp',,,,,,],
['yel','Cycle\nInventory\nDown',,,,,,],
['grn','Turn\nRight',,'Lean','Strafe',,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
['mag','Options\nScreen',,,,,,],
['mag','Weapon\nMFD',,,,,,],
['mag','Item\nMFD',,,,,,],
['mag','Automap',,,,,,],
['mag','Target\nMFD',,,,,,],
['mag','Data\nMFD',,,,,,],
['mag','Weapon\nMFD',,,,,,],
['mag','Item\nMFD',,,,,,],
['mag','Automap',,,,,,],
['mag','Target\nMFD',,,,,,],
['mag','Data\nMFD',,,,,,],
,
,
,
,
['mag','Pause\nGame',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,

]
Sch_Table['leg'][sLay] =
[
['red','Combat'],
['yel','Inventory'],
['grn','Movement'],
['mag','Game Controls']
]
Sch_Table['com'][sLay] =
[
'Climb = Space + Up'
]
Sch_Table['mou'][sLay] = []
Sch_Table['joy'][sLay] = []
Sch_Table['add'][sLay] = []
sLay = 'ATUS104DVO'
Sch_Table['gam'][sLay] = Sch_Table['gam']['ATUS104']
Sch_Table['aut'][sLay] = Sch_Table['aut']['ATUS104']
Sch_Table['key'][sLay] = Sch_Table['key']['ATUS104']
Sch_Table['leg'][sLay] = Sch_Table['leg']['ATUS104']
Sch_Table['com'][sLay] = Sch_Table['com']['ATUS104']
Sch_Table['mou'][sLay] = Sch_Table['mou']['ATUS104']
Sch_Table['joy'][sLay] = Sch_Table['joy']['ATUS104']
Sch_Table['add'][sLay] = Sch_Table['add']['ATUS104']
