sLay = 'ATUS104'
Sch_Table['gam'][sLay] = 'Jagged Alliance 2 (1.13)'
Sch_Table['aut'][sLay] = ''
Sch_Table['key'][sLay] =
[
,
,
['yel','Select\nSquad 1','Squad 11','Assign...',,,,],
['yel','Select\nSquad 2','Squad 12','Assign...','Spawn\nBaby\nCrep',,,],
['yel','Select\nSquad 3','Squad 13','Assign...',,,,],
['yel','Select\nSquad 4','Squad 14','Assign...','Put\nin\nChair',,,],
['yel','Select\nSquad 5','Squad 15','Assign...','Turn\ninto\nCrep',,,],
['yel','Select\nSquad 6','Squad 16','Assign...',,,,],
['yel','Select\nSquad 7','Squad 17','Assign...',,,,],
['yel','Select\nSquad 8','Squad 18','Assign...',,,,],
['yel','Select\nSquad 9','Squad 19','Assign...',,,,],
['yel','Select\nSquad 10','Squad 20','Assign...',,,,],
,                     
['yel','Select\nAll Mercs',,,,,,],
,
['mag','Toggle Roof /\nGround Mode',,,,,,],
[,,,,'Show\nInteriors',,,],
['mag','Toggle\nWire-\nframe',,,'Prog\nScroll',,,],
['yel','Next\nVisible\nEnemy',,,'Show\nAll',,,],
['red','Run',,,'Reload\nGun',,,],
['mag','Toggle\nTree-\ntops',,'Arrest\nMercs','Teleport',,,],
,
[,,,'Heal\nMe',,,,],
['mag','Toggle\nItem\nGlow',,,'Spawn\nGun',,,],
['mag','Options\nScreen',,'Spawn\nCrep','Kill\nAll',,,],
['red','Lie Prone',,,,,,],
,
,
,
,
['red','Auto-\nBandage',,,,,,],
['red','Stand\nUp',,'Save','Quick\nSave',,,],
['red','End Turn',,,,,,],
['mag','Show\nWeapon\nRanges',,'Show\nFPS','Lock\non Merc',,,],
['mag','Toggle\nMerc\nLights',,,'Spawn\nMerc',,,],
['mag','Help',,'Inflict\nDamage',,,,],
,
['mag','Key Ring',,,,,,],
['red','Look',,'Load','Quick\nLoad',,,],
,
,
,
['yel','Next Enemy',,,'Abort Enemy Turn',,,],
['yel','Show Movement Path /\nQuick Scroll /\nBand-Box Select /\nScroll Faster',,,,,,],
,
['red','Stealth\nMode',,,'All\nStealth',,,],
['red','Switch\nPlaces',,,'Exit\nGame',,,],
['red','Crouch',,,'Spawn\nCivvie',,,],
['mag','Show\nGame\nInfo',,,'Spawn\nRobot',,,],
['red','Burst\nMode',,,'Spawn\nEnemy',,,],
['yel','Select\nNext Unit\non Screen',,,,,,],
['mag','Map\nScreen',,,,,,],
,
,
['yel','Center\non Merc',,,,,,],
['yel','Show Movement Path /\nQuick Scroll /\nBand-Box Select /\nScroll Faster',,,,,,],
['yel','Hand Cursor /\nAdd to Selection',,,,,,],
['red','Side-Step /\nSelect or\nLocate Merc',,,,,,],
['yel','Select Next Merc','Select Next Squad',,,,,],
['red','Side-Step /\nSelect or\nLocate Merc',,,,,,],
['yel','Hand Cursor /\nAdd to Selection',,,,,,],
['mag','Sector\nMap',,,,,,],
['mag','Show\nBest\nCover',,,,,,],
['blu','Scroll\nLeft',,,,,,],
['mag','Show\nLine of\nSight',,,,,,],
,
['blu','Scroll\nUp',,,,,,],
['blu','Scroll\nDown',,,,,,],
,
,
['blu','Scroll\nRight',,,,,,],
,
,
,
['gry','Turn into\nTank',,,,,,],
,
,
,
,
,
['mag','Toggle\nRed/White\nDrops',,,,,,],
,
,
,
,
,
,
,
['red','Cancel\nAction',,,,,,],
['yel','Select\nMerc',,,,,,],
['yel','Select\nMerc',,,,,,],
['yel','Select\nMerc',,,,,,],
['yel','Select\nMerc',,,,,,],
['yel','Select\nMerc',,,,,,],
['yel','Select\nMerc',,,,,,],
,
,
,
,
,
,
,
,
['mag','Pause\nGame',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,

]
Sch_Table['leg'][sLay] =
[
['yel','Selection'],
['red','Action'],
['blu','Camera'],
['mag','Game Controls'],
['gry','Debug']
]
Sch_Table['com'][sLay] =
[
'SHIFT + Drag LMB = Band-box Select',
'CTRL + LMB on Merc = Add Merc to Selection',
'SHIFT + Arrow Keys = Scroll Faster',
'DELETE + \'-\' or \'+\' = Decrease\Increase Cover Distance',
'HOME + \'-\' or \'+\' = Decrease\Increase Line of Sight Information',
'ALT + W = Progressive Scroll Through Item List',
'ALT + SHIFT + W = Progressive Scroll Backwards'
]
Sch_Table['mou'][sLay] = []
Sch_Table['joy'][sLay] = []
Sch_Table['add'][sLay] = []
