sLay = 'ATUS104'
Sch_Table['gam'][sLay] = 'Space Rangers 2 (RTS)'
Sch_Table['aut'][sLay] = ''
Sch_Table['key'][sLay] =
[
,
,
['yel','Select\nGroup',,'Assign',,,,],
['yel','Select\nGroup',,'Assign',,,,],
['yel','Select\nGroup',,'Assign',,,,],
['yel','Select\nGroup',,'Assign',,,,],
['yel','Select\nGroup',,'Assign',,,,],
['yel','Select\nGroup',,'Assign',,,,],
['yel','Select\nGroup',,'Assign',,,,],
['yel','Select\nGroup',,'Assign',,,,],
['yel','Select\nGroup',,'Assign',,,,],
['yel','Select\nGroup',,'Assign',,,,],
['mag','Zoom\nMap -',,,,,,],
['mag','Zoom\nMap +',,,,,,],
,
,
,
,
['red','Explode',,,,,,],
['red','Repair',,,,,,],
,
,
['red','Auto\nAttack',,,,,,],
,
,
['red','Patrol',,,,,,],
['blu','Turn Left',,,,,,],
['blu','Turn Right',,,,,,],
['blu','Default\nCamera',,,,,,],
,
['red','Attack',,,,,,],
['red','Stop',,,,,,],
['red','Auto\nDefense',,,,,,],
,
,
,
,
['red','Capture',,,,,,],
,
,
,
,
['mag','Toggle Manual Control',,,,,,],
,
,
,
,
['red','Auto\nCapture',,,,,,],
,
,
,
['red','Move',,,,,,],
['yel','Cycle\nUnits -',,,,,,],
['yel','Cycle\nUnits +',,,,,,],
,
,
,
,
['mag','Toggle Manual Control',,,,,,],
,
,
,
,
['blu','Pan/Move\nLeft',,,,,,],
['blu','Turn\nLeft',,,,,,],
['blu','Turn\nRight',,,,,,],
['blu','Pan/Move\nAhead',,,,,,],
['blu','Pan/Move\nBack',,,,,,],
['blu','Tilt\nUp',,,,,,],
['blu','Tilt\nDown',,,,,,],
['blu','Pan/Move\nRight',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
['mag','Game\nMenu',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
['mag','Pause\nGame',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,

]
Sch_Table['leg'][sLay] =
[
['red','Actions'],
['yel','Selection'],
['blu','Camera'],
['mag','Game Controls']
]
Sch_Table['com'][sLay] = []
Sch_Table['mou'][sLay] = []
Sch_Table['joy'][sLay] = []
Sch_Table['add'][sLay] = []
sLay = 'ATUS104DVO'
Sch_Table['gam'][sLay] = Sch_Table['gam']['ATUS104']
Sch_Table['aut'][sLay] = Sch_Table['aut']['ATUS104']
Sch_Table['key'][sLay] = Sch_Table['key']['ATUS104']
Sch_Table['leg'][sLay] = Sch_Table['leg']['ATUS104']
Sch_Table['com'][sLay] = Sch_Table['com']['ATUS104']
Sch_Table['mou'][sLay] = Sch_Table['mou']['ATUS104']
Sch_Table['joy'][sLay] = Sch_Table['joy']['ATUS104']
Sch_Table['add'][sLay] = Sch_Table['add']['ATUS104']
