sLay = 'ATUS104'
Sch_Table['gam'][sLay] = 'Star Wolves & Star Wolves 2'
Sch_Table['aut'][sLay] = ''
Sch_Table['key'][sLay] =
[
,
,
['yel','Select\nSquad','Select\nHigh-\nlighted',,,,,],
['yel','Select\nSquad','Select\nHigh-\nlighted',,,,,],
['yel','Select\nSquad','Select\nHigh-\nlighted',,,,,],
['yel','Select\nSquad','Select\nHigh-\nlighted',,,,,],
['yel','Select\nSquad','Select\nHigh-\nlighted',,,,,],
['yel','Select\nSquad','Select\nHigh-\nlighted',,,,,],
,                     
,
,
,
['blu','Zoom Out',,,,,,],
['blu','Zoom In',,,,,,],
['mag','Galaxy Map',,,,,,],
['mag','System Map',,,,,,],
['mag','Quest Log',,,,,,],
,
['grn','Escort',,,,,,],
['red','Missile\nAttack',,,,,,],
,
,
,
,
,
,
['mag','Game\nSpeed -',,,,,,],
['mag','Game\nSpeed +',,,,,,],
,
['mag','Toggle\nHeight Indicators',,,,,,],
['red','Attack',,'Slect\nAll',,,,],
['grn','Stop',,,,,,],
['grn','Dock Ship',,,,,,],
['blu','Toggle\nFree\nCamera',,,,,,],
['blu','Cycle\nCamera\nModes',,,,,,],
['mag','Toggle\nHelpers',,,,,,],
,
,
['mag','Message\nLog',,,,,,],
,
,
,
,
,
,
['grn','Dock\nAll Ships',,'Launch All',,,,],
['mag','Special\nMoves',,,,,,],
['grn','Hold\nPosition',,,,,,],
['mag','Cycle\nRadars',,,,,,],
['mag','Mothership\n/ Hangar',,,,,,],
,
['grn','Move Ship',,,,,,],
['mag','Hide\nContacts',,,,,,],
['mag','Show\nContacts',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
['yel','Deselect /\nGame Menu',,,,,,],
['mag','Help',,,,,,],
,
,
,
['mag','Quick\nSave',,,,,,],
,
,
['mag','Quick\nLoad',,,,,,],
['blu','Free\nCamera',,,,,,],
['blu','View\nCamera',,,,,,],
['blu','Chase\nCamera',,,,,,],
['blu','Follow\nCamera',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,

]
Sch_Table['leg'][sLay] =
[
['grn','Movement'],
['yel','Selection'],
['red','Combat'],
['blu','Camera'],
['mag','Game Controls']
]
Sch_Table['com'][sLay] =
[
'Alt + Left Click: Focus on object',
'Left Click + Right Click + Move Mouse: Zoom in/out',
'CTRL + Left Click: Attack',
'Shift + Right Click + Move Mouse: Vertical movement',
'Shift + Left Click: Select highlighted squads'
]
Sch_Table['mou'][sLay] =
[
'Left Click: Select ships',
'Right Click: Default action',
'Double-Click: Fous on object',
'Mousewheel: Zoom in/out'
]
Sch_Table['joy'][sLay] = []
Sch_Table['add'][sLay] = []
sLay = 'ATUS104DVO'
Sch_Table['gam'][sLay] = Sch_Table['gam']['ATUS104']
Sch_Table['aut'][sLay] = Sch_Table['aut']['ATUS104']
Sch_Table['key'][sLay] = Sch_Table['key']['ATUS104']
Sch_Table['leg'][sLay] = Sch_Table['leg']['ATUS104']
Sch_Table['com'][sLay] = Sch_Table['com']['ATUS104']
Sch_Table['mou'][sLay] = Sch_Table['mou']['ATUS104']
Sch_Table['joy'][sLay] = Sch_Table['joy']['ATUS104']
Sch_Table['add'][sLay] = Sch_Table['add']['ATUS104']
