<?php
	// Video Game Keyboard Diagrams
	// Copyright (C) 2018  Michael Horvath
        // 
	// This file is part of Video Game Keyboard Diagrams.
        // 
	// This program is free software: you can redistribute it and/or modify
	// it under the terms of the GNU Lesser General Public License as 
	// published by the Free Software Foundation, either version 3 of the 
	// License, or (at your option) any later version.
        // 
	// This program is distributed in the hope that it will be useful, but 
	// WITHOUT ANY WARRANTY; without even the implied warranty of 
	// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU 
	// Lesser General Public License for more details.
        // 
	// You should have received a copy of the GNU Lesser General Public 
	// License along with this program.  If not, see 
	// <https://www.gnu.org/licenses/>.

	function gatherURLParameters()
	{
		global $game_seo, $game_id, $style_id, $layout_id, $format_id, $svg_bool, $ten_bool;
		$game_seo	= array_key_exists("seo", $_GET) ? $_GET["seo"]				: null;	// generated by htaccess if missing
		$game_id	= array_key_exists("gam", $_GET) ? intval(ltrim($_GET["gam"], "0"))	: null;	// obsolete
		$style_id	= array_key_exists("sty", $_GET) ? intval(ltrim($_GET["sty"], "0"))	: null;
		$layout_id	= array_key_exists("lay", $_GET) ? intval(ltrim($_GET["lay"], "0"))	: null;
		$format_id	= array_key_exists("fmt", $_GET) ? intval(ltrim($_GET["fmt"], "0"))	: null;
		$svg_bool	= array_key_exists("svg", $_GET) ? intval(ltrim($_GET["svg"], "0"))	: null;	// obsolete
		$ten_bool	= array_key_exists("ten", $_GET) ? intval(ltrim($_GET["ten"], "0"))	: null;
	}
	function checkURLParameters($code_format)
	{
		global $fix_url, $game_seo, $game_id, $style_id, $layout_id, $format_id, $svg_bool, $ten_bool;
//		error_log("checking URL query validity", 0);
		if ($game_id === null)
		{
			if ($game_seo !== null)
			{
				if ($code_format == "html")
					selGamesHTML_SEO();
				else if ($code_format == "svg")
					selGamesSVG_SEO();
			}
			else
			{
				$game_id = 1;
				$game_seo = "test-sample";
			}
//			$fix_url = true;	// obsolete
//			error_log("game_id is null", 0);
		}
		if ($game_seo === null)
		{
			if ($game_id !== null)
			{
				if ($code_format == "html")
					selGamesHTML_ID();
				else if ($code_format == "svg")
					selGamesSVG_ID();
			}
			else
			{
				$game_id = 1;
				$game_seo = "test-sample";
			}
			$fix_url = true;
//			error_log("game_seo is null", 0);
		}
		if ($style_id === null)
		{
			$style_id = 15;
			$fix_url = true;
//			error_log("style_id is null", 0);
		}
		if ($layout_id === null)
		{
			$layout_id = 1;
			$fix_url = true;
//			error_log("layout_id is null", 0);
		}
		if ($format_id === null)
		{
			if ($svg_bool !== null)
			{
				$format_id = $svg_bool;
			}
			else
			{
				$format_id = 1;
				$svg_bool = 1;
			}
			$fix_url = true;
//			error_log("format_id is null", 0);
		}
		if ($svg_bool === null)
		{
			$svg_bool = 0;
//			$fix_url = true;		// obsolete
//			error_log("svg_bool is null", 0);
		}
		if ($ten_bool === null)
		{
			$ten_bool = 1;
			$fix_url = true;
//			error_log("ten_bool is null", 0);
		}
	}

	// there is an analogous function written in JavaScript in "keyboard-submit-js.php"
	// need to keep the two functions synced
	function seo_url($input)
	{
		$input = mb_convert_case($input, MB_CASE_LOWER, "UTF-8");	//convert to lowercase
		$input = str_replace(array("'", "\""), "", $input);		//remove single and double quotes
		$input = preg_replace("/[^a-zA-Z0-9]+/", "-", $input);		//replace everything non-alphanumeric with dashes
		$input = preg_replace("/\-+/", "-", $input);			//replace multiple dashes with one dash
		$input = trim($input, "-");					//trim dashes from the beginning and end of the string if any
		return $input;
	}
	function getPlatformID($in_layout_id)
	{
		global $layout_array;
		for ($i = 0; $i < count($layout_array); $i++)
		{
			$layout_id = $layout_array[$i][0];
			$platform_id = $layout_array[$i][2];
			if ($in_layout_id == $layout_id)
			{
				return $platform_id;
			}
		}
	}
	function getLayoutName($in_layout_id)
	{
		global $layout_array;
		for ($i = 0; $i < count($layout_array); $i++)
		{
			$layout_id = $layout_array[$i][0];
			$layout_name = $layout_array[$i][1];
			if ($in_layout_id == $layout_id)
			{
				return $layout_name;
			}
		}
	}
	// is this still needed?
	function print_key_html($in_id, $in_class, $in_color, $in_value)
	{
		echo
"								<div id=\"" . $in_id . "\" class=\"" . $in_class . "\">" . cleantextHTML($in_value) . "</div>\n";
	}
	function cleantextHTML($instring)
	{
		return str_replace("\\t","\t",str_replace("\\r","",str_replace("\\n","<br/>",str_replace("\r","",str_replace("\n","",str_replace("<","&lt;",str_replace(">","&gt;",str_replace("\"","&quot;",str_replace("'","&#39;",str_replace("&","&amp;",$instring))))))))));
	}
	function cleantextSVG($instring)
	{
		return str_replace("\\t","\t",str_replace("\\r","",str_replace("\\n","\n",str_replace("\r","",str_replace("\n","",str_replace("<","&lt;",str_replace(">","&gt;",str_replace("\"","&quot;",str_replace("'","&#39;",str_replace("&","&amp;",$instring))))))))));
	}
	function cleantextJS($instring)
	{
		return str_replace("\"","\\\"",str_replace("\\","\\\\",$instring));
	}
	function cleantextWiki($instring)
	{
		return str_replace("\\t","\t",str_replace("\\n","&lt;br/&gt;",str_replace("&","&amp;",$instring)));
	}
	function splittext($instring)
	{
		return array_filter(explode("\n", $instring));
	}
	function getcolor($group)
	{
		// hardcoded! should fetch from database instead
		$color_array = ["red","yel","grn","cyn","blu","mag","wht","gry","blk","org","olv","brn"];
		return array_key_exists($group-1, $color_array) ? $color_array[$group-1] : "non";
	}
	function getkeyclass($group)
	{
		// hardcoded! should fetch from database instead
		$class_array = ["cssA","cssB","cssC","cssD","cssE","cssF","cssG","cssH","cssI","cssJ","cssK","cssL"];
		return array_key_exists($group-1, $class_array) ? $class_array[$group-1] : "";

	}
	function getAuthorName($in_author_id)
	{
		global $author_table;
		for ($i = 0; $i < count($author_table); $i++)
		{
			$author_id = $author_table[$i][0];
			$author_name = $author_table[$i][1];
			if ($author_id == $in_author_id)
			{
				return $author_name;
			}
		}
	}
	function leadingZeros3($innumber)
	{
		$outstring = strval($innumber);
		if ($innumber < 10)
		{
			$outstring = "0" . $outstring;
		}
		if ($innumber < 100)
		{
			$outstring = "0" . $outstring;
		}
		return $outstring;
	}
	function leadingZeros2($innumber)
	{
		$outstring = strval($innumber);
		if ($innumber < 10)
		{
			$outstring = "0" . $outstring;
		}
		return $outstring;
	}
	function checkStyle($in_style_id)
	{
		global $style_table;
		for ($i = 0; $i < count($style_table); $i++)
		{
			$style_box = $style_table[$i];
			for ($j = 0; $j < count($style_box); $j++)
			{
				if ($style_box[$j][0] == $in_style_id)
				{
					return true;
				}
			}
		}
		return false;
	}
	function checkLayout($in_layout_id)
	{
	}
	// outputs e.g.  somefile.txt was last modified: December 29 2002 22:16:23.
	function getFileTime($in_file)
	{
		if (file_exists($in_file))
		{
			return "Last modified: " . date ("F d Y H:i:s.", filemtime($in_file));
		}
		else
		{
			return "Last modified: File does not exist.";
		}
	}
	function sortGames()
	{
		global $genre_order_array, $genre_array, $game_array;
		array_multisort($genre_order_array, $genre_array, $game_array);
	}
	function sortGamesFront()
	{
		global $genre_array, $game_array;
		array_multisort($genre_array, SORT_ASC|SORT_NATURAL|SORT_FLAG_CASE, $game_array);
	}

	// forgot what this is used for
	// should probably be moved to the database and localized
	$word_part1 = ["keyboard","video game","software","printable","graphical","visual"];
	$word_part2 = ["shortcut","binding","control","hotkey","command"];
	$word_part3 = ["diagram","chart","overlay","database","reference","guide","list","map"];

	function checkForErrors()
	{
		global $errors_table,
			$game_seo, $game_name, $platform_name, $layout_name, $style_name,
			$temp_game_seo, $temp_game_name, $temp_platform_name, $temp_layout_name, $temp_style_name,
			$layout_id, $style_id, $gamesrecord_id, $stylesrecord_id;
		$temp_game_seo		= $game_seo		? $game_seo		: "unrecognized-game";
		$temp_game_name		= $game_name		? $game_name		: "Unrecognized Game";
		$temp_platform_name	= $platform_name	? $platform_name	: "Unrecognized Platform";
		$temp_layout_name	= $layout_name		? $layout_name		: "Unrecognized Layout";
		$temp_style_name	= $style_name		? $style_name		: "Unrecognized Theme";
		if (!$layout_name)
		{
			$errors_table[] = "Layout with ID number " . $layout_id . " not found.";
		}
		if (!$style_name)
		{
			$errors_table[] = "Theme with ID number " . $style_id . " not found.";
		}
		if (!$gamesrecord_id)
		{
			$errors_table[] = "No bindings found for game \"" . $temp_game_name . "\" on layout \"" . $temp_layout_name . "\".";
		}
		if (!$stylesrecord_id)
		{
			$errors_table[] = "No configurations found for theme \"" . $temp_style_name . "\" on layout \"" . $temp_layout_name . "\".";
		}
	}
?>
