<?php
	// Video Game Keyboard Diagrams
	// Copyright (C) 2018  Michael Horvath
        // 
	// This file is part of Video Game Keyboard Diagrams.
        // 
	// This program is free software: you can redistribute it and/or modify
	// it under the terms of the GNU Lesser General Public License as 
	// published by the Free Software Foundation, either version 3 of the 
	// License, or (at your option) any later version.
        // 
	// This program is distributed in the hope that it will be useful, but 
	// WITHOUT ANY WARRANTY; without even the implied warranty of 
	// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU 
	// Lesser General Public License for more details.
        // 
	// You should have received a copy of the GNU Lesser General Public 
	// License along with this program.  If not, see 
	// <https://www.gnu.org/licenses/>.

	$php_url		= "";
	$svg_url		= "";
	$can_url		= "";
	$default_game_id	= 0;
	$default_style_id	= 0;
	$default_layout_id	= 0;
	$default_format_id	= 0;
	$default_svg_bool	= 0;
	$default_ten_bool	= 1;
	$default_game_seo	= "";
	$default_game_name	= "";
	$default_style_name	= "";
	$default_layout_name	= "";
	$default_format_name	= "";
	$color_array		= [];
	$class_array		= [];
	$urlqueries_array	= [];
	$language_code		= "";
	$language_title		= "";
	$language_description	= "";
	$language_keywords	= "";
	$language_legend	= "";
	$temp_game_seo		= "";
	$temp_game_name		= "";
	$temp_layout_name	= "";
	$temp_style_name	= "";
	$temp_platform_name	= "";
	$temp_format_name	= "";
	$temp_separator		= "";
	$page_title_a		= "";
	$page_title_b		= "";
	$layout_language	= 1;	// temporary until more text gets localized

	// from https://www.php.net/manual/en/function.pathinfo.php
	function extension($path)
	{
		$qpos = strpos($path, "?");
		if ($qpos!==false) $path = substr($path, 0, $qpos);
		$extension = pathinfo($path, PATHINFO_EXTENSION);
		return $extension;
	}
	function checkURLParameters()
	{
		global	$php_url, $svg_url, $can_url, $url_ext,
			$game_seo,	$default_game_seo,
			$game_id,	$default_game_id,
			$game_name,	$default_game_name,
			$style_id,	$default_style_id,
			$style_name,	$default_style_name,
			$layout_id,	$default_layout_id,
			$layout_name,	$default_layout_name,
			$format_id,	$default_format_id,
			$format_name,	$default_format_name,
			$svg_bool,	$default_svg_bool,
			$ten_bool,	$default_ten_bool;
//		error_log("checking URL query validity", 0);
		$game_seo	= array_key_exists("seo", $_GET) ? $_GET["seo"]				: null;	// generated by htaccess if missing
		$game_id	= array_key_exists("gam", $_GET) ? intval(ltrim($_GET["gam"], "0"))	: null;	// obsolete parameter kept so old links don't break
		$style_id	= array_key_exists("sty", $_GET) ? intval(ltrim($_GET["sty"], "0"))	: null;
		$layout_id	= array_key_exists("lay", $_GET) ? intval(ltrim($_GET["lay"], "0"))	: null;
		$format_id	= array_key_exists("fmt", $_GET) ? intval(ltrim($_GET["fmt"], "0"))	: null;
		$svg_bool	= array_key_exists("svg", $_GET) ? intval(ltrim($_GET["svg"], "0"))	: null;	// obsolete parameter kept so old links don't break
		$ten_bool	= array_key_exists("ten", $_GET) ? intval(ltrim($_GET["ten"], "0"))	: null;
		$fix_url	= false;

		if ($url_ext == "svg")
		{
			if ($format_id != 1)
			{
				$fix_url = true;
			}
		}
		if ($format_id == 1)
		{
			if ($url_ext != "svg")
			{
				$fix_url = true;
			}
		}
		if ($game_id === null)
		{
//			error_log("game_id is null", 0);
			if ($game_seo !== null)
			{
				selThisGameSEOChart();
			}
			else
			{
//				error_log("game_seo is null", 0);
				$game_seo = $default_game_seo;
				$game_id = $default_game_id;
				$game_name = $default_game_name;
			}
//			$fix_url = true;	// don't uncomment this!
		}
		if ($game_seo === null)
		{
//			error_log("game_seo is null", 0);
			if ($game_id !== null)
			{
				selThisGamesIDChart();
			}
			else
			{
//				error_log("game_id is null", 0);
				$game_seo = $default_game_seo;
				$game_id = $default_game_id;
				$game_name = $default_game_name;
			}
			$fix_url = true;
		}
		if ($style_id === null)
		{
//			error_log("style_id is null", 0);
			$style_id = $default_style_id;
			$style_name = $default_style_name;
			$fix_url = true;
		}
		if ($layout_id === null)
		{
//			error_log("layout_id is null", 0);
			$layout_id = $default_layout_id;
			$layout_name = $default_layout_name;
			$fix_url = true;
		}
		if ($format_id === null)
		{
//			error_log("format_id is null", 0);
			if ($url_ext == "svg")
			{
				$format_id = 1;
				// what should I do here?
//				$format_name = ???;
			}
			else if ($svg_bool !== null)
			{
				$format_id = $svg_bool;
				// what should I do here?
//				$format_name = ???;
			}
			else
			{
//				error_log("svg_bool is null", 0);
				$format_id = $default_format_id;
				$format_name = $default_format_name;
				$svg_bool = $default_svg_bool;
			}
			$fix_url = true;
		}
		if ($svg_bool === null)
		{
//			error_log("svg_bool is null", 0);
			$svg_bool = $default_svg_bool;
//			$fix_url = true;	// don't uncomment this!
		}
		if ($ten_bool === null)
		{
//			error_log("ten_bool is null", 0);
			$ten_bool = $default_ten_bool;
			$fix_url = true;
		}

		$php_url = "keyboard-diagram-" . $game_seo . ".php?sty=" . $style_id . "&lay=" . $layout_id . "&fmt=" . $format_id	. "&ten=" . $ten_bool;
		$svg_url = "keyboard-diagram-" . $game_seo . ".svg?sty=" . $style_id . "&lay=" . $layout_id . "&fmt=" . 1		. "&ten=" . $ten_bool;
		$can_url = "http://isometricland.net/keyboard/" . $php_url;

		if ($fix_url === true)
		{
			if ($format_id == 1)
				header("Location: " . $svg_url);
			else
				header("Location: " . $php_url);
			die();
		}
	}
	function pageTitle()
	{
		global	$page_title_a, $page_title_b, $language_title, $gamesrecord_id,
			$temp_separator, $temp_game_name, $temp_platform_name, $temp_layout_name, $temp_style_name, $temp_format_name;
		$temp_separator	= " - ";
		$page_title_a	= $temp_game_name;
		$page_title_b	= $language_title . $temp_separator . $temp_platform_name . $temp_separator . $temp_layout_name . $temp_separator . $temp_style_name . $temp_separator . $temp_format_name . $temp_separator . "GRID:" . $gamesrecord_id;
	}
	// there is an analogous function written in JavaScript in "keyboard-submit.js"
	// need to keep the two functions synced
	function seo_url($input)
	{
		$input = mb_convert_case($input, MB_CASE_LOWER, "UTF-8");	//convert to lowercase
		$input = str_replace(array("'", "\""), "", $input);		//remove single and double quotes
		$input = preg_replace("/[^a-zA-Z0-9]+/", "-", $input);		//replace everything non-alphanumeric with dashes
		$input = preg_replace("/\-+/", "-", $input);			//replace multiple dashes with one dash
		$input = trim($input, "-");					//trim dashes from the beginning and end of the string if any
		return $input;
	}
	function getPlatformID($in_layout_id)
	{
		global $layout_table;
		foreach ($layout_table as $i => $layout_value)
		{
			// note these are local variables
			$layout_id   = $layout_value[0];
			$platform_id = $layout_value[2];
			if ($layout_id == $in_layout_id)
			{
				return $platform_id;
			}
		}
	}
	function getLayoutName($in_layout_id)
	{
		global $layout_table;
		foreach ($layout_table as $i => $layout_value)
		{
			// note these are local variables
			$layout_id	= $layout_value[0];
			$layout_name	= $layout_value[1];
			if ($layout_id == $in_layout_id)
			{
				return $layout_name;
			}
		}
	}
	function getGenreName($in_genre_id)
	{
		global $genre_table;
		foreach ($genre_table as $i => $genre_value)
		{
			// note these are local variables
			$genre_id	= $genre_value[0];
			$genre_name	= $genre_value[1];
			if ($genre_id == $in_genre_id)
			{
				return $genre_name;
			}
		}
	}
	function getStyleName($in_style_id)
	{
		global $style_table;
		for ($i = 0; $i < count($style_table); $i++)
		{
			$style_box = $style_table[$i];
			for ($j = 0; $j < count($style_box); $j++)
			{
				// note these are local variables
				$style_id = $style_box[$j][0];
				$style_name = $style_box[$j][1];
				if ($style_id == $in_style_id)
				{
					return $style_name;
				}
			}
		}
	}
	function getGameName($in_game_id)
	{
	}
	function getAuthorName($in_author_id)
	{
		global $author_table;
		for ($i = 0; $i < count($author_table); $i++)
		{
			// note these are local variables
			$author_id = $author_table[$i][0];
			$author_name = $author_table[$i][1];
			if ($author_id == $in_author_id)
			{
				return $author_name;
			}
		}
	}
	// need a version of this function for "keyboard-svg.php"
	function print_key_html($in_id, $in_class, $in_color, $in_value)
	{
		echo
"								<div id=\"" . $in_id . "\" class=\"" . $in_class . "\">" . cleantextHTML($in_value) . "</div>\n";
	}
	// there must be some easier way to do this using native PHP functions!
	function cleantextHTML($instring)
	{
		return str_replace("\\t","\t",str_replace("\\r","",str_replace("\\n","<br/>",str_replace("\r","",str_replace("\n","",str_replace("<","&lt;",str_replace(">","&gt;",str_replace("\"","&quot;",str_replace("'","&#39;",str_replace("&","&amp;",$instring))))))))));
	}
	function cleantextSVG($instring)
	{
		return str_replace("\\t","\t",str_replace("\\r","",str_replace("\\n","\n",str_replace("\r","",str_replace("\n","",str_replace("<","&lt;",str_replace(">","&gt;",str_replace("\"","&quot;",str_replace("'","&#39;",str_replace("&","&amp;",$instring))))))))));
	}
	function cleantextJS($instring)
	{
		return str_replace("'","\\'",str_replace("\\","\\\\",$instring));
	}
	function cleantextWiki($instring)
	{
		return str_replace("\\t","\t",str_replace("\\n","&lt;br/&gt;",str_replace("&","&amp;",$instring)));
	}
	function splittext($instring)
	{
		return array_filter(explode("\n", $instring));
	}
	function getkeycolor($group)
	{
		global $color_array;
		return array_key_exists($group-1, $color_array) ? $color_array[$group-1] : "non";
	}
	function getkeyclass($group)
	{
		global $class_array;
		return array_key_exists($group-1, $class_array) ? $class_array[$group-1] : "";
	}
	function leadingZeros($innumber, $level)
	{
		return str_pad($innumber, $level, "0", STR_PAD_LEFT);
	}
	function testPathInfo()
	{
		global $path_lib2, $path_file;
//		$path_parts = pathinfo($_SERVER["REQUEST_URI"]);
//		$path_parts = pathinfo(__FILE__);
		$path_parts = pathinfo($path_lib2 . $path_file);
		echo $path_parts["dirname"],	"<br>";
		echo $path_parts["basename"],	"<br>";
		echo $path_parts["extension"],	"<br>";
		echo $path_parts["filename"],	"<br>";	// since PHP 5.2.0
	}
	function getFileTime()
	{
		global $path_lib2, $path_file;
		$in_file = $path_lib2 . $path_file;
		$path_parts = pathinfo($in_file);
		$base_name = $path_parts["basename"];
		if (file_exists($in_file))
		{
			return "Page: " . $base_name . ". Last modified: " . date("F d Y H:i:s.", filemtime($in_file));
		}
		else
		{
			return "Page: " . $base_name . ". Last modified: File does not exist.";
		}
	}
	function checkForErrors()
	{
		global	$errors_table, $gamesrecord_id, $stylesrecord_id,
			$game_seo,	$temp_game_seo,
			$game_name,	$temp_game_name,	$game_id,
			$platform_name,	$temp_platform_name,	$platform_id,
			$layout_name,	$temp_layout_name,	$layout_id,
			$style_name,	$temp_style_name,	$style_id,
			$format_name,	$temp_format_name,	$format_id;
		$temp_game_seo		= $game_seo		? $game_seo		: "unrecognized-game";		// needs to be low caps
		$temp_game_name		= $game_name		? $game_name		: "Unrecognized Game";
		$temp_platform_name	= $platform_name	? $platform_name	: "Unrecognized Platform";
		$temp_layout_name	= $layout_name		? $layout_name		: "Unrecognized Layout";
		$temp_style_name	= $style_name		? $style_name		: "Unrecognized Style";
		$temp_format_name	= $format_name		? $format_name		: "Unrecognized Format";
		// checking for $game_id or $game_name  isn't working right now
		// should check for $format_id and $format_name too
		// should check that $ten_bool is in the correct range too
		if (!$game_name)
		{
			$errors_table[] = "Game with ID number " . $game_id . " not found.";
		}
		if (!$layout_name)
		{
			$errors_table[] = "Layout with ID number " . $layout_id . " not found.";
		}
		if (!$style_name)
		{
			$errors_table[] = "Style with ID number " . $style_id . " not found.";
		}
		if (!$gamesrecord_id)
		{
			$errors_table[] = "No bindings found for game \"" . $temp_game_name . "\" and layout \"" . $temp_layout_name . "\".";
		}
		if (!$stylesrecord_id)
		{
			$errors_table[] = "No configurations found for style \"" . $temp_style_name . "\" and layout \"" . $temp_layout_name . "\".";
		}
	}
	function usortByMember1($a, $b)
	{
		return strnatcmp($a[1], $b[1]);
	}
	function usortByMember2($a, $b)
	{
		return strnatcmp($a[2], $b[2]);
	}
?>
