sLay = 'ATUS104'
Gam_Table['gam'][sLay] = 'Brigade E5: New Jagged Union'
Gam_Table['aut'][sLay] = ''
Gam_Table['key'][sLay] =
[
,
,
['yel','Select\nSoldier',,,,,,],
['yel','Select\nSoldier',,,,,,],
['yel','Select\nSoldier',,,,,,],
['yel','Select\nSoldier',,,,,,],
['yel','Select\nSoldier',,,,,,],
['yel','Select\nSoldier',,,,,,],
,
,
,
['yel','Select\nAll',,,,,,],
['mag','TC -',,,,,,],
['mag','TC +',,,,,,],
['red','Cancel Orders',,,,,,],
['yel','Next\nSoldier',,,,,,],
,
['blu','Toggle\nLevel Mode',,,,,,],
['blu','Toggle\nFP View',,,,,,],
['grn','Run',,,,,,],
,
,
,
['mag','Inventory',,,,,,],
,
['grn','Walk with\nWeapon\nDrawn',,,,,,],
['red','Cycle Fire\nModes -',,,,,,],
['red','Cycle Fire\nModes +',,,,,,],
['red','Aim at Cursor',,,,,,],
,
['red','Attack\nNeutral\nPerson',,,,,,],
['grn','Stand\nUp',,,,,,],
['red','Drop\nItem',,,,,,],
['blu','Toggle\nView/Fire\nZones',,,,,,],
['red','Scan\nGround',,,,,,],
,
['red','Clear\nMisfire',,,,,,],
,
['grn','Lie\nProne',,,,,,],
['grn','Fast\nRun',,,,,,],
,
,
,
['blu','Fast Camera',,,,,,],
,
['mag','Record\nActions',,,,,,],
['red','Ready\nWeapon',,,,,,],
,
['mag','Cancel\nPause',,,,,,],
['mag','Force\nPause',,,,,,],
,
['mag','Strategic\nMap',,,,,,],
,
,
,
['blu','Fast Camera',,,,,,],
['red','Perform Action',,,,,,],
['red','Group Action',,,,,,],
['mag','Pause/Resume Game',,,,,,],
['red','Group Action',,,,,,],
['red','Perform Action',,,,,,],
['blu','Raise\nLevel',,,,,,],
['blu','Lower\nLevel',,,,,,],
['blu','Pan\nLeft',,,,,,],
['blu','Raise\nCamera',,,,,,],
['blu','Lower\nCamera',,,,,,],
['blu','Pan\nUp',,,,,,],
['blu','Pan\nDown',,,,,,],
,
,
['blu','Pan\nRight',,,,,,],
,
['red','Snap\nShot',,,,,,],
['red','Rough\nShot',,,,,,],
['red','Aimed\nShot',,,,,,],
,
['red','Snap\nBurst',,,,,,],
['red','Rough\nBurst',,,,,,],
['red','Aimed\nBurst',,,,,,],
,
,
['red','Snap\nAuto',,,,,,],
['red','Rough\nAuto',,,,,,],
['red','Aimed\nAuto',,,,,,],
,
,
,
,
,
,
,
,
,
['mag','Quick\nSave',,,,,,],
['mag','Save\nScreen',,,,,,],
,
['mag','Screenshot',,,,,,],
['mag','Quick\nLoad',,,,,,],
['mag','Load\nScreen',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,

]
Gam_Table['leg'][sLay] =
[
['red','Combat/Actions'],
['grn','Movement'],
['yel','Selection'],
['blu','Camera'],
['mag','Game Controls']
]
Gam_Table['com'][sLay] = []
Gam_Table['mou'][sLay] = []
Gam_Table['joy'][sLay] = []
Gam_Table['add'][sLay] = []
