sLay = 'ATUS104'
Gam_Table['gam'][sLay] = 'FreeSpace'
Gam_Table['aut'][sLay] = ''
Gam_Table['key'][sLay] =
[
,
,
,
,
,
,
,
,
,
,
,
,
['grn','Throttle\nDown 5%',,,,,,],
['grn','Throttle\nUp 5%',,,,,,],
['grn','Zero Throttle',,,,,,],
['grn','Afterburner',,,,,,],
['mag','Equalize\nShields',,,,,,],
[,,'Form on\nWing',,,,,],
['yel','Target\nEscort','Engage\nEnemy',,'Add/Sub\nto Escort',,,],
['yel','Attacker\nof Self','Rearm',,'Target\nRepair',,,],
['yel','Target\nNext Ship','Prev',,,,,],
['yel','Ship in\nReticle',,,'Target\nSender',,,],
,
[,,'Ignore\nTarget',,,,,],
,
[,,'Protect\nTarget',,,,,],
['grn','Throttle\nto 1/3',,,,,,],
['grn','Throttle\nto 2/3',,,,,,],
['grn','Full Throttle',,,,,,],
,
['grn','Accelerate','Attack\nTarget',,,,,],
['yel','Next\nSubsys','Prev',,'Cease\nTar-\ngeting',,,],
[,,'Disable\nTarget',,'Equalize\nEnergy',,,],
['yel','Next\nFriendly','Prev',,,,,],
['yel','Attacker\nof Target',,,,,,],
['yel','Next\nHostile','Prev',,'Auto\nTar-\ngeting',,,],
[,,'Return\nto Base',,'Jump/End',,,],
['yel','Next\nTurret',,,'Prev',,,],
,
,
,
,
,
,
,
['grn','Decelerate','Disarm\nTarget',,,,,],
['red','Counter-\nmeasures','Capture\nTarget',,,,,],
['cyn','Comms\nMenu','Cover\nMe',,,,,],
['yel','Subsys\nin Reticle','Attack\nSubsys',,,,,],
['yel','Next\nBomb','Prev',,,,,],
,
['grn','Match\nSpeed',,,'Auto\nMatch',,,],
['red','Cycle\nPrimary\nBackward','TC -',,,,,],
['red','Cycle\nPrimary\nForward','TC +',,,,,],
['red','Cycle\nSecondary','Toggle\nDual Fire',,,,,],
,
['red','Fire Primary',,,,,,],
,
['red','Fire Secondary',,,,,,],
,
,
['red','Increase\nWeapon\nRecharge',,,,,,],
['red','Decrease\nWeapon\nRecharge',,,,,,],
['red','Augment\nLeft\nShield',,,,,,],
['red','Increase\nShield\nRecharge',,,,,,],
['red','Decrease\nShield\nRecharge',,,,,,],
['red','Augment\nForward\nShield',,,,,,],
['red','Augment\nRear\nShield',,,,,,],
['red','Increase\nEngine\nRecharge',,,,,,],
['red','Decrease\nEngine\nRecharge',,,,,,],
['red','Augment\nRight\nShield',,,,,,],
,
['grn','Bank\nLeft',,,,,,],
['grn','Nose\nLeft',,,,,,],
,
['blu','Target\nView',,,,,,],
['grn','Nose\nDown',,,,,,],
['blu','Center\nView',,,,,,],
['grn','Nose\nUp',,,,,,],
,
['blu','Chase\nView',,,,,,],
['grn','Bank\nRight',,,,,,],
['grn','Nose\nRight',,,,,,],
,
['blu','External\nView',,,,,,],
['blu','Decrease\nZoom',,,,,,],
['blu','Increase\nZoom',,,,,,],
,
['mag','Game\nMenu',,,,,,],
['mag','Help',,,,,,],
['mag','Options',,,,,,],
['mag','Hotkey\nMenu',,,,,,],
['mag','Log',,,,,,],
['yel','Select\nHotkey','Add/Sub',,,,,],
['yel','Select\nHotkey','Add/Sub',,,,,],
['yel','Select\nHotkey','Add/Sub',,,,,],
['yel','Select\nHotkey','Add/Sub',,,,,],
['yel','Select\nHotkey','Add/Sub',,,,,],
['yel','Select\nHotkey','Add/Sub',,,,,],
['yel','Select\nHotkey','Add/Sub',,,,,],
['yel','Select\nHotkey','Add/Sub',,,,,],
['mag','Screenshot',,,,,,],
['red','Weapons\nto Shields','Shields to\nWeapons',,,,,],
['mag','Pause\nGame',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,

]
Gam_Table['leg'][sLay] =
[
['red','Weapons/Shields'],
['yel','Targeting'],
['grn','Navigation'],
['cyn','Communication'],
['blu','Camera'],
['mag','Game Controls']
]
Gam_Table['com'][sLay] =
[
'Clear Hotkey Set = Alt + Shift + F5 to F12',
'Clear Escort List = Alt + Shift + E'
]
Gam_Table['mou'][sLay] = []
Gam_Table['joy'][sLay] = []
Gam_Table['add'][sLay] = []
