sLay = 'ATUS104'
Gam_Table[sLay] = {}
Gam_Table[sLay]['nam'] = 'Vega Strike'
Gam_Table[sLay]['aut'] = 'Michael Horvath'
// norm_txt, norm_grp, shift_txt, shift_grp, ctrl_txt, ctrl_grp, alt_txt, alt_grp, altgr_txt, altgr_grp, extra_txt, extra_grp, image file, image uri
Gam_Table[sLay]['key'] =
[
	['Shelton\nSlide',2,'','','','','','','','','','','',''],
	['Toggle\nCockpit',4,'Self\nDestruct','','','','','','','','','','',''],
	['Look\nLeft',4,'','','','','','','','','','','',''],
	['Look\nRight',4,'','','','','','','','','','','',''],
	['Look\nBack',4,'','','','','','','','','','','',''],
	['Chase\nView',4,'','','','','','','','','','','',''],
	['Panning\nView',4,'','','','','','','','','','','',''],
	['Target\nView',4,'','','','','','','','','','','',''],
	['Target\nPanning\nView',4,'Roll\nRight','','','','','','','','','','',''],
	['TC -',5,'','','','','','','','','','','',''],
	['TC +',5,'','','','','Clear\nDock','','','','','','',''],
	['Decrease\nVelocity',2,'','','','','','','','','','','',''],
	['Increase\nVelocity',2,'','','','','','','','','','','',''],
	['Relative Stop',2,'','','','','','','','','','','',''],
	['Afterburner',2,'','','','','','','','','','','',''],
	['Pan Down',4,'','','','','','','','','','','',''],
	['Next\nSecondary\nWeapon',0,'Prev','','','','','','','','','','',''],
	['ECM',0,'','','','','Eject','','','','','','',''],
	['Next\nNear Target\n(Hostile)',1,'Toughest','','','','','','','','','','',''],
	['Next\nAll Target',1,'Prev','','','','','','','','','','',''],
	['Switch\nCombat\nMode',2,'','','','','','','','','','','',''],
	['Next\nManmade\nTarget',1,'Prev','','','','','','','','','','',''],
	['Screenshot',5,'','','','','','','','','','','',''],
	['Turret AI\nOn',0,'Auto','','','','Off','','','','','','',''],
	['Target in\nBoresight',1,'Turret\nTarget','','','','','','','','','','',''],
	['Change\nShip',1,'','','','','','','','','','','',''],
	['Text\nMessage',1,'','','','','','','','','','','',''],
	['Max Velocity',2,'Pause\nGame','','','','','','','','','','',''],
	null,
	['Autopilot',2,'SPEC','','','','','','','','','','',''],
	['Pan Left',4,'Skip Song','','','','','','','','','','',''],
	['Docking\nManeuver',2,'Attack\nTarget','','','','','','','','','','',''],
	['Pan Right',4,'Form Up','','','','','','','','','','',''],
	['Next\nPrimary\nWeapon',0,'Prev','','','','','','','','','','',''],
	['Next\nHostile\nTarget',1,'Prev','','','','Help\nMe','','','','','','',''],
	['Jump Drive',2,'','','','','','','','','','','',''],
	['Next Near\nTarget\n(Friend)',1,'Base','','Plant','','Jump','','','','','','',''],
	['Lock on\nTarget',1,'','','','','','','','','','','',''],
	['Respawn',5,'','','','','','','','','','','',''],
	null,
	null,
	['Fire Secondary',0,'','','','','','','','','','','',''],
	null,
	null,
	['Pan Up',4,'Jettison\nCargo','','','','','','','','','','',''],
	null,
	['Cloak',0,'','','','','','','','','','','',''],
	['Cycle\nRight VDU',5,'','','Shader\nNew','','','','','','','','',''],
	['Next\nSubunit',1,'Break\nForm','','','','','','','','','','',''],
	['Next\nNeutral\nTarget',1,'Prev','','','','Mission\nN/P','','','','','','',''],
	['Cycle\nLeft VDU',5,'Toggle\nMap','','','','','','','','','','',''],
	['Thrust\nUp',2,'Left','','','','','','','','','','',''],
	['Thrust\nDown',2,'Right','','','','','','','','','','',''],
	null,
	null,
	null,
	null,
	['Fire Primary',0,'','','','','','','','','','','',''],
	null,
	null,
	['Roll\nLeft',2,'','','','','','','','','','','',''],
	['Roll\nRight',2,'','','','','','','','','','','',''],
	['Nose\nLeft',2,'','','','','','','','','','','',''],
	['Match\nVelocity',2,'','','','','','','','','','','',''],
	['Zero\nVelocity',2,'','','','','','','','','','','',''],
	['Nose\nDown',2,'','','','','','','','','','','',''],
	['Nose\nUp',2,'','','','','','','','','','','',''],
	['Scroll\nText Up',5,'','','','','','','','','','','',''],
	['Scroll\nText Down',5,'','','','','','','','','','','',''],
	['Nose\nRight',2,'','','','','','','','','','','',''],
	null,
	['Match\nVelocity',2,'','','','','','','','','','','',''],
	['Nose\nLeft',2,'','','','','','','','','','','',''],
	['Zero\nVelocity',2,'','','','','','','','','','','',''],
	['Roll\nLeft',2,'','','','','','','','','','','',''],
	['Nose\nDown',2,'','','','','','','','','','','',''],
	null,
	['Nose\nUp',2,'','','','','','','','','','','',''],
	null,
	['Roll\nRight',2,'','','','','','','','','','','',''],
	['Scroll\nText Up',5,'','','','','','','','','','','',''],
	['Nose\nRight',2,'','','','','','','','','','','',''],
	['Scroll\nText Down',5,'','','','','','','','','','','',''],
	null,
	['Decrease\nVelocity',2,'','','','','','','','','','','',''],
	['Increase\nVelocity',2,'','','','','','','','','','','',''],
	['Fire\nSecondary',0,'','','','','','','','','','','',''],
	['Quit',5,'','','','','','','','','','','',''],
	['Comm\nKey 1',3,'','','','','','','','','','','',''],
	['Comm\nKey 2',3,'','','','','','','','','','','',''],
	['Comm\nKey 3',3,'','','','','','','','','','','',''],
	['Comm\nKey 4',3,'','','','','','','','','','','',''],
	['Comm\nKey 5',3,'','','','','','','','','','','',''],
	['Comm\nKey 6',3,'','','','','','','','','','','',''],
	['Comm\nKey 7',3,'','','','','','','','','','','',''],
	['Comm\nKey 8',3,'','','','','','','','','','','',''],
	['Volume -',5,'','','','','','','','','','','',''],
	['Volume +',5,'','','','','','','','','','','',''],
	['Music\nVolume -',4,'','','','','','','','','','','',''],
	['Music\nVolume +',4,'','','','','','','','','','','',''],
	null,
	null,
	['Pause\nGame',5,'','','','','','','','','','','',''],
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	null
]
Gam_Table[sLay]['leg'] =
[
[0,'Combat'],
[1,'Targeting'],
[2,'Navigation'],
[3,'Communication'],
[4,'Camera'],
[5,'Game Controls']
]
Gam_Table[sLay]['com'] = []
Gam_Table[sLay]['mou'] = []
Gam_Table[sLay]['joy'] = []
Gam_Table[sLay]['add'] = []


sLay = 'ATDE105'
Gam_Table[sLay] = {}
Gam_Table[sLay]['gam'] = 'Vega Strike'
Gam_Table[sLay]['aut'] = 'Agnes Beste'
// norm_txt, norm_grp, shift_txt, shift_grp, ctrl_txt, ctrl_grp, alt_txt, alt_grp, altgr_txt, altgr_grp, extra_txt, extra_grp, image file, image uri
Gam_Table[sLay]['key'] =
[
	['Ziel 1:\nSprechen',3,'Selbst-\nmord','','Fort-\nsetzen','','Speichern','','','','','','',''],
	['Ziel 2:\nSprechen',3,'','','Fort-\nsetzen','','Spei-\nchern','','','','','','',''],
	['Ziel 3:\nSprechen',3,'','','Fort-\nsetzen','','Spei-\nchern','','','','','','',''],
	['Ziel 4:\nSprechen',3,'','','Fort-\nsetzen','','Spei-\nchern','','','','','','',''],
	['Ziel 5:\nSprechen',3,'','','Fort-\nsetzen','','Spei-\nchern','','','','','','',''],
	['Ziel 6:\nSprechen',3,'','','Fort-\nsetzen','','Spei-\nchern','','','','','','',''],
	['Ziel 7:\nSprechen',3,'','','Fort-\nsetzen','','Spei-\nchern','','','','','','',''],
	['Ziel 8:\nSprechen',3,'','','Fort-\nsetzen','','Spei-\nchern','','','','','','',''],
	['Ziel 9:\nSprechen',3,'','','Fort-\nsetzen','','Spei-\nchern','','','','','','',''],
	['Erbitte\nLande-\nerlaubnis',3,'','','','','','','','','','','',''],
	['Bremsen',2,'','','','','','','','','','','',''],
	['Beschleu-\nnigen',2,'','','','','','','','','','','',''],
	['Stoppen',2,'','','','','','','','','','','',''],
	['Nachbrenner',2,'','','','','','','','','','','',''],
	null,
	['Wähle\nSekundär-\nwaffe',0,'','','','','','','','','','','',''],
	['ECM\nan/ab',0,'Erlasse\nSchiff','','','','','','','','','','',''],
	null,
	['Alle Ziele',1,'Rückw.','','','','','','','','','','',''],
	['Kampf-\nmodus',0,'','','','','','','','','','','',''],
	['Alles außer\nPlaneten',1,'Rückw.','','','','','','','','','','',''],
	['Screenshot',5,'','','','','','','','','','','',''],
	['Turm-KI\nan/ab',1,'','','','','','','','','','','',''],
	['Ziel unter\nFaden-\nkreuz',1,'','','','','','','','','','','',''],
	null,
	['Turm-\nkontrolle',1,'Wähle\nZiel für\nTürme','','','','','','','','','','',''],
	null,
	null,
	['SPEC Dr.\nan',2,'Ab','','','','','','','','','','',''],
	['','','Nächster\nSong\nTitel','','','','','','','','','','',''],
	['Andocken',2,'Alle mein\nZiel an-\ngreifen','','','','','','','','','','',''],
	['','','Forma-\ntionsflug ','','','','','','','','','','',''],
	['Wähle\nPrimär-\nwaffe',0,'','','','','','','','','','','',''],
	['Feind-\nliche\nZiele',1,'Rückw.','','','','Hilfe','','','','','','',''],
	['Jump Dr.\nan/ab',2,'','','','','','','','','','','',''],
	null,
	['Visiere\nan Ziel',1,'','','','','','','','','','','',''],
	['Schiff\naufer-\nstehen',5,'','','','','','','','','','','',''],
	null,
	['Volle\nGeschw.',2,'Spiel\npausen','','','','','','','','','','',''],
	['Feuer\nSekundär-\nwaffe',0,'','','','','','','','','','','',''],
	null,
	['Musik -',5,'Musik +','','','','','','','','','','',''],
	['Tarn-\nschild',0,'Kargo\naus-\nwerfen','','','','','','','','','','',''],
	null,
	null,
	['Rechte\nVDU',5,'','','','','','','','','','','',''],
	['Teil des\nSchiffs',1,'Formation\nauflösen','','','','','','','','','','',''],
	['Wichtige /\nNeutrale\nZiele',1,'Rückw.','','','','','','','','','','',''],
	['Linke\nVDU',5,'Miss/Nav\nComputer','','','','','','','','','','',''],
	['Geräu-\nsche -',5,'Musik -','','','','','','','','','','',''],
	['Geräu-\nsche +',5,'Musik +','','','','','','','','','','',''],
	null,
	null,
	null,
	null,
	['Feuer Primärwaffe',0,'','','','','','','','','','','',''],
	null,
	null,
	['Links\nRollen',2,'','','','','','','','','','','',''],
	['Rechts\nRollen',2,'','','','','','','','','','','',''],
	['Links',2,'','','','','','','','','','','',''],
	['Geschw.\ndem Ziel\nanpassen',2,'','','','','','','','','','','',''],
	['Null\nGeschw.',2,'','','','','','','','','','','',''],
	['Hoch',2,'','','','','','','','','','','',''],
	['Runter',2,'','','','','','','','','','','',''],
	['Text nach\noben',5,'','','','','','','','','','','',''],
	['Text nach\nunten',5,'','','','','','','','','','','',''],
	['Rechts',2,'','','','','','','','','','','',''],
	null,
	['Geschw.\ndem Ziel\nanpassen',2,'','','','','','','','','','','',''],
	['Links',2,'','','','','','','','','','','',''],
	['Null\nGeschw.',2,'','','','','','','','','','','',''],
	['Links\nRollen',2,'','','','','','','','','','','',''],
	['Hoch',2,'','','','','','','','','','','',''],
	null,
	['Runter',2,'','','','','','','','','','','',''],
	null,
	['Rechts\nRollen',2,'','','','','','','','','','','',''],
	['Text nach\noben',5,'','','','','','','','','','','',''],
	['Rechts',2,'','','','','','','','','','','',''],
	['Text nach\nunten',5,'','','','','','','','','','','',''],
	null,
	['Bremsen',2,'','','','','','','','','','','',''],
	['Beschleu-\nnigen',2,'','','','','','','','','','','',''],
	['Feuer\nSekundär-\nwaffe',0,'','','','','','','','','','','',''],
	['Spiel\nbeenden',5,'','','','','','','','','','','',''],
	['Normales\nCockpit',4,'','','','','','','','','','','',''],
	['Nach links\nschauen',4,'','','','','','','','','','','',''],
	['Nach rechts\nschauen',4,'','','','','','','','','','','',''],
	['Nach hinten\nschauen',4,'','','','','','','','','','','',''],
	['Verfolg-\nungs-\nkamera',4,'','','','','','','','','','','',''],
	['Freie\nKamera',4,'','','','','','','','','','','',''],
	['Ziel-\nkamera',4,'','','','','','','','','','','',''],
	['Ziel-Ego-\nKamera',4,'','','','','','','','','','','',''],
	['Zeitver-\nzerrung +',5,'','','','','','','','','','','',''],
	['Zeitver-\nzerrung -',5,'','','','','','','','','','','',''],
	['Kamera\nein-\nzoomen',4,'','','','','','','','','','','',''],
	['Kamera\naus-\nzoomen',4,'','','','','','','','','','','',''],
	null,
	null,
	['Spiel\npausen',5,'','','','','','','','','','','',''],
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	null
]
Gam_Table[sLay]['leg'] =
[
[0,'Kampf'],
[1,'Zielerfassung'],
[2,'Bewegung'],
[3,'Kommunikation'],
[4,'Kamera'],
[5,'System Kontrolle']
]
Gam_Table[sLay]['com'] = []
Gam_Table[sLay]['mou'] = []
Gam_Table[sLay]['joy'] = []
Gam_Table[sLay]['add'] = []
