sLay = 'ATUS104'
Gam_Table['gam'][sLay] = 'Thief 2: The Metal Age'
Gam_Table['aut'][sLay] = ''
Gam_Table['key'][sLay] =
[
,
['red','Clear\nWeapon',,,,,,],
['red','Sword',,,,,,],
['red','Blackjack',,,,,,],
['red','Broadhead\nArrow',,,,,,],
['red','Water\nArrow',,,,,,],
['red','Fire\nArrow',,,,,,],
['red','Moss\nArrow',,,,,,],
['red','Gas\nArrow',,,,,,],
['red','Rope\nArrow',,,,,,],
['red','Noise\nArrow',,,,,,],
,
['mag','Gamma -',,,,,,],
['mag','Gamma +',,,,,,],
['yel','Clear Items',,,,,,],
['yel','Next Item','Previous',,,,,],
['grn','Lean Left',,,,,,],
['grn','Move\nForward',,,'Lean\nForward',,,],
['grn','Lean Right',,,,,,],
['yel','Drop Item',,,,,,],
['blu','Look Up',,,,,,],
,
,
,
['mag','Objectives',,,,,,],
['blu','Reset\nZoom',,,,,,],
['blu','Zoom Out',,,,,,],
['blu','Zoom In',,,,,,],
,
,
['grn','Move Left',,,,,,],
['grn','Move\nBackward',,,'Quick\nSave',,,],
['grn','Move Right',,,,,,],
['red','Flare',,,,,,],
['blu','Look Down',,,,,,],
,
,
,
[,,,,'Quick Load',,,],
,
,
,
['red','Use Item',,,,,,],
['grn','Toggle Run/Walk',,,,,,],
,
['grn','Turn Left',,,,,,],
['grn','Crouch',,,,,,],
['grn','Turn Right',,,,,,],
['blu','Center\nView',,,,,,],
['red','Block',,,,,,],
,
['mag','Map',,,,,,],
,
,
,
['grn','Toggle Run/Walk',,,,,,],
,
,
['grn','Jump',,,,,,],
,
,
,
,
['grn','Move Left',,,,,,],
,
,
['grn','Move\nForward',,,,,,],
['grn','Move\nBackward',,,,,,],
,
,
['grn','Move Right',,,,,,],
,
['grn','Lean Left',,,,,,],
['grn','Move Left',,,,,,],
['grn','Turn Left',,,,,,],
['yel','Previous\nItem',,,,,,],
['grn','Move\nForward',,,,,,],
['grn','Move\nBackward',,,,,,],
['grn','Crouch',,,,,,],
['grn','Jump',,,,,,],
['yel','Next\nItem',,,,,,],
['grn','Lean Right',,,,,,],
['grn','Move Right',,,,,,],
['grn','Turn Right',,,,,,],
,
['red','Previous\nWeapon',,,,,,],
['red','Next\nWeapon',,,,,,],
['grn','Toggle\nRun/Walk',,,,,,],
['mag','Main Menu',,,,,,],
['yel','Healing\nPotion',,,,,,],
['yel','Breath\nPotion',,,,,,],
['yel','Invisibility\nPotion',,,,,,],
['yel','Slowfall\nPotion',,,,,,],
['yel','Speed\nPotion',,,,,,],
['yel','Lockpick\n1',,,,,,],
['yel','Lockpick\n2',,,,,,],
['yel','Flash\nBomb',,,,,,],
['yel','Gas\nMine',,,,,,],
['yel','Mine',,,,,,],
['yel','Scouting\nOrb',,,,,,],
['yel','Compass',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,

]
Gam_Table['leg'][sLay] =
[
['red','Weapons/Actions'],
['yel','Items'],
['grn','Movement'],
['blu','Camera'],
['mag','Game Controls']
]
Gam_Table['com'][sLay] = []
Gam_Table['mou'][sLay] =
[       
'Left Click = Attack',
'Right Click = Use Item',
'Middle Click = Block',
'Wheel = Cycle Items'
]
Gam_Table['joy'][sLay] = []
Gam_Table['add'][sLay] = []
