sLay = 'ATUS104'
Gam_Table['gam'][sLay] = 'StarShatter'
Gam_Table['aut'][sLay] = ''
Gam_Table['key'][sLay] =
[
,
['mag','Mouse\nSteering',,,,,,],
['cyn','Radio\nCommand',,,,,,],
['cyn','Radio\nCommand',,,,,,],
['cyn','Radio\nCommand',,,,,,],
['cyn','Radio\nCommand',,,,,,],
['cyn','Radio\nCommand',,,,,,],
['cyn','Radio\nCommand',,,,,,],
['cyn','Radio\nCommand',,,,,,],
['cyn','Radio\nCommand',,,,,,],
['cyn','Radio\nCommand',,,,,,],
['cyn','Radio\nCommand',,,,,,],
['blu','Zoom\nOut',,,,,,],
['blu','Zoom\nIn',,,,,,],
['red','Cycle Secondary','Cycle\nPrimary',,,,,],
['grn','Afterburner',,,,,,],
['grn','Quantum\nDrive',,,,,,],
['mag','WEP\nConsole',,,,,,],
['mag','ENG\nConsole',,,'Escort\nTarget',,,],
['cyn','Radio\nMenu',,,'Return\nto Base',,,],
['yel','Ship in\nReticule','Attack\nThreat',,,,,],
['yel','Closest\nShip','Closest\nThreat',,,,,],
['yel','Hostile\nShip','Hostile\nThreat',,,,,],
[,,,,'Call\nInbound',,,],
['grn','Break\nOrbit',,,,,,],
[,,,,'Request\nPicture',,,],
['mag','Lower\nLeft MFD',,,,,,],
['mag','Lower\nRight MFD',,,,,,],
,
,
['grn','Increase\nThrust','Max\nThrust',,'Attack\nTarget',,,],
['red','Increase\nShields','Max\nShields',,'Request\nSupport',,,],
['red','Release\nDecoy',,,,,,],
['mag','FLIGHT\nConsole',,,'Form Up',,,],
['grn','Landing\nGear',,,,,,],
['mag','HUD Mode','HUD\nColor',,'Help\nMe',,,],
['mag','Swap\nRoll/Yaw',,,,,,],
['blu','Camera\nAngle',,,,,,],
['grn','NAV Lights',,,,,,],
,
,
,
,
,
,
['grn','Decrease\nThrust','Zero\nThrust',,,,,],
['grn','Decrease\nShields','Zero\nShields',,,,,],
['mag','Indicators',,,,,,],
['blu','View\nSelection',,,,,,],
[,,,,'Break &\nAttack',,,],
['mag','NAV\nConsole',,,'Skip\nNav',,,],
['mag','FLCS Mode',,,,,,],
['grn','Camera\nLeft',,,,,,],
['grn','Camera\nRight',,,,,,],
,
,
['red','Fire Primary',,,,,,],
,
['red','Fire Secondary',,,,,,],
,
['red','Fire Primary',,,,,,],
['mag','Accel Time',,,,,,],
['mag','Decel Time',,,,,,],
['grn','Yaw Left',,,,,,],
['blu','Camera\nForward',,,,,,],
['blu','Camera\nBackward',,,,,,],
['grn','Pitch Down',,,,,,],
['grn','Pitch Up',,,,,,],
['blu','Camera\nUp',,,,,,],
['blu','Camera\nDown',,,,,,],
['grn','Yaw Right',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
['mag','Exit',,,,,,],
['blu','Main\nView','Virtual\n3D',,,,,],
['blu','Chase\nView',,,,,,],
['blu','Orbit\nView',,,,,,],
['blu','Padlock\nView',,,,,,],
['mag','Sensors\nMode','Ground\nMode',,,,,],
['red','Launch\nProbe',,,,,,],
['red','Decrease\nSensors',,,,,,],
['red','Increase\nSensors',,,,,,],
['mag','Decrease\nEMCON',,,,,,],
['mag','Increase\nEMCON',,,,,,],
,
['mag','Screenshot',,,,,,],
,
,
['mag','Pause',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,

]
Gam_Table['leg'][sLay] =
[
['red','Combat'],
['yel','Targeting'],
['grn','Navigation'],
['cyn','Communication'],
['blu','Camera'],
['mag','Game Controls']
]
Gam_Table['com'][sLay] = []
Gam_Table['mou'][sLay] = []
Gam_Table['joy'][sLay] = []
Gam_Table['add'][sLay] = []
