sLay = 'ATUS104'
Gam_Table['gam'][sLay] = 'Baldur\'s Gate II: Shadows of Amn'
Gam_Table['aut'][sLay] = ''
Gam_Table['key'][sLay] =
[
,
,
['yel','Select\nUnit 1',,,,,,],
['yel','Select\nUnit 2',,,,,,],
['yel','Select\nUnit 3',,,,,,],
['yel','Select\nUnit 4',,'Debug:\nShow\nDoors\n& Traps',,,,],
['yel','Select\nUnit 5',,,,,,],
['yel','Select\nUnit 6',,'Debug:\nSprite -',,,,],
['yel','Select\nUnits 1 & 2',,'Debug:\nSprite +',,,,],
['yel','Select\nUnits 3 & 4',,,,,,],
['yel','Select\nUnits 5 & 6',,,,,,],
['yel','Select\nUnits 1 - 3',,,,,,],
['yel','Select\nUnits 4 - 6',,,,,,],
['yel','Select\nAll Units',,,,,,],
,
['blu','Show\nHealth Bars',,,,,,],
['mag','Quick\nSave',,'Debug:\nAdd to\nParty',,,,],
['mag','Mage\nBook',,,,,,],
,
['mag','Character\nInfo',,'Debug:\nHeal\nUnits',,,,],
['cyn','Chat\nWindow',,'Debug:\nTime +1\nHour',,,,],
['mag','Toggle\nLeft HUD',,'Debug:\nKill\nUnit',,,,],
['mag','Toggle\nRight HUD',,,,,,],
['mag','Inventory',,'Debug:\nSet\nAnim',,,,],
['mag','Game\nOptions',,,,,,],
['mag','Priest\nScroll',,,,,,],
,
,
,
,
['mag','Toggle\nAI',,'Debug:\nPlay\nCombat\nSequence',,,,],
[,,,'Debug:\nSet\nCombat\nSequence',,,,],
[,,,'Debug:\nFrame\nRate',,,,],
[,,,'Debug:\nFace\nCursor',,,,],
['mag','Return\nto Game',,'Debug:\nArea\nNumber',,,,],
['mag','Toggle\nAll HUDs',,,,,,],
['mag','Journal',,'Debug:\nTeleport',,,,],
[,,,'Debug:\nRemove\nUnit',,,,],
[,,,'Debug:\nPlay\nAnim',,,,],
,
,
,
,
,
,
['red','Rest',,,,,,],
['mag','Show\nMouse\nCoords',,'Debug:\nCoord\nDetails',,,,],
['mag','Arbitrate\nChar',,'Debug:\nCircus\nMovie',,,,],
,
[,,,'Debug:\nSet\nChar\nSpeed',,,,],
,
['mag','Map',,'Debug:\nItem\nCodes',,,,],
,
,
,
,
,
,
['mag','Pause Game',,'Debug: CLUA Console',,,,],
,
,
,
,
['blu','Scroll\nLeft',,,,,,],
,
,
['blu','Scroll\nUp',,,,,,],
['blu','Scroll\nDown',,,,,,],
['mag','Message\nBox +',,,,,,],
['mag','Message\nBox -',,,,,,],
['blu','Scroll\nRight',,,,,,],
,
['blu','Scroll\nUp-Left',,,,,,],
['blu','Scroll\nLeft',,,,,,],
['blu','Scroll\nDown-Left',,,,,,],
,
['blu','Scroll\nUp',,,,,,],
,
['blu','Scroll\nDown',,,,,,],
,
,
['blu','Scroll\nUp-Right',,,,,,],
['blu','Scroll\nRight',,,,,,],
['blu','Scroll\nDown-Right',,,,,,],
,
,
,
,
['mag','Exit\nMenu',,,,,,],
['red','Talk',,,,,,],
['red','Quick\nAction 1',,,,,,],
['red','Quick\nAction 2',,,,,,],
['red','Quick\nAction 3',,,,,,],
['red','Quick\nAction 4',,,,,,],
['red','Quick\nAction 5',,,,,,],
['red','Cast\nSpell',,,,,,],
['red','Use\nItem',,,,,,],
['red','Quick\nItem 1',,,,,,],
['red','Quick\nItem 2',,,,,,],
['red','Quick\nItem 3',,,,,,],
['red','Special\nAbility',,,,,,],
['mag','Screenshot',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,

]
Gam_Table['leg'][sLay] =
[
['red','Actions/Commands'],
['yel','Selection'],
['blu','Camera'],
['cyn','Chat'],
['mag','Game Controls']
]
Gam_Table['com'][sLay] =
[
'SHIFT + LMB on Terrain = Set Waypoints',
'ALT + LMB on Terrain = Move on Mouseup',
'SHIFT or CTRL + LMB on Unit = Add Unit to Selection',
'SHIFT or CTRL + Drag LMB on Terrain = Add Multiple Units to Selection',
'(Debug) CTRL + Hold U + I = Inter-character Dialogues'
]
Gam_Table['mou'][sLay] =
[
'LMB on Unit = Select Unit',
'Drag LMB on Terrain = Select Multiple Units'
]
Gam_Table['joy'][sLay] = []
Gam_Table['add'][sLay] = []
