sLay = 'ATUS104'
Gam_Table['gam'][sLay] = 'Homeworld & Homeworld: Cataclysm'
Gam_Table['aut'][sLay] = ''
Gam_Table['key'][sLay] =
[
,
['red','Cancel\nOrder',,,,,,],
['yel','Select\nGroup',,'Assign',,,,],
['yel','Select\nGroup',,'Assign',,,,],
['yel','Select\nGroup',,'Assign',,,,],
['yel','Select\nGroup',,'Assign',,,,],
['yel','Select\nGroup',,'Assign',,,,],
['yel','Select\nGroup',,'Assign',,,,],
['yel','Select\nGroup',,'Assign',,,,],
['yel','Select\nGroup',,'Assign',,,,],
['yel','Select\nGroup',,'Assign',,,,],
['yel','Select\nGroup',,'Assign',,,,],
,
,
,
['mag','Formations',,,,,,],
,
,
['yel','Select All',,,,,,],
['mag','Research\nManager',,,,,,],
['cyn','Send\nMessage',,,,,,],
,
,
['red','Retire',,,,,,],
,
['mag','Pause',,,,,,],
,
,
,
['mag','Tactical Overlay',,,,,,],
,
['red','Scuttle',,,,,,],
['red','Dock',,,,,,],
['yel','Focus on\nSelected',,,,,,],
['red','Guard',,,,,,],
['red','Harvest',,,,,,],
['red','Hyper-\nspace',,,,,,],
['red','Kamikaze',,,,,,],
['mag','Launch\nManager',,,,,,],
,
,
,
,
,
,
['red','Special',,,,,,],
,
['yel','Cancel\nFocus',,,,,,],
,
['mag','Build\nManager',,,,,,],
,
['red','Move','Vertical\nMove',,,,,],
,
,
,
,
['red','Attack','Force\nAttack',,,,,],
,
['mag','Sensors Manager',,,,,,],
,
,
,
['blu','Unfocus\nCamera',,,,,,],
['blu','Pan\nLeft',,,,,,],
['yel','Focus on\nMothership',,,,,,],
,
['blu','Pan\nForward',,,,,,],
['blu','Pan\nBack',,,,,,],
,
,
['blu','Pan\nRight',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
['yel','Deselect',,,,,,],
['blu','Fleet\nView',,,,,,],
['red','Evasive\nStance',,,,,,],
['red','Neutral\nStance',,,,,,],
['red','Aggressive\nStance',,,,,,],
['red','Delta\nFormation',,,,,,],
['red','Broad\nFormation',,,,,,],
['red','X\nFormation',,,,,,],
['red','Claw\nFormation',,,,,,],
['red','Wall\nFormation',,,,,,],
['red','Sphere\nFormation',,,,,,],
['red','Custom\nFormation',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,

]
Gam_Table['leg'][sLay] =
[
['red','Actions'],
['yel','Selection'],
['blu','Camera'],
['cyn','Chat'],
['mag','Menus']
]
Gam_Table['com'][sLay] =
[
'SHIFT + LMB = Add to Selection',
'CTRL + Drag LMB = Attack Group',
'CTRL + SHIFT + LMB = Force Attack',
'ALT + LMB = Focus Without Selection',
'CTRL + ALT + F = Fleet View',
'LMB + Z = Repair'
]
Gam_Table['mou'][sLay] =
[
'LMB = Select Ship / Attack Ship',
'Drag LMB = Band-box Select',
'XY Axes + RMB = Rotate Camera',
'LMB + RMB + Y Axis = Zoom In/Out',
'Mouse Wheel = Zoom In/Out',
'MMB = Focus on Unit'
]
Gam_Table['joy'][sLay] = []
Gam_Table['add'][sLay] = []
