sLay = 'ATUS104'
Gam_Table['gam'][sLay] = 'Myth: The Fallen Lords'
Gam_Table['aut'][sLay] = ''
Gam_Table['key'][sLay] =
[
,
['yel','Clear\nSelection',,,,,,],
['yel','Short\nLine',,,,,,],
['yel','Long\nLine',,,,,,],
['yel','Loose\nLine',,,,,,],
['yel','Staggered\nLine',,,,,,],
['yel','Box',,,,,,],
['yel','Rabble',,,,,,],
['yel','Shallow\nEncircle-\nment',,,,,,],
['yel','Deep\nEncircle-\nment',,,,,,],
['yel','Vanguard',,,,,,],
['yel','Circle',,,,,,],
,
,
,
['mag','Overhead\nMap',,,,,,],
['blu','Orbit\nClockwise',,,,,,],
['blu','Pan Up',,,,,,],
['blu','Orbit\nCounter-\nclockwise',,,,,,],
['red','Retreat',,,,,,],
['red','Special\nAction',,,,,,],
['red','Whisper','Yell',,,,,],
,
,
,
,
,
,
['yel','Detach Units',,,,,,],
,
['blu','Rotate\nLeft',,,,,,],
['blu','Pan Down',,,,,,],
['blu','Rotate\nLeft',,,,,,],
['yel','Cycle\nPresets',,,,,,],
['red','Guard',,,,,,],
['blu','Focus on\nSelection',,,,,,],
,
,
,
,
,
,
['yel','Select/Deselect All',,,,,,],
['yel','(Plus Click)\nSet Waypoints /\nAdd to Selection',,,,,,],
,
['blu','Pan Left',,,,,,],
['blu','Pan Right',,,,,,],
['blu','Zoom In',,,,,,],
['blu','Zoom Out',,,,,,],
['red','Scatter',,,,,,],
['mag','Rename\nUnit',,,,,,],
,
,
,
,
['yel','(Plus Click)\nSet Waypoints /\nAdd to Selection',,,,,,],
['red','Attack Ground',,,,,,],
['yel','(Plus 0-9)\nRecall/Set\nPreset',,,,,,],
['red','Stop',,,,,,],
['yel','(Plus 0-9)\nRecall/Set\nPreset',,,,,,],
['red','Attack Ground',,,,,,],
,
['yel','Cycle\nPresets',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
['mag','Main\nMenu',,,,,,],
['mag','Game\nSpeed -',,,,,,],
['mag','Game\nSpeed +',,,,,,],
['mag','Volume -',,,,,,],
['mag','Volume +',,,,,,],
['mag','Toggle\nResolution',,,,,,],
['mag','Toggle\nStatus Bar',,,,,,],
['mag','Network\nStatistics',,,,,,],
['mag','Key Map',,,,,,],
['mag','(3DFX)\nBright -',,,,,,],
['mag','(3DFX)\nBright +',,,,,,],
['mag','Filter\nLandscape',,,,,,],
['blu','Auto\nCamera',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,

]
Gam_Table['leg'][sLay] =
[
['red','Commands/Actions'],
['yel','Selection/Formations'],
['blu','Camera'],
['mag','Game Controls']
]
Gam_Table['com'][sLay] =
[
'ALT + 0-9 = Set/Recall Preset Selections',
'Shift + Left Click on Map = Set Waypoints',
'Shift + Left Click on Unit = Add/Remove from Selection'
]
Gam_Table['mou'][sLay] =
[
'Left Click = Select Unit',
'Double Left Click = Select Nearby Units',
'Right Click = Deselect Unit',
'Drag Mouse = Face Units'
]
Gam_Table['joy'][sLay] = []
Gam_Table['add'][sLay] = []
