sLay = 'ATUS104'
Gam_Table['gam'][sLay] = 'Xconq'
Gam_Table['aut'][sLay] = ''
Gam_Table['key'][sLay] =
[
,
,
[,,'Detonate\nMunition',,,,,],
[,,'Change\nCamera\nAngle',,,,,],
[,,'Distance\nto Target',,,,,],
,
,
,
,
,
,
,
['grn','Decrease\nAltitude',,,,,,],
['grn','Increase\nAltitude',,,,,,],
,
,
[,,'Quit\nGame',,,,,],
['red','Wake\nUp Unit','Wake Up\nAll in Cell',,,,,],
['red','Enter\nTransport',,'Exit\nTransport',,,,],
['red','Return to\nResupply','Remove\nTerrain','Redraw\nDisplay',,,,],
['red','Take\nSupplies\nfrom Unit',,,,,,],
['grn','Move\nNW','Move\nMultiple',,,,,],
['grn','Move\nNE','Move\nMultiple',,,,,],
['mag','Look at\nOccupants','Set Unit\nto Idle',,,,,],
['mag','Other\nCommands',,,,,,],
['mag','Setup\nProduction','Setup\nBuilds','Repair\nUnit',,,,],
[,,'Zoom\nOut',,,,,],
[,,'Zoom\nIn',,,,,],
,
,
['red','Attack\nUnit','Alter\nTerrain','Toggle AI',,,,],
['red','Go to\nSleep','Save\nGame',,,,,],
['red','Delay\nAction','Disband\nUnit','Detach\nPart',,,,],
['red','Fire at\nUnit','Set\nForm','Fire at\nLocation',,,,],
['red','Give\nSupplies\nto Unit','Give Unit\nto Side',,,,,],
['grn','Move\nW','Move\nMultiple',,,,,],
['grn','Move\nS','Move\nMultiple','End Turn',,,,],
['grn','Move\nN','Move\nMultiple',,,,,],
['grn','Move\nE','Move\nMultiple',,,,,],
,
,
,
,
,
,
['mag','Switch\nSelection\nMode',,,,,,],
,
['mag','Change\nUnit\nType','Clear\nUnit\nPlans',,,,,],
['mag','Flash\nUnit\nPosition',,,,,,],
['grn','Move\nSW','Move\nMultiple',,,,,],
['grn','Move\nSE','Move\nMultiple',,,,,],
['grn','Move\nto Place','Send\nMessage','End Turn',,,,],
,
['mag','Center on\nSelected',,,,,,],
[,,'Display\nHelp Info',,,,,],
,
,
,
['red','Put into Reserve',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,

]
Gam_Table['leg'][sLay] =
[
['grn','Movement'],
['red','Unit Actions'],
['mag','Game Controls']
]
Gam_Table['com'][sLay] = []
Gam_Table['mou'][sLay] = []
Gam_Table['joy'][sLay] = []
Gam_Table['add'][sLay] = []
