sLay = 'ATUS104'
Sch_Table['gam'][sLay] = 'Independence War 2: Edge of Chaos'
Sch_Table['aut'][sLay] = ''
Sch_Table['key'][sLay] =
[
,
['mag','MP Chat','Team\nChat',,,,,],
['cyn','Report In\n(Wing)','Taunt 1',,,,,],
['cyn','Defend Me\n(Wing)','Taunt 2',,,,,],
['cyn','Attack\nTarget\n(Wing)','Taunt 3',,,,,],
['cyn','Defend\nTarget\n(Wing)','Taunt 4',,,,,],
['cyn','Dock to\nTarget\n(Wing)',,,,,,],
['cyn','Halt\n(Wing)',,,,,,],
['cyn','Cease Fire\n(Turret)',,,,,,],
['cyn','Attack\nTarget\n(Turret)',,,,,,],
['cyn','Fire\nat Will\n(Turret)',,,,,,],
['cyn','Dock /\nUndock\n(Turret)',,,,,,],
['grn','Thrust -',,,,,,],
['grn','Thrust +',,,,,,],
['red','Cycle\nSecondary Weapon',,,,,,],
['mag','MP Scores',,,,,,],
['yel','Target\nLast\nAttacker',,,,,,],
['grn','Forward\nThrust\nOverride',,,,,,],
['yel','Cycle\nEnemy\nTargets','Engin-\neering',,,,,],
['yel','Target\nNearest\nEnemy','Remote\nPilot',,,,,],
['yel','Target in\nReticule',,,,,,],
['yel','Sub-\nTarget /\nTag Cargo',,,,,,],
['grn','Undock',,,,,,],
['red','Launch\nLDSI\nMissile',,,,,,],
[,,'Objectives',,,,,],
['mag','Pause\nGame',,,,,,],
,
,
,
,
['grn','Left\nThrust\nOverride',,,,,,],
['grn','Reverse\nThrust\nOverride','Statistics',,,,,],
['grn','Right\nThrust\nOverride',,,,,,],
['red','Toggle\nFire Mode',,,,,,],
,
,
['cyn','Jafs:\nCargo\nPickup',,,,,,],
,
['grn','Toggle\nManual LDS',,'Log',,,,],
,
,
,
['red','Cycle Primary Weapon',,,,,,],
,
['red','Fire Selected',,,,,,],
['red','Zoom\n(Sniper\nMode)',,,,,,],
['red','Toggle\nAim Assist',,,,,,],
['yel','Next\nCritical\nShip',,,,,,],
,
,
['grn','Toggle\nFlight\nAssist',,,,,,],
[,,'Star Map',,,,,],
['yel','Cycle\nTargets\nDown',,,,,,],
['yel','Cycle\nTargets\nUp',,,,,,],
,
,
['grn','Flight Assist\n(Hold Key)',,,,,,],
['grn','Lateral\nThrusters\n(Hold Key)',,,,,,],
['red','Fire Selected Weapon',,,,,,],
['grn','Lateral\nThrusters\n(Hold Key)',,,,,,],
['grn','Flight Assist\n(Hold Key)',,,,,,],
,
['mag','Skip Dialog',,,,,,],
['mag','Menu\nLeft',,'Power to\nWeapons',,,,],
['yel','Select First\nin List',,,,,,],
['yel','Select Last\nin List',,,,,,],
['mag','Menu Up /\nPrev Dialog','Reset\nDistribution',,,,,],
['mag','Menu Down /\nNext Dialog','Power to\nEngines',,,,,],
,
,
['mag','Menu\nRight','Power to\nShields',,,,,],
,
['blu','Camera\nRoll Left',,,,,,],
['blu','Camera\nTurn Left',,,,,,],
,
,
['blu','Camera\nTurn Up',,,,,,],
,
['blu','Camera\nTurn Down',,,,,,],
,
['blu','Camera\nZoom\nto Fit',,,,,,],
['blu','Camera\nRoll Right',,,,,,],
['blu','Camera\nTurn Right',,,,,,],
,
,
['blu','Camera\nZoom Out',,,,,,],
['blu','Camera\nZoom In',,,,,,],
,
['mag','Main\nMenu',,,,,,],
['blu','Cycle\nInternal\nViews',,,,,,],
['blu','Cycle\nTactical\nViews',,,,,,],
['blu','Cycle\nExternal\nViews',,,,,,],
['blu','Drop\nCamera',,,,,,],
['grn','Autopilot\nDisengage',,,,,,],
['grn','Autopilot\nApproach',,,,,,],
['grn','Autopilot\nFormate',,,,,,],
['grn','Autopilot\nDock',,,,,,],
['grn','Autopilot\nPursuit',,,,,,],
,
['blu','Director\nMode',,,,,,],
,
,
,
['mag','Pause\nGame',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,

]
Sch_Table['leg'][sLay] =
[
['red','Combat'],
['yel','Targeting'],
['grn','Navigation'],
['cyn','Communication'],
['blu','Camera'],
['mag','Game Controls']
]
Sch_Table['com'][sLay] = []
Sch_Table['mou'][sLay] = []
Sch_Table['joy'][sLay] = []
Sch_Table['add'][sLay] = []
