sLay = 'ATUS104'
Sch_Table['gam'][sLay] = 'Rome: Total War'
Sch_Table['aut'][sLay] = ''
Sch_Table['key'][sLay] =
[
,
,
['yel','Select\nGroup','Form 1','Assign',,,,],
['yel','Select\nGroup','Form 2','Assign',,,,],
['yel','Select\nGroup','Form 3','Assign',,,,],
['yel','Select\nGroup','Form 4','Assign',,,,],
['yel','Select\nGroup','Form 5','Assign',,,,],
['yel','Select\nGroup','Form 6','Assign',,,,],
['yel','Select\nGroup','Form 7','Assign',,,,],
['yel','Select\nGroup','Form 8','Assign',,,,],
['yel','Select\nGroup',,'Assign',,,,],
['yel','Select\nGroup',,'Assign',,,,],
['grn','Cluster\nTogether',,,,,,],
['grn','Spread\nOut',,,,,,],
['red','Cancel Orders',,,,,,],
,
,
,
,
['grn','Toggle\nRun/Walk',,,,,,],
['cyn','Send\nMessage',,,,,,],
,
,
[,,,'Select\nInfantry',,,,],
,
['mag','Pause\nGame',,,,,,],
,
,
,
,
['red','Fire at\nWill',,'Select\nAll',,,,],
['red','Skirmish\nMode',,'Quick\nSave',,,,],
['red','Guard\nMode',,,,,,],
['red','Special\nAbility',,,,,,],
['yel','Group/\nUngroup',,,,,,],
[,,,'Select\nMelee',,,,],
,
,
,
[,,,'Quick\nLoad',,,,],
,
,
['yel','Deselect All',,,,,,],
['mag','Show Stored Waypoints',,,,,,],
,
,
,
['red','Tight\nFormation',,'Select\nCavalry',,,,],
,
[,,,'Select\nArtillery',,,,],
,
[,,,'Select\nRanged',,,,],
['grn','Rotate\nClockwise',,,,,,],
['grn','Rotate\nCounter-\nclockwise',,,,,,],
,
['mag','Show Stored Waypoints',,,,,,],
,
,
['mag','Show Movement Destinations / Game Speed +',,,,,,],
,
,
,
,
['blu','Pan\nLeft',,,,,,],
['blu','Focus on\nGeneral\n/Home',,,,,,],
['blu','Focus\non Unit',,,,,,],
['blu','Pan\nForward',,,,,,],
['blu','Pan\nBackward',,,,,,],
,
,
['blu','Pan\nRight',,,,,,],
,
,
['blu','Pan\nLeft',,,,,,],
,
['blu','Zoom\nOut',,,,,,],
['blu','Pan\nForward',,,,,,],
,
['blu','Pan\nBackward',,,,,,],
,
['blu','Zoom\nIn',,,,,,],
,
['blu','Pan\nRight',,,,,,],
,
,
['blu','Tilt\nDown',,,,,,],
['blu','Tilt\nUp',,,,,,],
,
['mag','Options\nScreen',,,,,,],
['mag','Help\nScreen',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,

]
Sch_Table['leg'][sLay] =
[
['red','Combat/Actions'],
['grn','Movement'],
['yel','Selection'],
['blu','Camera'],
['cyn','Chat'],
['mag','Game Controls']
]
Sch_Table['com'][sLay] =
[
'CTRL + Click LMB = Add to Selection',
'CTRL + Double-Click LMB = Select All of Same Type',
'SHIFT + Click RMB = Set Waypoint',
'ALT + Click RMB = Secondary Attack'
]
Sch_Table['mou'][sLay] =
[
'Click LMB = Select Unit',
'Double-Click LMB = Focus on Selected Unit',
'Drag LMB = Band-box Select',
'Click RMB = Move to Destination / Attack Unit',
'Double-Click RMB = Run to Destination / Charge Toward Unit',
'Drag RMB = Change Formation Width and Depth',
'Mouse Wheel = Tilt Camera Up/Down',
'Click MMB = Look at Nearest Unit'
]
Sch_Table['joy'][sLay] = []
Sch_Table['add'][sLay] = []
