sLay = 'ATUS104'
Sch_Table['gam'][sLay] = 'Total Annihilation: Kingdoms'
Sch_Table['aut'][sLay] = ''
Sch_Table['key'][sLay] =
[
,
,
['yel','Select\nSquad',,'Assign','Form',,,],
['yel','Select\nSquad',,'Assign','Form',,,],
['yel','Select\nSquad',,'Assign','Form',,,],
['yel','Select\nSquad',,'Assign','Form',,,],
['yel','Select\nSquad',,'Assign','Form',,,],
['yel','Select\nSquad',,'Assign','Form',,,],
['yel','Select\nSquad',,'Assign','Form',,,],
['yel','Select\nSquad',,'Assign','Form',,,],
['yel','Select\nSquad',,'Assign','Form',,,],
['yel','Select\nSquad',,'Assign','Form',,,],
['red','Decrease\nSpeed',,,,,,],
['red','Increase\nSpeed',,,,,,],
,
['yel','Radar',,,,,,],
,
,
[,,,'Select\nMelee',,,,],
[,,,'Select\nBallistic',,,,],
['yel','Track Unit',,'Select\nTroops',,,,],
[,,,'Select\nFlying',,,,],
['red','Unload',,'Select\nVisible',,,,],
,
['red','Open Gate',,,,,,],
['red','Patrol',,,,,,],
,
,
,
,
['red','Attack',,'Select\nAll',,,,],
['red','Stop',,'Save\nGame',,,,],
['mag','Diplomacy',,'Suicide',,,,],
[,,,'Select\nFactory',,,,],
['red','Guard',,'Select\nMagic',,,,],
['red','Heal',,,,,,],
,
['red','Cloak',,,,,,],
['red','Load',,'Load\nGame',,,,],
,
,
,
,
,
,
[,,,'Select\nAll of\nType',,,,],
,
['yel','Clear',,'Copy\nUnit',,,,],
[,,,'Paste\nUnit',,,,],
[,,,'Select\nBuilder',,,,],
['yel','Next Unit',,'Select\nBoat',,,,],
['red','Move',,'Select\nMonarch',,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
['mag','Menu',,'Primary\nWeapon',,,,],
['mag','Briefing',,'Secondary\nWeapon',,,,],
['mag','Last\nReport',,'Special\nWeapon',,,,],
['mag','Score',,,,,,],
['blu','Select\nBookmark',,'Store',,,,],
['blu','Select\nBookmark',,'Store',,,,],
['blu','Select\nBookmark',,'Store',,,,],
['blu','Select\nBookmark',,'Store',,,,],
['mag','Screenshot',,,,,,],
,
,
['mag','Clear Chat',,,,,,],
,
,
['mag','Pause',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,

]
Sch_Table['leg'][sLay] =
[
['red','Action'],
['yel','Selection'],
['mag','Game Controls']
]
Sch_Table['com'][sLay] =
[
'Add to Squad = Shift + Ctrl + 1 thru 0',
'Add to Squad = Shift + Alt + 1 thru 0',
'Select Units = Shift + Ctrl + A',
'Add Builder to Selected = Shift + Ctrl + B',
'Copy Units to Clipboard Shift + Ctrl + C',
'Self-Destruct = Shift + Ctrl + D',
'Add Melee to Selected = Shift + Ctrl + E',
'Add Factory to Selected = Shift + Ctrl + F',
'Add Magic to Selected = Shift + Ctrl + G',
'Load Game = Shift + Ctrl + L',
'Add Monarch to Selected = Shift + Ctrl + M',
'Add Naval to Selected = Shift + Ctrl + N',
'Add Ballistic to Selected = Shift + Ctrl + R',
'Save Game = Shift + Ctrl + S',
'Add Troops to Selected = Shift + Ctrl + T',
'Select Units on Screen = Shift + Ctrl + U',
'Paste Units from Clipboard = Shift + Ctrl + V',
'Add Attack to Selected = Shift + Ctrl + W',
'Cut Unit to Clipboard = Shift + Ctrl + X',
'Add Flying to Selected = Shift + Ctrl + Y',
'Select Units of a Type = Shift + Ctrl + Z'
]
Sch_Table['mou'][sLay] = []
Sch_Table['joy'][sLay] = []
Sch_Table['add'][sLay] = []
