sLay = 'ATUS104'
Sch_Table['gam'][sLay] = 'X-Tension'
Sch_Table['aut'][sLay] = ''
Sch_Table['key'][sLay] =
[
,
,
[,,'Attack\nTarget',,,,,],
[,,'Defend\nWingman',,,,,],
[,,'(Drones)\nAttack',,,,,],
[,,'Defend\nDrones',,,,,],
,
,
,
,
,
,
,
,
['grn','Zero Thrust',,,,,,],
['grn','Maximum\nThrust',,,,,,],
['grn','Roll\nLeft','Quit\nGame',,,,,],
['grn','Roll\nRight',,,,,,],
['yel','Next\nEnemy','Exit/Enter\nShip',,,,,],
,
['yel','Lock on\nTarget',,,,,,],
,
['grn','ZIPPER',,,,,,],
['yel','Target\nInfo',,,,,,],
['grn','Open/Close\nCargo Bay',,,,,,],
['red','Pilot Status','Pause\nGame',,,,,],
,
,
,
,
['grn','Increase\nThrust',,,,,,],
['red','Ship\nStatus','Save\nGame',,,,,],
['grn','Docking\nComputer',,,,,,],
['grn','Load/Eject\nCargo',,,,,,],
,
,
['grn','SINZA',,,,,,],
,
['red','Launch\nMissile','Load\nGame',,,,,],
,
,
,
['mag','Main Menu',,,,,,],
,
,
['grn','Decrease\nThrust',,,,,,],
,
['yel','Hail\nTarget',,,,,,],
['blu','Change\nView',,,,,,],
,
['yel','Navigation\nMap','Galaxy\nMap',,,,,],
['red','Select\nMissile',,,,,,],
['yel','Galaxy\nMap',,,,,,],
['yel','Sector\nMap',,,,,,],
,
,
['red','Fire Laser',,,,,,],
,
,
['yel','Goggles',,,,,,],
['grn','Strafe Drive',,,,,,],
,
,
,
['mag','Minimum\nValue',,,,,,],
['mag','Maximum\nValue',,,,,,],
,
,
['yel','Next\nTarget',,,,,,],
['yel','Previous\nTarget',,,,,,],
,
,
['blu','Look\nUp-Left',,,,,,],
['blu','Look\nLeft',,,,,,],
['blu','Look\nDown-Left',,,,,,],
,
['blu','Look\nUp',,,,,,],
,
['blu','Look\nDown',,,,,,],
,
,
['blu','Look\nUp-Right',,,,,,],
['blu','Look\nRight',,,,,,],
['blu','Look\nDown-Right',,,,,,],
,
,
,
,
,
['blu','Cockpit\nView',,,,,,],
['blu','External\nView',,,,,,],
['blu','Release\nCamera',,,,,,],
['blu','Rear\nView',,,,,,],
['blu','Elliptic\nProjector',,,,,,],
,
,
['mag','General\nOptions',,,,,,],
['mag','Screenshot',,,,,,],
,
['mag','Graphics\nOptions',,,,,,],
['mag','Sound\nOptions',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,

]
Sch_Table['leg'][sLay] =
[
['red','Combat'],
['yel','Targeting'],
['grn','Navigation'],
['blu','Camera'],
['mag','Game Controls']
]
Sch_Table['com'][sLay] = []
Sch_Table['mou'][sLay] = []
Sch_Table['joy'][sLay] = []
Sch_Table['add'][sLay] = []
