sLay = 'ATUS104'
Gam_Table['gam'][sLay] = 'System Shock 2'
Gam_Table['aut'][sLay] = ''
Gam_Table['key'][sLay] =
[
,
['yel','PSI\nAmp',,,,,,],
['yel','Wrench',,,,,,],
['yel','Pistol',,,,,,],
['yel','Shotgun',,,,,,],
['yel','Assault\nRifle',,,,,,],
['yel','Laser\nPistol',,,,,,],
['yel','EMP\nRifle',,,'Com-\npass',,,],
['yel','Electro\nShock',,,,,,],
['yel','Grenade\nLauncher',,,,,,],
['yel','Stasis\nField',,,,,,],
['yel','Fusion\nCannon',,,,,,],
['yel','Crystal\nShard',,,,,,],
['yel','Viral\nProliferator',,,,,,],
['mag','Cut Dialogue',,,,,,],
['yel','Inventory',,,,,,],
['grn','Lean\nLeft',,,,,,],
['grn','Run\nForward',,,,,,],
['grn','Lean\nRight',,,,,,],
['yel','Reload\nWeapon',,,,,,],
['grn','Look\nUp',,,'Tele-\nport',,,],
['yel','Next\nWeapon','Prev',,,,,],
,
['yel','Inventory',,,,,,],
['yel','Weapon\nSettings',,,,,,],
['yel','Radiation\nHypo',,,,,,],
,
,
['yel','Worm Launcher',,,,,,],
,
['grn','Turn\nLeft',,,,,,],
['grn','Crouch',,,'Quick\nSave',,,],
['grn','Turn\nRight',,,,,,],
,
['grn','Look\nDown',,,,,,],
['yel','Medical\nHypo',,,,,,],
,
,
['mag','Message\nHistory',,,'Quick\nLoad',,,],
['yel','Cycle\nAmmo',,,,,,],
,
,
,
['grn','Creep Mode',,,,,,],
,
['grn','Strafe\nLeft',,,,,,],
['grn','Walk\nBackward',,,,,,],
['grn','Strafe\nRight',,,'Com-\npass',,,],
['grn','Look\nForward',,,,,,],
['yel','Cycle\nAmmo',,,,,,],
['mag','Navigation\nMarker',,,,,,],
['mag','Map',,,,,,],
,
,
,
['grn','Creep Mode',,,,,,],
,
['mag','Split Stack',,,,,,],
['grn','Jump',,,,,,],
['mag','Split Stack',,,,,,],
,
,
,
['grn','Turn\nLeft',,,,,,],
,
,
['grn','Run\nForward',,,,,,],
['grn','Walk\nBackward',,,,,,],
['grn','Look Up',,,,,,],
['grn','Look Down',,,,,,],
['grn','Turn\nRight',,,,,,],
,
['grn','Lean\nLeft',,,,,,],
['grn','Turn\nLeft',,,,,,],
['grn','Strafe\nLeft',,,,,,],
,
['grn','Run\nForward',,,,,,],
,
['grn','Walk\nBackward',,,,,,],
,
,
['grn','Lean\nRight',,,,,,],
['grn','Turn\nRight',,,,,,],
['grn','Strafe\nRight',,,,,,],
,
,
,
,
['mag','Pause\nMenu',,,,,,],
['yel','Quick Use','Assign',,,,,],
['yel','Quick Use','Assign',,,,,],
['yel','Quick Use','Assign',,,,,],
['yel','Quick Use','Assign',,,,,],
['yel','Quick Use','Assign',,,,,],
['yel','Quick Use','Assign',,,,,],
['yel','Quick Use','Assign',,,,,],
['yel','Quick Use','Assign',,,,,],
['yel','Quick Use','Assign',,,,,],
['yel','Quick Use','Assign',,,,,],
['yel','Quick Use','Assign',,,,,],
['yel','Quick Use','Assign',,,,,],
,
,
['mag','Minimize',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,

]
Gam_Table['leg'][sLay] =
[
['grn','Movement'],
['yel','Inventory'],
['mag','Game Controls']
]
Gam_Table['com'][sLay] =
[
'Lean Forward = Alt + Shift + W'
]
Gam_Table['mou'][sLay] = []
Gam_Table['joy'][sLay] = []
Gam_Table['add'][sLay] = []
