sLay = 'ATUS104'
Gam_Table['gam'][sLay] = 'Star Wars: X-Wing'
Gam_Table['aut'][sLay] = ''
Gam_Table['key'][sLay] =
[
,
,
['blu','View 7\nO\'Clock',,,,,,],
['blu','View 6\nO\'Clock',,,,,,],
['blu','View 5\nO\'Clock',,,,,,],
['blu','View 3\nO\'Clock',,,,,,],
['blu','View\nUp',,,,,,],
['blu','View 3\nO\'Clock',,,,,,],
['blu','View 10\nO\'Clock',,,,,,],
['blu','View 12\nO\'Clock',,,,,,],
['blu','View 2\nO\'Clock',,,,,,],
['blu','Toggle\nView Angle',,,,,,],
['grn','Decrease\nThrottle',,,,,,],
['grn','Increase\nThrottle',,,,,,],
['grn','Full Throttle',,,,,,],
,
,
['red','Toggle\nWeapon','Wait for\nOrders',,,,,],
[,,'Evasive\nActions',,'Eject',,,],
['yel','Target\nNearest','Report\nIn',,,,,],
['yel','Target\nNext',,,,,,],
['yel','Target\nPrevious',,,,,,],
['yel','Target\nAhead',,,,,,],
['yel','Toggle\nCMD','Ignore Target',,,,,],
,
,
['grn','1/3\nThrottle',,,,,,],
['grn','2/3\nThrottle',,,,,,],
['grn','Zero Throttle',,,,,,],
,
[,,'Attack\nTarget',,,,,],
['red','Shields',,,,,,],
['mag','Damage\nDisplay',,,,,,],
['grn','S-Foils',,,,,,],
[,,'Engage\nEnemy',,,,,],
['grn','Hyperdrive','Head\nHome',,,,,],
,
,
,
,
,
,
['red','Fire Weapon',,,,,,],
,
,
,
['red','Toggle\nFire Config',,,,,,],
['mag','Toggle\nRecorder','Cover Me',,'Calibrate',,,],
['mag','View\nRecorder',,,,,,],
['mag','Mission\nDisplay',,,,,,],
,
['mag','Map\nDisplay',,,,,,],
,
['blu','Toggle\nCockpit',,,,,,],
['blu','External\nView',,,,,,],
,
['grn','Roll Ship /\nTarget Ahead',,,,,,],
,
,
,
['grn','Roll Ship /\nTarget Ahead',,,,,,],
,
,
['grn','Nose Left',,,,,,],
,
,
['grn','Nose Up',,,,,,],
['grn','Nose Down',,,,,,],
,
,
['grn','Nose Right',,,,,,],
,
,
['grn','Nose Left',,,,,,],
,
['blu','External\nView',,,,,,],
['grn','Nose Up',,,,,,],
,
['grn','Nose Down',,,,,,],
,
['blu','Re-center\nCamera',,,,,,],
,
['grn','Nose Right',,,,,,],
,
,
['grn','Increase\nThrottle',,,,,,],
['grn','Decrease\nThrottle',,,,,,],
['red','Fire\nWeapon',,,,,,],
['mag','Options',,,,,,],
['blu','Cockpit\nView',,,,,,],
['blu','Missile\nView',,,,,,],
['blu','External\nView',,,,,,],
['blu','Re-center\nCamera',,,,,,],
['yel','Preset 1',,'Store',,,,],
['yel','Preset 2',,'Store',,,,],
['yel','Preset 3',,'Store',,,,],
['yel','Preset 4',,'Store',,,,],
['red','Laser\nRecharge','Shield to\nLaser',,,,,],
['red','Shield\nRecharge','Laser to\nShield',,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,

]
Gam_Table['leg'][sLay] =
[
['red','Combat'],
['yel','Targeting'],
['grn','Navigation'],
['blu','Camera'],
['mag','Game Controls']
]
Gam_Table['com'][sLay] = []
Gam_Table['mou'][sLay] = []
Gam_Table['joy'][sLay] = []
Gam_Table['add'][sLay] = []
