sLay = 'ATUS104'
Gam_Table['gam'][sLay] = 'Railroad Tycoon II'
Gam_Table['aut'][sLay] = ''
Gam_Table['key'][sLay] =
[
,
,
['yel','Station\nTab',,,,,,],
['yel','Train\nTab',,,,,,],
['yel','Player\nTab',,,,,,],
['yel','Company\nTab',,,,,,],
,
['yel','Resources\nOverview',,,,,,],
['yel','Stations\nOverview',,,,,,],
['yel','Grades\nOverview',,,,,,],
['yel','Traffic\nDensity\nOverview',,,,,,],
['yel','Track\nOwner\nOverview',,,,,,],
['mag','Game\nSpeed -',,,,,,],
['mag','Game\nSpeed +',,,,,,],
,
['mag','Multiplayer\nChat',,,,,,],
['mag','Quit\nGame',,,,,,],
,
['yel','Expand\nList Box',,,,,,],
,
['red','Lay\nTrack',,'Follow\nTrain',,,,],
,
,
,
['yel','Overview',,,,,,],
['yel','Purchase\nTrain',,'Toggle\nPolygons',,,,],
,
,
,
,
['yel','Anual Report',,,,,,],
['yel','Build Station',,'Save Game',,,,],
['yel','Detail Screen',,'Dialog Box',,,,],
['mag','File Options',,'Find City',,,,],
['mag','Toggle Grid',,,,,,],
,
,
,
['yel','List\nScreen',,'Load\nGame',,,,],
,
,
,
,
,
,
,
,
['mag','Control\nPanel',,,,,,],
,
['red','Bulldoze',,,,,,],
['yel','Recent\nNewspaper',,,,,,],
['yel','Stock\nMarket',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
['blu','Scroll\nLeft',,,,,,],
,
,
['blu','Scroll\nUp',,,,,,],
['blu','Scroll\nDown',,,,,,],
,
,
['blu','Scroll\nRight',,,,,,],
,
,
['blu','Rotate\nLeft',,,,,,],
,
,
['blu','Zoom\nIn',,,,,,],
,
['blu','Zoom\nOut',,,,,,],
,
,
,
['blu','Rotate\nRight',,,,,,],
,
,
,
,
,
,
,
,
['mag','Toggle\nColor\nDepth',,,,,,],
['mag','Toggle\nFullscreen',,,,,,],
['blu','Change\nView',,'Store\nView',,,,],
['blu','Change\nView',,'Store\nView',,,,],
['blu','Change\nView',,'Store\nView',,,,],
['blu','Change\nView',,'Store\nView',,,,],
['blu','Change\nView',,'Store\nView',,,,],
,
['blu','Change\nView',,'Store\nView',,,,],
['blu','Change\nView',,'Store\nView',,,,],
['mag','Screenshot',,,,,,],         
,
['mag','Pause\nGame',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,

]
Gam_Table['leg'][sLay] =
[
['red','Game Actions'],
['yel','Game Menus'],
['blu','Camera Controls'],
['mag','System Menus/Controls']
]
Gam_Table['com'][sLay] = []
Gam_Table['mou'][sLay] = []
Gam_Table['joy'][sLay] = []
Gam_Table['add'][sLay] = []
