sLay = 'ATUS104'
Gam_Table['gam'][sLay] = 'Microsoft Windows'
Gam_Table['aut'][sLay] = ''
Gam_Table['key'][sLay] =
[
,
,
,
,
,
,
,
,
,
,
,
,
[,,,,'Document\nControls',,,],
,
['grn','Go Up/Back','Go\nForward',,,,,],
['grn','Next Dialog','Previous','Cycle Docs','Cycle Windows',,,],
,
[,,,'Close\nDocument',,,,],
,
,
,
[,,,'Redo',,,,],
[,,,'Underline\nText',,,,],
[,,,'Italic\nText',,,,],
,
,
,
,
,
,
[,,,'Select All',,,,],
,
,
,
[,,,'Go To',,,,],
,
,
,
,
,
,
,
[,,,,'Properties /\nResize',,,],
['yel','Expand Selection',,,,,,],
,
[,,,'Undo',,,,],
[,,,'Cut',,,,],
[,,,'Copy',,,,],
[,,,'Paste',,,,],
[,,,'Bold Text',,,,],
,
,
,
,
,
['mag','Skip Autoplay',,,,,,],
['yel','Add to Selection',,,,,,],
,
[,,,,'Window Controls',,,],
,
['grn','Scroll',,,,,,],
,
[,,'Perma-\nDelete','Delete\nWord',,,,],
[,,,'Go to\nPrevious\nWord',,,,],
[,,,'Go to\nStart',,,,],
[,,,'Go to\nEnd',,,,],
,
[,,,,'Expand\nList',,,],
,
,
[,,,'Go to\nNext\nWord',,,,],
,
,
['grn','Next Node\nin Tree',,,,,,],
,
,
,
,
,
,
['grn','Expand\nTree',,,,,,],
,
['grn','Previous\nNode\nin Tree',,,,,,],
,
,
['grn','Collapse\nNode',,,,,,],
['grn','Expand\nNode',,,,,,],
,
[,,,'Start Menu','Cycle\nWindows',,,],
['mag','Help',,,,,,],
['mag','Rename',,,,,,],
['mag','Find',,,,,,],
['grn','Address\nBar',,'Close\nDoc','Close\nWindow',,,],
['mag','Reload',,,,,,],
['grn','Cycle\nPanes',,,'Cycle\nDialogs',,,],
,
,
,
['grn','File Menu','Context\nMenu',,,,,],
['mag','Fullscreen',,,,,,],
,
,
,
,
,
['grn','Start Menu',,,,,,],
['grn','Context\nMenu',,,,,,],
,
,
,
,
,
,
,
,
,
,
,

]
Gam_Table['leg'][sLay] =
[
['yel','Selection'],
['grn','Navigation'],
['mag','Special Actions']
]
Gam_Table['com'][sLay] =
[       
'Win + R = Run Dialog',
'Win + M = Minimize All',
'Win + M + Shift = Undo Minimize',
'Win + F1 = Help',
'Win + E = Windows Explorer',
'Win + F = Find Files/Folders',
'Win + D = Minimize to Desktop',
'Win + L = Log Off',
'Win + P = Print Manager',
'Win + C = Control Panel',
'Win + V = Clipboard',
'Win + K = Keyboard Properties',
'Win + A = Accessibility Options',
'Win + Space = IntelliType Icon',
'Win + S = Caps Lock',
'Win + Tab = Cycle Taskbar',
'Win + Pause = System Properties',
'Win + Ctrl + Tab = Switch between Start Menu and Quicklaunch Toolbar',
'Win + Ctrl + F = Find Computer',
'Ctrl + Alt + Del = Close Program Dialog',
'Alt + Numpad Sequence = Extended Characters',
'Shift x 5 Times = Toggle StickyKeys',
'Shift x 8 Seconds = Toggle FilterKeys',
'LAlt + LShift + NmLk = Toggle MouseKeys',
'LAlt + LShift + PrtScr = Toggle High Contrast Colors',
'Shift + Click + CLOSE BUTTON = Close Window and All Descendents'
]
Gam_Table['mou'][sLay] = []
Gam_Table['joy'][sLay] = []
Gam_Table['add'][sLay] = []
