sLay = 'ATUS104'
Gam_Table['gam'][sLay] = 'FarCry'
Gam_Table['aut'][sLay] = ''
Gam_Table['key'][sLay] =
[
,
,
['red','Quick\nSlot 1',,,,,,],
['red','Quick\nSlot 2',,,,,,],
['red','Quick\nSlot 3',,,,,,],
['red','Quick\nSlot 4',,,,,,],
,
,
,
['blu',,'Binoculars',,,,,],
,
,
['blu','Zoom Out',,,,,,],
['blu','Zoom In',,,,,,],
,
['mag','Briefing /\nScoreboard',,,,,,],
['grn','Lean\nLeft',,,,,,],
['grn','Move\nForward',,,,,,],
['grn','Lean\nRight',,,,,,],
['red','Reload',,,,,,],
,
['mag','Chat All',,,,,,],
['mag','Chat Team',,,,,,],
,
,
,
,
,
['blu',,'Flashlight /\nHeadlight',,,,,],
,
['grn','Strafe\nLeft',,,,,,],
['grn','Move\nBackward',,,,,,],
['grn','Strafe\nRight',,,,,,],
['grn','Enter/Exit\nVehicle /\nUse Item',,,,,,],
['red','Throw\nGrenade',,,,,,],
['red','Cycle\nGrenades',,,,,,],
['red','Drop\nWeapon',,,,,,],
,
,
,
,
,
,
['grn','Sprint / Change Seat',,,,,,],
,
['grn','Run / Walk',,,,,,],
['red','Toggle\nWeapon\nMode',,,,,,],
,
['grn','Lie Prone',,,,,,],
['blu','Binoculars',,,,,,],
,
,
,
,
,
,
['grn','Crouch / Duck',,,,,,],
,
['grn','Jump / Hold Breath',,,,,,],
,
,
,
,
,
,
,
['blu','CryVision',,,,,,],
,
['red','Cycle\nWeapons\nUp',,,,,,],
['red','Cycle\nWeapons\nDown',,,,,,],
,
['red','Toggle\nWeapon\nMode',,,,,,],
['grn','Lean\nLeft',,,,,,],
['grn','Strafe\nLeft',,,,,,],
,
['blu','Flashlight',,,,,,],
['red','Throw\nGrenade',,,,,,],
['grn','Move\nForward',,,,,,],
['grn','Move\nBackward',,,,,,],
['grn','Crouch / Duck',,,,,,],
,
['grn','Lean\nRight',,,,,,],
['grn','Strafe\nRight',,,,,,],
,
,
,
,
['grn','Jump /\nEnter\nVehicle /\nUse Item',,,,,,],
['mag','Enter\nLimbo',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,

]
Gam_Table['leg'][sLay] =
[
['grn','Movement'],
['red','Combat'],
['blu','Vision'],
['mag','Game Controls']
]
Gam_Table['com'][sLay] = []
Gam_Table['mou'][sLay] =
[
'Left Mouse Button: Attack',
'Right Mouse Button: Use weapon sight',
'Mouse Wheel Down: Cycle weapons down, Zoom in',
'Mouse Wheel Up: Cycle weapons up, Zoom out'
]
Gam_Table['joy'][sLay] = []
Gam_Table['add'][sLay] = []
