sLay = 'ATUS104'
Gam_Table['gam'][sLay] = 'FreeLancer'
Gam_Table['aut'][sLay] = ''
Gam_Table['key'][sLay] =
[
,
,
['red','Weapon 1','Assign',,,,,],
['red','Weapon 2','Assign',,,,,],
['red','Weapon 3','Assign',,,,,],
['red','Weapon 4','Assign',,,,,],
['red','Weapon 5','Assign',,,,,],
['red','Weapon 6','Assign',,,,,],
['red','Weapon 7','Assign',,,,,],
['red','Weapon 8','Assign',,,,,],
['red','Weapon 9','Assign',,,,,],
['red','Weapon 10','Assign',,,,,],
,
,
['mag','Minimize HUD',,,,,,],
['grn','Afterburner',,,,,,],
['red','Launch\nMissile','Launch\nTorpedo',,,,,],
['grn','Increase\nThrust','Cruise',,,,,],
['red','Launch\nMine','Launch\nDisruptor',,,,,],
['yel','Next\nEnemy','Previous\nEnemy',,,,,],
['yel','Next\nTarget','Previous\nTarget','Clear',,,,],
,
,
,
['yel','Scan\nCargo',,,,,,],
['yel','Hail\nTarget',,,,,,],
,
,
,
,
['grn','Strafe\nLeft',,,,,,],
['grn','Decrease\nThrust',,,,,,],
['grn','Strafe\nRight',,,,,,],
['red','Shield\nBattery',,,,,,],
['red','Nanobot',,,,,,],
['blu','Turret\nView',,,,,,],
,
,
,
,
,
,
,
,
,
['grn','Kill\nEngine',,,,,,],
['grn','Reverse\nThrust',,,,,,],
['red','Launch\nCounter-\nmeasure',,,,,,],
['blu','Rear\nView',,'Change\nView',,,,],
['red','Tractor\nOne Item','Tractor\nAll Items',,,,,],
['yel','Target\nObjective',,,,,,],
,
,
,
,
,
,
,
['mag','Toggle Mouse Flight',,,,,,],
,
,
,
,
['grn','Strafe\nLeft',,,,,,],
,
,
['grn','Increase\nThrust',,,,,,],
['grn','Decrease\nThrust',,,,,,],
,
,
['grn','Strafe\nRight',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
['grn','Free\nFlight',,,,,,],
['mag','Main\nMenu',,,,,,],
['grn','Go To',,,,,,],
['grn','Dock',,,,,,],
['grn','Join\nFormation',,,,,,],
['yel','Story Star',,,,,,],
['yel','Nav Map',,,,,,],
['yel','Inventory',,,,,,],
['yel','Reputation',,,,,,],
['yel','Infor-\nmation',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,

]
Gam_Table['leg'][sLay] =
[
['red','Combat'],
['yel','Targeting'],
['grn','Navigation'],
['blu','Camera'],
['mag','Game Controls']
]
Gam_Table['com'][sLay] = []
Gam_Table['mou'][sLay] = []
Gam_Table['joy'][sLay] = []
Gam_Table['add'][sLay] = []
