sLay = 'ATUS104'
Gam_Table['gam'][sLay] = 'SimuTrans'
Gam_Table['aut'][sLay] = ''
Gam_Table['key'][sLay] =
[
,
,
['blu',,'Cycle\nStation\nInfo',,,,,],
,
['blu',,'Toggle\nGrid',,,,,],
,
,
,
,
,
,
,
['blu','Darken\nDisplay',,,,,,],
['blu','Lighten\nDisplay',,,,,,],
['yel','Close All Windows',,,,,,],
,
['mag',,'Create\nNew World',,,,,],
['yel','Manage\nLines','Super\nFast\nSpeed',,,,,],
['red','Electrify\nTrack',,,,,,],
['red','Destroy',,,,,,],
['red','Build Last\nRailway','City\nList',,,,,],
,
['red','Raise Land',,,,,,],
['red',,'Build\nPower\nPlant',,,,,],
,
['mag','Pause\nGame','Cycle\nPlayer\nCompanies',,,,,],
,
,
,
,
['red','Query',,,,,,],
['red','Build Last\nRoadway','Save\nGame',,,,,],
['red','Lower Land',,,,,,],
['yel','Finances',,,,,,],
['red','Build\nTransform\nStation','Goods\nList',,,,,],
['red',,'Build HQ',,,,,],
,
['yel','Player List',,,,,,],
['red','Build\nPower\nLines','Load\nGame',,,,,],
,
['blu',,'Cycle\nBuildings\n& Trees',,,,,],
,
,
,
,
['red','Undo Last\nRoute',,,,,,],
['mag',,'Create\nNew World',,,,,],
['mag','Capture\nScreen','Build\nNew City',,,,,],
['blu','Toggle\nStation\nFeeder\nZones','Vehicle\nList',,,,,],
['red','Block\nRepair','Mailbox',,,,,],
,
['yel','Map','Set\nMarker',,,,,],
['mag','Game\nSpeed -','Zoom\nView Out',,,,,],
['mag','Game\nSpeed +','Zoom\nView In',,,,,],
,
,
,
,
,
,
,
,
['yel','Close\nTop-Most\nWindow',,,,,,],
['blu','Pan Left',,,,,,],
,
,
['blu','Pan Up',,,,,,],
['blu','Pan Down',,,,,,],
['blu','Zoom In',,,,,,],
['blu','Zoom Out',,,,,,],
['blu','Pan Right',,,,,,],
,
['blu','Pan\nUp-Left',,,,,,],
['blu','Pan Left',,,,,,],
['blu','Pan\nDown-\nLeft',,,,,,],
,
['blu','Pan Up',,,,,,],
,
['blu','Pan Down',,,,,,],
,
,
['blu','Pan\nUp-Right',,,,,,],
['blu','Pan Right',,,,,,],
['blu','Pan\nDown-\nRight',,,,,,],
,
,
,
,
['yel','Close\nTop-Most\nWindow',,,,,,],
['yel','Help',,,,,,],
,
,
,
,
,
,
,
,
['mag','Pause\nGame',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,

]
Gam_Table['leg'][sLay] =
[
['red','Tools'],
['yel','Windows'],
['blu','Camera'],
['mag','System']
]
Gam_Table['com'][sLay] =
[
'CTRL + Tool = Build on upper level, or construct slower route over faster route.'
]
Gam_Table['mou'][sLay] = []
Gam_Table['joy'][sLay] = []
Gam_Table['add'][sLay] = []
