sLay = 'ATUS104'
Gam_Table['gam'][sLay] = 'Jagged Alliance'
Gam_Table['aut'][sLay] = ''
Gam_Table['key'][sLay] =
[
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
[,,,,'Quick\nLoad',,,],
,
,
,
['mag','Inventory',,,,,,],
['mag','Options',,,,,,],
['mag','Pause\nGame',,,,,,],
,
,
,
,
,
['mag','Merc\nStats',,,'Quick\nSave',,,],
['red','End Turn',,,,,,],
,
,
,
,
,
['mag','Repeat\nLast\nMessage',,,,,,],
,
,
,
['yel','Show Next\nVisible Enemy',,,,,,],
['red','(Hold)\nSneak',,,,,,],
,
['mag','Magnify\nItems',,,,,,],
['red','Switch\nPlaces',,,'Exit\nGame',,,],
['mag','Compress\nTime',,,,,,],
,
,
,
['mag','Map\nScreen',,,,,,],
,
,
,
['red','(Hold)\nSneak',,,,,,],
['red','(Hold)\nWalk Backward /\nHand Cursor',,,,,,],
['red','Crouch',,,,,,],
['yel','Select Next Merc',,,,,,],
['red','Crouch',,,,,,],
['red','(Hold)\nWalk Backward /\nHand Cursor',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
['red','Cancel\nAction',,,,,,],
['yel','Select\nMerc 1',,,,,,],
['yel','Select\nMerc 2',,,,,,],
['yel','Select\nMerc 3',,,,,,],
['yel','Select\nMerc 4',,,,,,],
['yel','Select\nMerc 5',,,,,,],
['yel','Select\nMerc 6',,,,,,],
['yel','Select\nMerc 7',,,,,,],
['yel','Select\nMerc 8',,,,,,],
['yel','Show\nEnemies\nVisible\nto Merc',,,,,,],
['mag','Options\nMenu',,,,,,],
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,
,

]
Gam_Table['leg'][sLay] =
[
['red','Action'],
['yel','Selection'],
['mag','Game Controls']
]
Gam_Table['com'][sLay] =
[
'CTRL + Right Click on Item = Magnify Item',
'SHIFT + Double Left Click on Map = Sneak While Moving to Cursor',
'CTRL + Double Left Click on Map = Move Backwards to Cursor'
]
Gam_Table['mou'][sLay] =
[
'Double Left Click on Merc = Select Merc',
'Double Left Click on Map = Move Merc to Cursor',
'Double Left Click on Door = Open Door',
'Left Click + Right Click on Map = Move Everyone to Cursor',
'Hold ALT with Cursor over Merc = Crouch Down',
'Right Click then Left Click on Merc = Crouch Down',
'Right Click then Left Click on Map = Look Toward Cursor',
'Right Click on Map then Left Click on Enemy = Target Enemy',
'Target Enemy then Right Click Repeatedly = Tighten Aim',
'Target Enemy then Left Click = Fire Weapon',
'Right Click on Map then Left Click on Target = Use Item',
'Right Click on Secondary Weapon = Swap Held Weapons'
]
Gam_Table['joy'][sLay] = []
Gam_Table['add'][sLay] = []
